// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { VerticalBox, Palette } from "std-widgets.slint";
import { Icon, IconDisplay, IconSet } from "@lucide";
import { HorizontalLine } from "horizontal_line.slint";
import { Card } from "card.slint";
import { State } from "../state.slint";

export component BoolSetting inherits Card {
    in property <string> label;
    in property <Icon> icon;
    in property <[{value: bool, label: string}]> items;
    in-out property <bool> active_value;

    width: 100%;

    VerticalBox {
        height: 100%;

        HorizontalLayout {
            IconDisplay {
                icon: icon;
                stroke: Palette.foreground;
                size: 14px;
            }

            Text {
                text: " " + label;
            }
        }

        HorizontalLine { }

        for item in items: Rectangle {
            HorizontalLayout {
                IconDisplay {
                    icon: item.value == active_value ? IconSet.Disc : IconSet.Circle;
                    stroke: item.value == active_value ? Palette.accent-background : Palette.foreground;
                    size: 14px;
                }

                Text {
                    text: " " + item.label;
                }
            }

            TouchArea {
                clicked => {
                    active_value = item.value;
                    State.write_config();
                }
            }
        }
    }
}
