// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { State } from "../state.slint";
import { MyPalette } from "../styling.slint";
import { IconButton } from "icon-button.slint";
import { IconSet } from "@lucide";
import { Card } from "card.slint";
import { IconButtonKind } from "../types.slint";
import { HorizontalLine } from "horizontal-line.slint";

export component ConfirmConversionModal inherits Card {
    width: 600px;
    height: 400px;

    ScrollView {
        height: parent.height - toolbar.height;
        x: 0px;
        y: 0px;

        VerticalLayout {
            alignment: start;
            padding: 20px;
            spacing: 5px;

            Text {
                text: "Picked \{State.adding-games.length} games, are you sure you want to continue?\n";
            }

            for queued in State.adding-games: Text {
                text: "• \{queued.standard.game-title} [\{queued.standard.game-id}]";
                overflow: elide;
            }
        }
    }

    toolbar := VerticalLayout {
        height: self.min-height;
        x: 0px;
        y: parent.height - self.height;

        HorizontalLine { }

        HorizontalLayout {
            alignment: end;
            padding: 10px;
            spacing: 10px;

            IconButton {
                label: "Cancel";
                clicked => {
                    State.adding-games = [];
                }
            }

            IconButton {
                label: "Ok";
                kind: IconButtonKind.Primary;
                icon: IconSet.Rocket;
                clicked => {
                    State.add-to-queue();
                    State.start-conversion();
                }
            }
        }
    }
}
