// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconButton, IconButtonKind } from "icon-button.slint";
import { IconSet, IconDisplay } from "@lucide";
import { MyPalette } from "../styling.slint";
import { UiState } from "../ui-state.slint";
import { Message, Dispatcher } from "../messages.slint";

export component ConversionQueueToolbar inherits HorizontalLayout {
    alignment: space-between;
    height: 38px;

    HorizontalLayout {
        padding-top: 10px;
        spacing: 5px;

        IconDisplay {
            icon: IconSet.ChevronRight;
            size: 18px;
            stroke: MyPalette.foreground;
        }

        Text {
            text: "Conversion queue";
            font-size: 18px;
        }
    }

    VerticalLayout {
        alignment: center;

        if UiState.conversion-queue.length > 0: IconButton {
            icon: IconSet.X;
            label: "Cancel all conversions";
            kind: IconButtonKind.Primary;
            clicked => Dispatcher.dispatch(Message.CancelAllConversions, "");
        }
    }
}
