// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconSet } from "@lucide";
import { IconButton } from "icon-button.slint";
import { QueuedConversion, ConversionKind } from "../types.slint";
import { MyPalette } from "../styling.slint";
import { Logic } from "../logic.slint";

export component ConversionRow inherits Rectangle {
    in property <QueuedConversion> conv;

    callback cancel();

    pure function label(conv: QueuedConversion) -> string {
        if conv.kind == ConversionKind.Standard {
            "↑ Conversion: " + conv.in-path
        } else if conv.kind == ConversionKind.Archive {
            "↓ Archive: " + conv.out-path
        } else {
            "↔ Scrub: " + conv.game-title
        }
    }

    height: 24px;

    Text {
        x: 5px;
        y: 5px;
        text: label(conv);
        overflow: elide;
    }

    IconButton {
        x: parent.width - 24px;
        y: 0px;
        icon: IconSet.X;
        tooltip: "Cancel conversion";
        height: 24px;
        width: 24px;
        squared: true;
        clicked => cancel();
    }
}
