// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconSet } from "@lucide";
import { IconButton } from "icon-button.slint";
import { MyPalette } from "../styling.slint";
import { UiState } from "../ui-state.slint";

export component ConversionRow inherits Rectangle {
    in property <string> label;

    callback cancel();

    height: 24px;

    Text {
        x: 5px;
        y: 5px;
        text: label;
        overflow: elide;
    }

    IconButton {
        x: parent.width - 24px;
        y: 0px;
        icon: IconSet.X;
        tooltip: "Cancel conversion";
        height: 24px;
        width: 24px;
        squared: true;
        clicked => cancel();
    }
}
