// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { State } from "../state.slint";
import { MyPalette } from "../styling.slint";
import { IconButton } from "icon-button.slint";
import { HorizontalLine } from "horizontal-line.slint";
import { IconSet } from "@lucide";
import { Card } from "card.slint";
import { IconButtonKind } from "../types.slint";

export component DeletingDirModal inherits Card {
    width: 600px;
    height: 400px;

    Text {
        y: 20px;
        x: 20px;
        width: parent.width - 40px;
        text: "Are you sure you want to delete \"\{State.deleting-dir}\"?\n\nThis is irreversible!!";
        wrap: char-wrap;
    }

    toolbar := VerticalLayout {
        height: self.min-height;
        x: 0px;
        y: parent.height - self.height;

        HorizontalLine { }

        HorizontalLayout {
            spacing: 10px;
            padding: 10px;
            alignment: end;

            IconButton {
                label: "Cancel";
                clicked => {
                    State.deleting-dir = "";
                }
            }

            IconButton {
                label: "Delete";
                icon: IconSet.Trash;
                kind: IconButtonKind.Danger;
                clicked => State.delete-dir();
            }
        }
    }
}
