// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { GameFilter } from "game-filter.slint";
import { ShowWiiGc } from "show-wii-gc.slint";
import { IconButton } from "icon-button.slint";
import { IconButtonKind } from "../types.slint";
import { IconSet, IconDisplay } from "@lucide";
import { State } from "../state.slint";
import { SortGamesAndHbcApps } from "sort-games-and-hbc-apps.slint";
import { ViewAs } from "view-as.slint";
import { MyPalette } from "../styling.slint";

export component GamesToolbar inherits HorizontalLayout {
    alignment: space-between;
    height: 38px;

    HorizontalLayout {
        padding-top: 10px;
        spacing: 5px;

        IconDisplay {
            icon: IconSet.ChevronRight;
            size: 18px;
            stroke: MyPalette.foreground;
        }

        Text {
            text: "\{State.game-list.games.length} Game\{State.game-list.games.length == 1 ? "" : "s"} (\{State.game-list.total-size.to-fixed(2)} GiB)";
            font-size: 18px;
        }
    }

    HorizontalLayout {
        spacing: 10px;

        GameFilter { }

        ShowWiiGc { }

        SortGamesAndHbcApps { }

        ViewAs { }

        VerticalLayout {
            alignment: center;

            HorizontalLayout {
                spacing: 10px;

                IconButton {
                    icon: IconSet.RotateCw;
                    tooltip: "Refresh games and apps";
                    rounded: true;
                    kind: IconButtonKind.Primary;
                    font-size: 18px;
                    width: 34px;
                    height: 34px;
                    clicked => State.refresh-all();
                }

                IconButton {
                    icon: IconSet.Plus;
                    tooltip: "Add new games";
                    rounded: true;
                    kind: IconButtonKind.Primary;
                    font-size: 18px;
                    width: 34px;
                    height: 34px;
                    clicked => State.pick-games();
                }

                IconButton {
                    icon: IconSet.FolderPlus;
                    tooltip: "Add new games from a folder (recursively)";
                    rounded: true;
                    kind: IconButtonKind.Primary;
                    font-size: 18px;
                    width: 34px;
                    height: 34px;
                    clicked => State.pick-games-r();
                }
            }
        }
    }
}
