// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconSet, IconDisplay } from "@lucide";
import { VerticalLine } from "vertical-line.slint";
import { IconButton } from "icon-button.slint";
import { Game } from "../types.slint";
import { MyPalette } from "../styling.slint";
import { State } from "../state.slint";

export component GameRow inherits HorizontalLayout {
    in property <Game> game;

    alignment: space-between;
    padding-left: 5px;

    HorizontalLayout {
        spacing: 5px;

        VerticalLayout {
            alignment: center;

            IconDisplay {
                icon: game.is-wii ? IconSet.Pointer : IconSet.Box;
                size: 14px;
                stroke: MyPalette.foreground;
            }
        }

        Text {
            height: 24px;
            vertical-alignment: center;
            text: "\{game.title} [\{game.id}]";
            overflow: elide;
        }
    }

    HorizontalLayout {
        Text {
            height: 24px;
            vertical-alignment: center;
            text: "\{game.size-gib} GiB  ";
        }

        VerticalLine { }

        IconButton {
            tooltip: "Game info";
            icon: IconSet.Info;
            height: 24px;
            width: 24px;
            squared: true;
            clicked => State.open-game-info(game);
        }

        VerticalLine { }

        IconButton {
            icon: IconSet.HardDriveDownload;
            tooltip: "Archive to PC";
            height: 24px;
            width: 24px;
            squared: true;
            clicked => State.archive-game(game);
        }

        VerticalLine { }

        IconButton {
            icon: IconSet.Trash;
            tooltip: "Delete game";
            height: 24px;
            width: 24px;
            squared: true;
            clicked => {
                State.deleting-dir = game.path;
            }
        }
    }
}
