// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { Game, MessageKind, Page } from "../types.slint";
import { VerticalBox } from "std-widgets.slint";
import { IconButton } from "icon-button.slint";
import { IconSet } from "@lucide";
import { State } from "../state.slint";

export component GameCard inherits Card {
    in property <Game> game;

    width: 168px;
    height: 205px;

    VerticalBox {
        HorizontalLayout {
            Text {
                text: game.id;
                wrap: no-wrap;
            }

            Text {
                text: game.size-gib + " GiB";
                wrap: no-wrap;
                horizontal-alignment: right;
            }
        }

        Image {
            source: game.cover;
            height: 93px;
        }

        Text {
            text: game.title;
            horizontal-alignment: center;
            wrap: no-wrap;
            overflow: elide;
        }

        HorizontalLayout {
            spacing: 5px;

            IconButton {
                label: "Info";
                icon: IconSet.Info;
                tooltip: "Game info";
                clicked => {
                    State.current-page = Page.Game;
                    State.current-game = game;
                }
            }

            IconButton {
                icon: IconSet.HardDriveDownload;
                tooltip: "Archive to PC";
            }

            IconButton {
                icon: IconSet.Trash;
                tooltip: "Delete game";
                clicked => {
                    State.message.kind = MessageKind.DeleteDir;
                    State.message.text = "Are you sure you want to delete \"" + game.title + "\"?\nThis is irreversible!";
                    State.message.data = game.path;
                }
            }
        }
    }
}
