// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ShowWiiGc } from "show-wii-gc.slint";
import { IconButton, IconButtonKind } from "icon-button.slint";
import { IconSet, IconDisplay } from "@lucide";
import { SortGamesAndHomebrewApps } from "sort-games-and-homebrew-apps.slint";
import { ViewAs } from "view-as.slint";
import { MyPalette } from "../styling.slint";
import { Rust } from "../rust.slint";
import { Config } from "../types.slint";

export component GamesToolbar inherits HorizontalLayout {
    in property <Config> config;

    alignment: space-between;
    height: 38px;

    HorizontalLayout {
        padding-top: 10px;
        spacing: 5px;

        IconDisplay {
            icon: IconSet.ChevronRight;
            size: 18px;
            stroke: MyPalette.foreground;
        }

        Text {
            text: "Games";
            font-size: 18px;
        }
    }

    HorizontalLayout {
        spacing: 10px;

        ShowWiiGc {
            config: config;
        }

        SortGamesAndHomebrewApps {
            config: config;
        }

        ViewAs { }

        VerticalLayout {
            alignment: center;

            HorizontalLayout {
                spacing: 10px;

                IconButton {
                    icon: IconSet.RotateCw;
                    tooltip: "Refresh games and apps";
                    rounded: true;
                    kind: IconButtonKind.Primary;
                    font-size: 18px;
                    width: 34px;
                    height: 34px;
                    clicked => Rust.refresh-all();
                }

                IconButton {
                    icon: IconSet.Plus;
                    tooltip: "Add new games";
                    rounded: true;
                    kind: IconButtonKind.Primary;
                    font-size: 18px;
                    width: 34px;
                    height: 34px;
                    clicked => Rust.pick-games(false);
                }

                IconButton {
                    icon: IconSet.FolderPlus;
                    tooltip: "Add new games from a folder (recursively)";
                    rounded: true;
                    kind: IconButtonKind.Primary;
                    font-size: 18px;
                    width: 34px;
                    height: 34px;
                    clicked => Rust.pick-games(true);
                }
            }
        }
    }
}
