// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { GameFilter } from "game-filter.slint";
import { ShowWiiGc } from "show-wii-gc.slint";
import { HorizontalBox } from "std-widgets.slint";
import { IconButton } from "icon-button.slint";
import { IconButtonKind } from "../types.slint";
import { IconSet } from "@lucide";
import { State } from "../state.slint";
import { SortGames } from "sort-games.slint";
import { ViewAs } from "view-as.slint";
import { TooltipArea } from "tooltip-area.slint";

export component GamesToolbar inherits HorizontalBox {
    alignment: space-between;

    GameFilter { }

    HorizontalLayout {
        spacing: 10px;

        ShowWiiGc { }

        SortGames { }

        ViewAs { }

        VerticalLayout {
            alignment: center;

            HorizontalLayout {
                spacing: 10px;

                IconButton {
                    icon: IconSet.RotateCw;
                    tooltip: "Refresh games and apps";
                    rounded: true;
                    kind: IconButtonKind.Primary;
                    font-size: 18px;
                    width: 34px;
                    height: 34px;
                    clicked => State.refresh-all();
                }

                IconButton {
                    icon: IconSet.Plus;
                    tooltip: "Add new games";
                    rounded: true;
                    kind: IconButtonKind.Primary;
                    font-size: 18px;
                    width: 34px;
                    height: 34px;
                    clicked => State.pick-games();
                }

                IconButton {
                    icon: IconSet.FolderPlus;
                    tooltip: "Add new games from a folder (recursively)";
                    rounded: true;
                    kind: IconButtonKind.Primary;
                    font-size: 18px;
                    width: 34px;
                    height: 34px;
                    clicked => State.pick-games-r();
                }
            }
        }
    }
}
