// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { GameFilter } from "game-filter.slint";
import { MirroredProperties } from "../mirrored-properties.slint";

export component GamesOtherToolbar inherits HorizontalLayout {
    alignment: space-between;
    height: 38px;
    padding-right: 20px;

    GameFilter { }

    Text {
        height: parent.height;
        vertical-alignment: center;
        horizontal-alignment: end;
        text: "\{MirroredProperties.games.length} game\{MirroredProperties.games.length == 1 ? "" : "s"}   ~ \{MirroredProperties.drive-info.games-gib.to-fixed(2)} GiB";
    }
}
