// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconSet, IconDisplay } from "@lucide";
import { VerticalLine } from "vertical-line.slint";
import { IconButton } from "icon-button.slint";
import { DisplayedGame } from "../types.slint";
import { MyPalette } from "../styling.slint";
import { Logic } from "../logic.slint";

export component GameRow inherits Rectangle {
    in property <DisplayedGame> game;

    callback open-info();
    callback delete();

    height: 24px;

    IconDisplay {
        x: 5px;
        y: 5px;
        icon: game.is-wii ? IconSet.Pointer : IconSet.Box;
        size: 14px;
        stroke: MyPalette.foreground;
    }

    Text {
        x: 5px + 14px + 5px;
        y: 5px;
        text: "\{game.title} [\{game.id}]";
        overflow: elide;
    }

    Text {
        x: parent.width - 75px - self.preferred-width - 5px;
        y: 5px;
        text: "\{game.size-gib.to-fixed(2)} GiB";
    }

    VerticalLine {
        x: parent.width - 75px;
        y: 0px;
        height: 24px;
    }

    IconButton {
        x: parent.width - 74px;
        y: 0px;
        tooltip: "Game info";
        icon: IconSet.Info;
        height: 24px;
        width: 24px;
        squared: true;
        clicked => open-info();
    }

    VerticalLine {
        x: parent.width - 50px;
        y: 0px;
        height: 24px;
    }

    IconButton {
        x: parent.width - 49px;
        y: 0px;
        icon: IconSet.HardDriveDownload;
        tooltip: "Archive to PC";
        height: 24px;
        width: 24px;
        squared: true;
        clicked => Logic.archive-game(game.idx);
    }

    VerticalLine {
        x: parent.width - 25px;
        y: 0px;
        height: 24px;
    }

    IconButton {
        x: parent.width - 24px;
        y: 0px;
        icon: IconSet.Trash;
        tooltip: "Delete game";
        height: 24px;
        width: 24px;
        squared: true;
        clicked => delete();
    }
}
