// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import {
    LineEdit,
    HorizontalBox,
    VerticalBox,
} from "std-widgets.slint";
import { MyPalette } from "../styling.slint";
import { IconSet, IconDisplay } from "@lucide";
import { State } from "../state.slint";

export component GameFilter inherits Card {
    width: 200px;
    clip: true;

    HorizontalLayout {
        VerticalBox {
            alignment: center;

            IconDisplay {
                icon: IconSet.Search;
                size: 14px;
                stroke: MyPalette.foreground;
            }
        }

        LineEdit {
            width: 175px;

            placeholder-text: "Search by Title/ID";
            text <=> State.game-filter;
            changed text => {
                State.filter-games();
            }
        }
    }
}
