// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView, Palette } from "std-widgets.slint";
import { DisplayedGame } from "../types.slint";
import { IconSet, IconDisplay } from "@lucide";
import { Link } from "link.slint";
import { Card } from "card.slint";
import { HorizontalLine } from "horizontal-line.slint";
import { MyPalette } from "../styling.slint";
import { IconButton, IconButtonKind } from "icon-button.slint";
import { Modal } from "modal.slint";
import { UiState } from "../ui-state.slint";
import { Message, Dispatcher } from "../messages.slint";

export component GameInfoModal inherits Modal {
    VerticalLayout {
        alignment: stretch;

        VerticalLayout {
            alignment: space-between;

            VerticalLayout {
                padding: 20px;
                spacing: 10px;

                Text {
                    text: UiState.current-game.title;
                    font-size: 18px;
                    overflow: elide;
                }

                Link {
                    icon: IconSet.Folder;
                    label: "Path: \{UiState.current-game.path}";
                    uri: UiState.current-game.path;
                }
            }

            if UiState.current-disc-info.path.is-empty: HorizontalLayout {
                spacing: 5px;
                alignment: center;

                IconDisplay {
                    icon: IconSet.TriangleAlert;
                    stroke: MyPalette.foreground;
                    size: 14px;
                }

                Text {
                    text: "Could not read disc info";
                }
            }

            if !UiState.current-disc-info.path.is-empty: HorizontalLayout {
                alignment: space-between;
                padding-right: 10px;
                padding-left: 20px;

                VerticalLayout {
                    spacing: 5px;
                    alignment: center;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.FileQuestionMark;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Format: \{UiState.current-disc-info.format}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Tag;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Game ID: \{UiState.current-disc-info.game-id}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.NotebookPen;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Game title: \{UiState.current-disc-info.game-title}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Globe;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Region: \{UiState.current-disc-info.region}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Pointer;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Is Wii: \{(UiState.current-disc-info.is-wii ? "yes" : "no")}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Box;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Is GameCube: \{(UiState.current-disc-info.is-gc ? "yes" : "no")}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Hash;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Disc number: \{UiState.current-disc-info.disc-number}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Pin;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Disc version: \{UiState.current-disc-info.disc-version}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.FingerprintPattern;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "CRC32: \{(UiState.current-disc-info.crc32.is-empty ? "N/A" : UiState.current-disc-info.crc32)}";
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    Image {
                        source: UiState.current-game.cover;
                        height: 200px;
                    }
                }
            }

            VerticalLayout { }
        }

        VerticalLayout {
            height: self.min-height;

            HorizontalLine { }

            HorizontalLayout {
                alignment: space-between;

                VerticalLayout {
                    alignment: center;
                    padding-left: 15px;

                    Link {
                        uri: "https://www.gametdb.com/Wii/\{UiState.current-game.id}";
                        label: "GameTDB page";
                    }
                }

                HorizontalLayout {
                    padding: 10px;
                    spacing: 10px;

                    IconButton {
                        label: "Get cheats";
                        tooltip: "Download txtcodes (change the source in settings)";
                        icon: IconSet.Skull;
                        clicked => Dispatcher.dispatch(Message.DownloadTxtCodes, UiState.current-game.path);
                    }

                    if UiState.current-disc-info.is-worth-scrubbing: IconButton {
                        label: "Scrub";
                        tooltip: "Remove update partition to save space";
                        icon: IconSet.Shredder;
                        clicked => {
                            UiState.scrubbing-current-game = true;
                        }
                    }

                    if !UiState.current-disc-info.path.is-empty: IconButton {
                        label: UiState.crc32-status.is-empty ? "CRC32" : UiState.crc32-status;
                        icon: IconSet.FingerprintPattern;
                        clicked => {
                            if UiState.crc32-status.is-empty {
                                Dispatcher.dispatch(Message.Checksum, UiState.current-game.path);
                            }
                        };
                    }

                    IconButton {
                        label: "Close";
                        kind: IconButtonKind.Primary;
                        clicked => {
                            UiState.current-game = { };
                            UiState.crc32-status = "";
                            UiState.current-disc-info = { };
                        }
                    }
                }
            }
        }
    }
}
