// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { Game, Page } from "../types.slint";
import { VerticalBox } from "std-widgets.slint";
import { IconButton } from "icon-button.slint";
import { IconSet, IconDisplay } from "@lucide";
import { State } from "../state.slint";
import { MyPalette } from "../styling.slint";

export component GameCard inherits Card {
    in property <Game> game;

    width: 168px;

    VerticalBox {
        HorizontalLayout {
            alignment: space-between;

            HorizontalLayout {
                IconDisplay {
                    icon: IconSet.Tag;
                    size: 13px;
                    stroke: MyPalette.foreground;
                }

                Text {
                    text: " " + game.id;
                    wrap: no-wrap;
                }
            }

            Text {
                text: game.size-gib + " GiB";
                wrap: no-wrap;
                horizontal-alignment: right;
            }
        }

        Image {
            source: game.cover;
            height: 93px;
        }

        Text {
            text: game.title;
            horizontal-alignment: center;
            wrap: no-wrap;
            overflow: elide;
        }

        HorizontalLayout {
            spacing: 5px;

            IconButton {
                label: "Info";
                icon: IconSet.Info;
                clicked => {
                    State.open-game-info(game);
                }
            }

            IconButton {
                icon: IconSet.HardDriveDownload;
                tooltip: "Archive to PC";
            }

            IconButton {
                icon: IconSet.Trash;
                tooltip: "Delete game";
                clicked => {
                    State.deleting-dir = game.path;
                }
            }
        }
    }
}
