// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView, Palette } from "std-widgets.slint";
import { Game } from "../types.slint";
import { IconSet, IconDisplay } from "@lucide";
import { Link } from "link.slint";
import { Card } from "card.slint";
import { HorizontalLine } from "horizontal-line.slint";
import { MyPalette } from "../styling.slint";
import { IconButton, IconButtonKind } from "icon-button.slint";
import { Modal } from "modal.slint";
import { Logic } from "../logic.slint";

export component GameInfoModal inherits Modal {
    in property <Game> game;

    callback closed();

    VerticalLayout {
        alignment: stretch;

        VerticalLayout {
            alignment: space-between;

            VerticalLayout {
                padding: 20px;
                spacing: 10px;

                Text {
                    text: game.title;
                    font-size: 18px;
                    overflow: elide;
                }

                Link {
                    icon: IconSet.Folder;
                    label: "Path: \{game.path}";
                    uri: game.path;
                }
            }

            if !game.disc-info-err.is-empty: HorizontalLayout {
                spacing: 5px;
                alignment: center;

                IconDisplay {
                    icon: IconSet.TriangleAlert;
                    stroke: MyPalette.foreground;
                    size: 14px;
                }

                Text {
                    text: game.disc-info-err;
                }
            }

            if game.disc-info-err.is-empty: HorizontalLayout {
                alignment: space-between;
                padding-right: 10px;
                padding-left: 20px;

                VerticalLayout {
                    spacing: 5px;
                    alignment: center;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.FileQuestionMark;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Format: \{game.disc-info.format}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Tag;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Game ID: \{game.disc-info.game-id}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.NotebookPen;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Game title: \{game.disc-info.game-title}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Globe;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Region: \{game.disc-info.region}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Pointer;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Is Wii: \{(game.disc-info.is-wii ? "yes" : "no")}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Box;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Is GameCube: \{(game.disc-info.is-gc ? "yes" : "no")}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Hash;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Disc number: \{game.disc-info.disc-number}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Pin;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Disc version: \{game.disc-info.disc-version}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.FingerprintPattern;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "CRC32: \{(game.crc32.is-empty ? "N/A" : game.crc32)}";
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    Image {
                        source: game.cover;
                        height: 200px;
                    }
                }
            }

            VerticalLayout { }
        }

        VerticalLayout {
            height: self.min-height;

            HorizontalLine { }

            HorizontalLayout {
                alignment: space-between;

                VerticalLayout {
                    alignment: center;
                    padding-left: 15px;

                    Link {
                        uri: "https://www.gametdb.com/Wii/\{game.id}";
                        label: "GameTDB page";
                    }
                }

                HorizontalLayout {
                    padding: 10px;
                    spacing: 10px;

                    if game.disc-info.is-worth-scrubbing: IconButton {
                        label: "Scrub";
                        tooltip: "Remove update partition to save space";
                        icon: IconSet.Shredder;
                        clicked => Logic.scrub-game(game);
                    }

                    if game.disc-info-err.is-empty: IconButton {
                        label: Logic.crc32-status.is-empty ? "CRC32" : Logic.crc32-status;
                        icon: IconSet.FingerprintPattern;
                        clicked => {
                            if Logic.crc32-status.is-empty {
                                Logic.checksum(game);
                            }
                        };
                    }

                    IconButton {
                        label: "Close";
                        kind: IconButtonKind.Primary;
                        clicked => closed();
                    }
                }
            }
        }
    }
}
