// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { HbcApp } from "../types.slint";
import { IconButton } from "icon-button.slint";
import { IconSet, IconDisplay } from "@lucide";
import { State } from "../state.slint";
import { MyPalette } from "../styling.slint";

export component HbcAppCard inherits Card {
    in property <HbcApp> app;

    width: 171px;

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        HorizontalLayout {
            alignment: space-between;

            HorizontalLayout {
                spacing: 5px;

                IconDisplay {
                    icon: IconSet.Milestone;
                    size: 13px;
                    stroke: MyPalette.foreground;
                }

                Text {
                    text: app.meta.version;
                    wrap: no-wrap;
                }
            }

            Text {
                text: "\{app.size-mib.to-fixed(2)} MiB";
                wrap: no-wrap;
                horizontal-alignment: right;
            }
        }

        Image {
            source: app.icon;
            height: 48px;
        }

        Text {
            text: app.meta.name;
            horizontal-alignment: center;
            wrap: no-wrap;
            overflow: elide;
        }

        HorizontalLayout {
            spacing: 5px;

            IconButton {
                label: "Info";
                icon: IconSet.Info;
            }

            IconButton {
                icon: IconSet.Trash;
                tooltip: "Delete app";
                clicked => {
                    State.deleting-dir = app.path;
                }
            }
        }
    }
}
