// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconButton } from "icon-button.slint";
import { IconButtonKind } from "../types.slint";
import { IconSet } from "@lucide";
import { State } from "../state.slint";
import { ViewAs } from "view-as.slint";
import { HbcAppsFilter } from "hbc-apps-filter.slint";
import { SortGamesAndHbcApps } from "sort-games-and-hbc-apps.slint";

export component HbcAppsToolbar inherits HorizontalLayout {
    alignment: space-between;
    height: self.min-height;

    HbcAppsFilter { }

    HorizontalLayout {
        spacing: 10px;

        SortGamesAndHbcApps { }

        ViewAs { }

        VerticalLayout {
            alignment: center;

            HorizontalLayout {
                spacing: 10px;

                IconButton {
                    icon: IconSet.RotateCw;
                    tooltip: "Refresh games and apps";
                    rounded: true;
                    kind: IconButtonKind.Primary;
                    font-size: 18px;
                    width: 34px;
                    height: 34px;
                    clicked => State.refresh-all();
                }

                IconButton {
                    icon: IconSet.Plus;
                    tooltip: "Add new apps";
                    rounded: true;
                    kind: IconButtonKind.Primary;
                    font-size: 18px;
                    width: 34px;
                    height: 34px;
                }
            }
        }
    }
}
