// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { MyPalette } from "../styling.slint";
import { HomebrewAppsFilter } from "homebrew-apps-filter.slint";
import { HomebrewApp, DriveInfo } from "../types.slint";

export component HomebrewAppsOtherToolbar inherits HorizontalLayout {
    in property <[HomebrewApp]> apps;
    in property <DriveInfo> drive-info;

    alignment: space-between;
    height: 38px;
    padding-right: 10px;

    HomebrewAppsFilter { }

    Text {
        height: parent.height;
        vertical-alignment: center;
        horizontal-alignment: end;
        text: "\{apps.length} app\{apps.length == 1 ? "" : "s"}   ~ \{drive-info.apps-mib.to-fixed(2)} MiB";
    }
}
