// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconSet, IconDisplay } from "@lucide";
import { VerticalLine } from "vertical-line.slint";
import { IconButton } from "icon-button.slint";
import { HomebrewApp } from "../types.slint";
import { MyPalette } from "../styling.slint";
import { Logic } from "../logic.slint";
import { TooltipArea } from "tooltip-area.slint";

export component HomebrewAppRow inherits Rectangle {
    in property <HomebrewApp> app;
    callback open-info();

    private property <string> update: app.osc-i == -1 || Logic.osc-apps[app.osc-i].meta.version == app.meta.version ? "" : Logic.osc-apps[app.osc-i].meta.version;

    height: 24px;

    name := Text {
        x: 5px;
        y: 5px;
        text: "\{app.meta.name} (\{app.meta.version})";
        overflow: elide;
    }

    if !update.is-empty: TooltipArea {
        x: 5px + name.preferred-width + 5px;
        y: 5px;
        width: 13px;
        height: 13px;
        tooltip: "Update available: \{update}";

        IconDisplay {
            icon: IconSet.ArrowUp;
            size: 13px;
            stroke: MyPalette.foreground;
        }
    }

    Text {
        x: parent.width - 75px - self.preferred-width - 5px;
        y: 5px;
        text: "\{app.size-mib.to-fixed(2)} MiB";
    }

    VerticalLine {
        x: parent.width - 75px;
        y: 0px;
        height: 24px;
    }

    IconButton {
        x: parent.width - 74px;
        y: 0px;
        tooltip: "App info";
        icon: IconSet.Info;
        height: 24px;
        width: 24px;
        squared: true;
        clicked => open-info();
    }

    VerticalLine {
        x: parent.width - 50px;
        y: 0px;
        height: 24px;
    }

    if update.is-empty: TooltipArea {
        tooltip: "App is up to date";
        x: parent.width - 49px;
        y: 0px;
        height: 24px;
        width: 24px;

        IconDisplay {
            x: (parent.width - self.width) / 2;
            y: (parent.height - self.height) / 2;
            icon: IconSet.CloudCheck;
            size: 13px;
            stroke: MyPalette.foreground;
        }
    }

    if !update.is-empty: IconButton {
        x: parent.width - 49px;
        y: 0px;
        tooltip: "Update app to \{update}";
        icon: IconSet.ArrowUp;
        height: 24px;
        width: 24px;
        squared: true;
        clicked => {
            Logic.install-osc-app(Logic.osc-apps[app.osc-i]);
        }
    }

    VerticalLine {
        x: parent.width - 25px;
        y: 0px;
        height: 24px;
    }

    IconButton {
        x: parent.width - 24px;
        y: 0px;
        icon: IconSet.Trash;
        tooltip: "Delete app";
        height: 24px;
        width: 24px;
        squared: true;
        clicked => Logic.delete-homebrew-app(app);
    }
}
