// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconButton } from "icon-button.slint";
import { IconButtonKind } from "../types.slint";
import { IconSet, IconDisplay } from "@lucide";
import { State } from "../state.slint";
import { ViewAs } from "view-as.slint";
import { SortGamesAndHomebrewApps } from "sort-games-and-homebrew-apps.slint";
import { MyPalette } from "../styling.slint";

export component HomebrewAppsToolbar inherits HorizontalLayout {
    alignment: space-between;
    height: 38px;

    HorizontalLayout {
        padding-top: 10px;
        spacing: 5px;

        IconDisplay {
            icon: IconSet.ChevronRight;
            size: 18px;
            stroke: MyPalette.foreground;
        }

        Text {
            text: "Homebrew apps";
            font-size: 18px;
        }
    }

    HorizontalLayout {
        spacing: 10px;

        SortGamesAndHomebrewApps { }

        ViewAs { }

        VerticalLayout {
            alignment: center;

            HorizontalLayout {
                spacing: 10px;

                IconButton {
                    icon: IconSet.RotateCw;
                    tooltip: "Refresh games and apps";
                    rounded: true;
                    kind: IconButtonKind.Primary;
                    font-size: 18px;
                    width: 34px;
                    height: 34px;
                    clicked => State.refresh-all();
                }

                IconButton {
                    icon: IconSet.Plus;
                    tooltip: "Add new apps";
                    rounded: true;
                    kind: IconButtonKind.Primary;
                    font-size: 18px;
                    width: 34px;
                    height: 34px;
                    clicked => State.install-homebrew-apps();
                }
            }
        }
    }
}
