// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconSet, IconDisplay } from "@lucide";
import { VerticalLine } from "vertical-line.slint";
import { IconButton } from "icon-button.slint";
import { DisplayedHomebrewApp } from "../types.slint";
import { MyPalette } from "../styling.slint";
import { UiState } from "../ui-state.slint";
import { Message, Dispatcher } from "../messages.slint";

export component HomebrewAppRow inherits Rectangle {
    in property <DisplayedHomebrewApp> app;

    private property <string> update: app.osc-app.version == app.version ? "" : app.osc-app.version;

    height: 24px;

    name := Text {
        x: 5px;
        y: 5px;
        text: "\{app.name} (\{app.version})";
        overflow: elide;
    }

    Text {
        x: parent.width - 75px - self.preferred-width - 5px;
        y: 5px;
        text: "\{app.size-mib.to-fixed(2)} MiB";
    }

    VerticalLine {
        x: parent.width - 75px;
        y: 0px;
        height: 24px;
    }

    IconButton {
        x: parent.width - 74px;
        y: 0px;
        tooltip: "App info";
        icon: IconSet.Info;
        height: 24px;
        width: 24px;
        squared: true;
        clicked => {
            UiState.current-homebrew-app = app;
        }
    }

    VerticalLine {
        x: parent.width - 50px;
        y: 0px;
        height: 24px;
    }

    IconButton {
        x: parent.width - 49px;
        y: 0px;
        tooltip: update.is-empty ? "App is up to date" : "Update app to \{update}";
        icon: IconSet.ArrowUp;
        height: 24px;
        width: 24px;
        squared: true;
        disabled: update.is-empty;
        clicked => Dispatcher.dispatch(Message.InstallOscApp, app.osc-app.slug);
    }

    VerticalLine {
        x: parent.width - 25px;
        y: 0px;
        height: 24px;
    }

    IconButton {
        x: parent.width - 24px;
        y: 0px;
        icon: IconSet.Trash;
        tooltip: "Delete app";
        height: 24px;
        width: 24px;
        squared: true;
        clicked => {
            UiState.homebrew-app-to-delete = app;
        }
    }
}
