// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { DisplayedHomebrewApp } from "../types.slint";
import { IconButton } from "icon-button.slint";
import { IconSet, IconDisplay } from "@lucide";
import { MyPalette } from "../styling.slint";
import { UiState } from "../ui-state.slint";
import { TooltipArea } from "tooltip-area.slint";
import { Message, Dispatcher } from "../messages.slint";

export component HomebrewAppCard inherits Card {
    in property <DisplayedHomebrewApp> app;

    private property <string> update: app.osc-app.version == app.version ? "" : app.osc-app.version;

    width: 172px;
    height: self.min-height;

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        HorizontalLayout {
            alignment: space-between;

            HorizontalLayout {
                spacing: 5px;

                IconDisplay {
                    icon: IconSet.Tag;
                    size: 13px;
                    stroke: MyPalette.foreground;
                }

                Text {
                    text: app.version;
                    wrap: no-wrap;
                    overflow: elide;
                }

                if !update.is-empty: TooltipArea {
                    width: 13px;
                    height: 13px;
                    tooltip: "Update available: \{update}";

                    IconDisplay {
                        icon: IconSet.ArrowUp;
                        size: 13px;
                        stroke: MyPalette.foreground;
                    }
                }
            }

            Text {
                text: "\{app.size-mib.to-fixed(2)} MiB";
                wrap: no-wrap;
                horizontal-alignment: right;
            }
        }

        Image {
            source: app.icon;
            height: 48px;
        }

        Text {
            text: app.name;
            horizontal-alignment: center;
            wrap: no-wrap;
            overflow: elide;
        }

        HorizontalLayout {
            spacing: 5px;

            IconButton {
                label: "Info";
                icon: IconSet.Info;
                clicked => {
                    UiState.current-homebrew-app = app;
                }
            }

            if !update.is-empty: IconButton {
                width: self.height + 1px;
                icon: IconSet.ArrowUp;
                tooltip: "Update app to \{update}";
                clicked => Dispatcher.dispatch(Message.InstallOscApp, app.osc-app.slug);
            }

            IconButton {
                width: self.height + 1px;
                icon: IconSet.Trash;
                tooltip: "Delete app";
                clicked => {
                    UiState.homebrew-app-to-delete = app;
                }
            }
        }
    }
}
