// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView, Palette } from "std-widgets.slint";
import { DisplayedHomebrewApp } from "../types.slint";
import { IconSet, IconDisplay } from "@lucide";
import { Link } from "link.slint";
import { Card } from "card.slint";
import { HorizontalLine } from "horizontal-line.slint";
import { MyPalette } from "../styling.slint";
import { IconButton, IconButtonKind } from "icon-button.slint";
import { Developers } from "../developers.slint";
import { Modal } from "modal.slint";

export component HomebrewAppInfoModal inherits Modal {
    in property <DisplayedHomebrewApp> app;

    callback closed();

    VerticalLayout {
        alignment: space-between;

        VerticalLayout {
            alignment: space-between;

            VerticalLayout {
                padding: 20px;
                spacing: 10px;

                Text {
                    text: app.name;
                    font-size: 18px;
                    overflow: elide;
                }

                Link {
                    icon: IconSet.Folder;
                    label: "Path: \{app.path}";
                    uri: app.path;
                }
            }

            HorizontalLayout {
                alignment: space-between;
                padding-right: 20px;

                VerticalLayout {
                    spacing: 5px;
                    padding: 20px;
                    alignment: start;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Tag;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Version: \{app.version}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Calendar;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Release date: \{app.release-date}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: Developers.get-icon(app.coder);
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Coder: \{app.coder}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.NotepadText;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Description: \{app.short-description}";
                        }
                    }

                    HorizontalLayout {
                        padding: 5px;
                        HorizontalLine { }
                    }

                    ScrollView {
                        width: 400px;
                        height: 100px;
                        viewport-height: v.preferred-height;

                        v := VerticalLayout {
                            Text {
                                text: app.long-description;
                                wrap: word-wrap;
                            }
                        }
                    }
                }

                Image {
                    source: app.icon;
                    height: 96px;
                }
            }

            VerticalLayout { }
        }

        VerticalLayout {
            height: self.min-height;

            HorizontalLine { }

            HorizontalLayout {
                alignment: space-between;

                VerticalLayout {
                    alignment: center;
                    padding-left: 15px;

                    Link {
                        uri: "https://oscwii.org/library/app/\{app.slug}";
                        label: "Open Shop Channel page";
                    }
                }

                HorizontalLayout {
                    padding: 10px;
                    spacing: 10px;

                    IconButton {
                        label: "Close";
                        kind: IconButtonKind.Primary;
                        clicked => closed();
                    }
                }
            }
        }
    }
}
