// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { HomebrewAppsFilter } from "homebrew-apps-filter.slint";
import { Logic } from "../logic.slint";

export component HomebrewAppsOtherToolbar inherits HorizontalLayout {
    alignment: space-between;
    height: 38px;
    padding-right: 10px;

    HomebrewAppsFilter { }

    Text {
        height: parent.height;
        vertical-alignment: center;
        horizontal-alignment: end;
        text: "\{Logic.homebrew-apps.length} app\{Logic.homebrew-apps.length == 1 ? "" : "s"}   ~ \{Logic.drive-info.apps-mib.to-fixed(2)} MiB";
    }
}
