// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Icon, IconDisplay, IconSet } from "@lucide";
import { HorizontalBox, Palette } from "std-widgets.slint";
import { MyPalette } from "../styling.slint";
import { IconButtonKind } from "../types.slint";
import { Card } from "card.slint";
import { State } from "../state.slint";

export component IconButton inherits Rectangle {
    in property <string> label;
    in property <Icon> icon: IconSet.WifiZero;
    in property <IconButtonKind> kind: IconButtonKind.Secondary;
    in property <string> tooltip;

    callback clicked;

    pure function get-bg() -> brush {
        if kind == IconButtonKind.Primary {
            t.has-hover ? MyPalette.primary-hover : MyPalette.accent-background
        } else if kind == IconButtonKind.Secondary {
            t.has-hover ? MyPalette.secondary-hover : MyPalette.alternate-background
        } else if kind == IconButtonKind.Warning {
            t.has-hover ? MyPalette.warning-hover : MyPalette.warning-background
        } else if kind == IconButtonKind.Danger {
            t.has-hover ? MyPalette.danger-hover : MyPalette.danger-background
        } else {
            transparent
        }
    }

    pure function get-border-color() -> color {
        if kind == IconButtonKind.Secondary {
            MyPalette.border
        } else {
            transparent
        }
    }

    pure function get-border-width() -> length {
        if kind == IconButtonKind.Secondary {
            1px
        } else {
            0px
        }
    }

    pure function get-stroke() -> brush {
        if kind == IconButtonKind.Secondary {
            MyPalette.foreground
        } else {
            MyPalette.accent-foreground
        }
    }

    background: get-bg();
    border-color: get-border-color();
    border-width: get-border-width();
    border-radius: 10px;
    height: self.min-height;

    h := HorizontalLayout {
        padding-top: 8px;
        padding-bottom: 8px;
        padding-left: 9px;
        padding-right: 9px;
        spacing: 3px;

        if icon != IconSet.WifiZero: IconDisplay {
            icon: icon;
            stroke: get-stroke();
            size: 14px;
        }

        if !label.is-empty: Text {
            text: label;
            color: get-stroke();
            horizontal-alignment: center;
        }
    }

    t := TouchArea {
        clicked => {
            State.tooltip.a-text = "";
            clicked();
        }
        width: h.width;
        height: h.height;

        pointer-event(event) => {
            if event.kind == PointerEventKind.move {
                State.tooltip.b-mouse-x = self.absolute-position.x + self.mouse-x;
                State.tooltip.c-mouse-y = self.absolute-position.y + self.mouse-y;
            }
        }

        changed has-hover => {
            if self.has-hover {
                State.tooltip.a-text = tooltip;
                State.tooltip.b-mouse-x = self.absolute-position.x + self.mouse-x;
                State.tooltip.c-mouse-y = self.absolute-position.y + self.mouse-y;
            } else {
                State.tooltip.a-text = "";
            }
        }
    }
}
