// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Icon, IconDisplay, IconSet } from "@lucide";
import { HorizontalBox, Palette } from "std-widgets.slint";
import { IconButtonKind } from "../types.slint";
import { Card } from "card.slint";
import { State } from "../state.slint";

export component IconButton inherits Rectangle {
    in property <string> label;
    in property <Icon> icon: IconSet.WifiZero;
    in property <IconButtonKind> kind: IconButtonKind.Secondary;
    in property <string> tooltip;

    callback clicked;

    pure function get-bg() -> color {
        if kind == IconButtonKind.Primary && !t.has-hover {
            Palette.accent-background
        } else if kind == IconButtonKind.Primary && Palette.color-scheme == ColorScheme.light {
            Palette.accent-background.darker(0.1)
        } else if kind == IconButtonKind.Primary {
            Palette.accent-background.brighter(0.1)
        } else if kind == IconButtonKind.Secondary && !t.has-hover {
            Palette.alternate-background
        } else if kind == IconButtonKind.Secondary && Palette.color-scheme == ColorScheme.light {
            Palette.alternate-background.darker(0.1)
        } else if kind == IconButtonKind.Secondary {
            Palette.alternate-background.brighter(0.1)
        } else if kind == IconButtonKind.Warning && !t.has-hover {
            Colors.yellow
        } else if kind == IconButtonKind.Warning && Palette.color-scheme == ColorScheme.light {
            Colors.yellow.darker(0.1)
        } else if kind == IconButtonKind.Warning {
            Colors.yellow.brighter(0.1)
        } else if kind == IconButtonKind.Danger && !t.has-hover {
            Colors.red
        } else if kind == IconButtonKind.Danger && Palette.color-scheme == ColorScheme.light {
            Colors.red.darker(0.1)
        } else if kind == IconButtonKind.Danger {
            Colors.red.brighter(0.1)
        } else {
            transparent
        }
    }

    pure function get-border-color() -> color {
        if kind == IconButtonKind.Secondary {
            Palette.border
        } else {
            transparent
        }
    }

    pure function get-border-width() -> length {
        if kind == IconButtonKind.Secondary {
            1px
        } else {
            0px
        }
    }

    pure function get-stroke() -> color {
        if kind == IconButtonKind.Secondary {
            Palette.foreground
        } else {
            Palette.accent-foreground
        }
    }

    background: get-bg();
    border-color: get-border-color();
    border-width: get-border-width();
    border-radius: 10px;

    h := HorizontalLayout {
        padding-top: 8px;
        padding-bottom: 8px;
        padding-left: 9px;
        padding-right: 9px;
        spacing: 3px;

        if icon != IconSet.WifiZero: IconDisplay {
            icon: icon;
            stroke: get-stroke();
            size: 14px;
        }

        if !label.is-empty: Text {
            text: label;
            color: get-stroke();
            horizontal-alignment: center;
        }
    }

    t := TouchArea {
        clicked => clicked();
        width: h.width;
        height: h.height;

        pointer-event(event) => {
            if event.kind == PointerEventKind.move {
                State.tooltip.b-mouse-x = self.absolute-position.x + self.mouse-x;
                State.tooltip.c-mouse-y = self.absolute-position.y + self.mouse-y;
            }
        }

        changed has-hover => {
            if self.has-hover {
                State.tooltip = {
                    a-text: tooltip,
                    b-mouse-x: self.absolute-position.x + self.mouse-x,
                    c-mouse-y: self.absolute-position.y + self.mouse-y
                };
            } else {
                State.tooltip = { a-text: "", b-mouse-x: 0, c-mouse-y: 0 };
            }
        }
    }
}
