// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Icon, IconDisplay, IconSet } from "@lucide";
import { Palette } from "std-widgets.slint";
import { MyPalette } from "../styling.slint";
import { IconButtonKind } from "../types.slint";
import { Card } from "card.slint";
import { State } from "../state.slint";
import { TooltipArea } from "tooltip-area.slint";

export component IconButton inherits TooltipArea {
    in property <string> label;
    in property <Icon> icon: IconSet.WifiZero;
    in property <IconButtonKind> kind: IconButtonKind.Secondary;
    in property <bool> rounded: false;
    in property <bool> squared: false;
    in property <length> font-size: 14px;
    pure function get-bg() -> brush {
        if kind == IconButtonKind.Primary {
            self.has-hover ? MyPalette.accent-background.darker(0.2) : MyPalette.accent-background
        } else if kind == IconButtonKind.Destructive {
            self.has-hover ? MyPalette.destructive.darker(0.2) : MyPalette.destructive;
        } else {
            self.has-hover ? MyPalette.background.darker(0.1) : MyPalette.background;
        }
    }

    pure function get-border-color() -> color {
        if kind == IconButtonKind.Secondary && !squared {
            MyPalette.border
        } else {
            transparent
        }
    }

    pure function get-border-width() -> length {
        if kind == IconButtonKind.Secondary && !squared {
            1px
        } else {
            0px
        }
    }

    pure function get-stroke() -> brush {
        if kind == IconButtonKind.Secondary {
            MyPalette.foreground
        } else {
            MyPalette.accent-foreground
        }
    }

    pure function get-font-weight() -> int {
        if kind == IconButtonKind.Secondary {
            400
        } else {
            600
        }
    }

    pure function get-radius() -> length {
        if rounded {
            self.width / 2;
        } else if squared {
            0px
        } else {
            10px
        }
    }

    background: get-bg();
    border-color: get-border-color();
    border-width: get-border-width();
    border-radius: get-radius();
    height: 27px;

    HorizontalLayout {
        alignment: center;
        spacing: 5px;
        padding-left: label.is-empty ? 0px : 10px;
        padding-right: label.is-empty ? 0px : 10px;

        if icon != IconSet.WifiZero: VerticalLayout {
            alignment: center;
            width: font-size;

            IconDisplay {
                icon: icon;
                stroke: get-stroke();
                size: font-size;
            }
        }

        if !label.is-empty: Text {
            text: label;
            color: get-stroke();
            vertical-alignment: center;
            font-weight: get-font-weight();
            font-size: font-size;
        }
    }
}
