// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { MyPalette } from "../styling.slint";

export component MyLineEdit inherits Rectangle {
    in-out property <string> text;
    in property <string> placeholder-text;

    height: t.preferred-height;

    Text {
        x: 0;
        y: 0;
        horizontal-alignment: left;
        visible: t.text.is-empty;
        text: placeholder-text;
        color: MyPalette.foreground.transparentize(0.5);
    }

    t := TextInput {
        x: 0;
        y: 0;
        text <=> text;
    }
}
