// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { MyPalette } from "../styling.slint";

export component MyLineEdit inherits Rectangle {
    in-out property <string> text;
    in property <string> placeholder-text;

    t := TextInput {
        text <=> text;
    }

    Text {
        visible: t.text.is-empty;
        text: placeholder-text;
        color: MyPalette.foreground.transparentize(0.5);
    }
}
