// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconSet } from "@lucide";
import { Page } from "../types.slint";
import { State } from "../state.slint";
import { NavbarButton } from "navbar-button.slint";

export component Navbar inherits VerticalLayout {
    alignment: LayoutAlignment.space-between;

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        NavbarButton {
            active: State.current-page == Page.Games;
            icon: IconSet.Gamepad2;
            tooltip: "Games";
            clicked => {
                State.current-page = Page.Games;
            }
        }

        NavbarButton {
            active: false;
            icon: IconSet.Waves;
            icon2: IconSet.Bubbles;
            tooltip: "Homebrew apps";
            clicked => {
                State.current-page = Page.HbcApps;
            }
        }

        NavbarButton {
            active: false;
            icon: IconSet.Waves;
            icon2: IconSet.ArrowBigDown;
            tooltip: "Open Shop Channel";
        }

        NavbarButton {
            active: false;
            icon: IconSet.ToolCase;
            tooltip: "Tools and utilities";
        }

        NavbarButton {
            active: State.current-page == Page.Settings;
            icon: IconSet.Settings;
            tooltip: "Settings";
            clicked => {
                State.current-page = Page.Settings;
            }
        }
    }

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        NavbarButton {
            icon: IconSet.HardDrive;
            tooltip: "Select a drive";
            clicked => State.pick-mount-point();
        }

        NavbarButton {
            active: State.current-page == Page.About;
            icon: IconSet.Info;
            tooltip: "About TinyWiiBackupManager";
            clicked => {
                State.current-page = Page.About;
            }
        }
    }
}
