// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconSet } from "@lucide";
import { Page, Action } from "../types.slint";
import { NavbarButton } from "navbar-button.slint";
import { Logic } from "../logic.slint";

export component Navbar inherits VerticalLayout {
    in-out property <Page> current-page: Page.Games;

    alignment: LayoutAlignment.space-between;

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        NavbarButton {
            active: current-page == Page.Games;
            icon: IconSet.Gamepad2;
            tooltip: "Games";
            clicked => {
                current-page = Page.Games;
            }
        }

        NavbarButton {
            active: current-page == Page.HomebrewApps;
            icon: IconSet.WavesHorizontal;
            icon2: IconSet.Bubbles;
            tooltip: "Homebrew apps";
            clicked => {
                current-page = Page.HomebrewApps;
            }
        }

        NavbarButton {
            active: current-page == Page.Osc;
            icon: IconSet.WavesHorizontal;
            icon2: IconSet.ArrowBigDown;
            tooltip: "Open Shop Channel";
            clicked => {
                current-page = Page.Osc;
                Logic.dispatch(Action.DownloadOscIcons, "");
            }
        }

        NavbarButton {
            active: current-page == Page.Toolbox;
            icon: IconSet.ToolCase;
            tooltip: "Toolbox";
            clicked => {
                current-page = Page.Toolbox;
            }
        }

        NavbarButton {
            active: current-page == Page.Settings;
            icon: IconSet.Settings;
            tooltip: "Settings";
            clicked => {
                current-page = Page.Settings;
            }
        }
    }

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        if Logic.conversion-queue.length > 0: NavbarButton {
            active: current-page == Page.ConversionQueue;
            icon: IconSet.RefreshCw;
            tooltip: "Conversion queue";
            rotate: true;
            clicked => {
                current-page = Page.ConversionQueue;
            }
        }

        if !Logic.latest-version.is-empty: NavbarButton {
            icon: IconSet.BellPlus;
            tooltip: "New TinyWiiBackupManager version available: \{Logic.latest-version}";
            clicked => Logic.dispatch(Action.OpenThat, "https://github.com/mq1/TinyWiiBackupManager/releases/latest");
        }

        NavbarButton {
            icon: IconSet.HardDrive;
            tooltip: "Select a drive";
            clicked => Logic.dispatch(Action.PickMountPoint, "");
        }

        NavbarButton {
            active: current-page == Page.About;
            icon: IconSet.Info;
            tooltip: "About TinyWiiBackupManager";
            clicked => {
                current-page = Page.About;
            }
        }
    }
}
