// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconSet } from "@lucide";
import { Page, Config } from "../types.slint";
import { NavbarButton } from "navbar-button.slint";
import { Rust } from "../rust.slint";

export component Navbar inherits VerticalLayout {
    in-out property <Page> current-page: Page.Games;
    in-out property <Config> config;

    alignment: LayoutAlignment.space-between;

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        NavbarButton {
            active: current-page == Page.Games;
            icon: IconSet.Gamepad2;
            tooltip: "Games";
            clicked => {
                current-page = Page.Games;
            }
        }

        NavbarButton {
            active: current-page == Page.HomebrewApps;
            icon: IconSet.Waves;
            icon2: IconSet.Bubbles;
            tooltip: "Homebrew apps";
            clicked => {
                current-page = Page.HomebrewApps;
            }
        }

        NavbarButton {
            active: current-page == Page.Osc;
            icon: IconSet.Waves;
            icon2: IconSet.ArrowBigDown;
            tooltip: "Open Shop Channel";
            clicked => {
                current-page = Page.Osc;
            }
        }

        NavbarButton {
            active: false;
            icon: IconSet.ToolCase;
            tooltip: "Tools and utilities";
        }

        NavbarButton {
            active: current-page == Page.Settings;
            icon: IconSet.Settings;
            tooltip: "Settings";
            clicked => {
                current-page = Page.Settings;
            }
        }
    }

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        NavbarButton {
            icon: IconSet.HardDrive;
            tooltip: "Select a drive";
            clicked => {
                config = Rust.pick-mount-point();
                Rust.refresh-all();
            }
        }

        NavbarButton {
            active: current-page == Page.About;
            icon: IconSet.Info;
            tooltip: "About TinyWiiBackupManager";
            clicked => {
                current-page = Page.About;
            }
        }
    }
}
