// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { MyPalette } from "../styling.slint";
import { IconDisplay, Icon, IconSet } from "@lucide";
import { TooltipArea } from "tooltip-area.slint";

export component NavbarButton inherits TooltipArea {
    in property <bool> active: false;
    in property <Icon> icon;
    in property <Icon> icon2: IconSet.WifiZero;

    pure function get-background() -> color {
        if active {
            MyPalette.selection-background
        } else if self.has-hover {
            MyPalette.alternate-background
        } else {
            transparent
        }
    }

    width: 42px;
    height: 42px;
    border-radius: self.width / 2;
    clip: true;
    background: get-background();

    IconDisplay {
        icon: icon;
        stroke: MyPalette.foreground;
    }

    if icon2 != IconSet.WifiZero: IconDisplay {
        icon: icon2;
        stroke: MyPalette.foreground;
        stroke-fill: MyPalette.alternate-background;
    }
}
