// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Palette } from "std-widgets.slint";
import { IconDisplay, Icon } from "@lucide";
import { State } from "../state.slint";

export component NavbarButton inherits Rectangle {
    in property <bool> active: false;
    in property <Icon> icon;
    in property <string> tooltip;

    callback clicked;

    pure function get-background() -> color {
        if active {
            Palette.selection-background
        } else if ta.has-hover {
            Palette.alternate-background
        } else {
            transparent
        }
    }

    width: 40px;
    height: 40px;
    border-radius: self.width / 2;
    clip: true;
    background: get-background();

    IconDisplay {
        icon: icon;
        stroke: Palette.foreground;
    }

    ta := TouchArea {
        clicked => clicked();

        pointer-event(event) => {
            if event.kind == PointerEventKind.move {
                State.tooltip.b-mouse-x = self.absolute-position.x + self.mouse-x;
                State.tooltip.c-mouse-y = self.absolute-position.y + self.mouse-y;
            }
        }

        changed has-hover => {
            if self.has-hover {
                State.tooltip.a-text = tooltip;
                State.tooltip.b-mouse-x = self.absolute-position.x + self.mouse-x;
                State.tooltip.c-mouse-y = self.absolute-position.y + self.mouse-y;
            } else {
                State.tooltip.a-text = "";
            }
        }
    }
}
