// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { State } from "../state.slint";
import { Card } from "card.slint";
import { IconButton } from "icon-button.slint";
import { IconSet } from "@lucide";
import { Rust } from "../rust.slint";

export component Notifications inherits VerticalBox {
    width: self.preferred-width;
    height: self.preferred-height;

    for notification[i] in State.notifications: Card {
        width: h.preferred-width + 10px;

        h := HorizontalLayout {
            padding: 5px;

            IconButton {
                icon: IconSet.X;
                clicked => Rust.close-notification(i);
                rounded: true;
                width: 20px;
                height: 20px;
            }

            Text {
                text: "  " + notification.text;
                vertical-alignment: center;
            }
        }
    }
}
