// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { State } from "../state.slint";
import { Card } from "card.slint";
import { IconButton } from "icon-button.slint";
import { IconSet, IconDisplay } from "@lucide";
import { MyPalette } from "../styling.slint";

export component Notifications inherits VerticalBox {
    width: self.preferred-width;
    height: self.preferred-height;

    for notification[i] in State.notifications: Card {
        width: h.preferred-width + 10px;

        h := HorizontalLayout {
            padding: 5px;
            spacing: 10px;

            VerticalLayout {
                alignment: center;
                width: 14px;
                padding-left: 5px;
                padding-right: 10px;

                IconDisplay {
                    icon: notification.critical ? IconSet.TriangleAlert : IconSet.Info;
                    size: 14px;
                    stroke: MyPalette.foreground;
                }
            }

            Text {
                text: notification.text;
                vertical-alignment: center;
            }

            IconButton {
                icon: IconSet.X;
                clicked => State.close-notification(i);
                rounded: true;
                width: 20px;
                height: 20px;
            }
        }
    }
}
