// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { State } from "../state.slint";
import { Card } from "card.slint";
import { IconButton } from "icon-button.slint";
import { IconSet, IconDisplay } from "@lucide";
import { MyPalette } from "../styling.slint";

export component Notifications inherits VerticalLayout {
    width: self.preferred-width;
    height: self.preferred-height;
    padding: 10px;
    spacing: 5px;

    for notification[i] in State.notifications: Card {
        height: 40px;

        h := HorizontalLayout {
            spacing: 10px;
            padding-left: 10px;
            padding-right: 10px;

            VerticalLayout {
                alignment: center;
                width: 14px;

                IconDisplay {
                    icon: notification.critical ? IconSet.TriangleAlert : IconSet.Info;
                    size: 14px;
                    stroke: MyPalette.foreground;
                }
            }

            Text {
                text: notification.text;
                vertical-alignment: center;
            }

            VerticalLayout {
                alignment: center;

                IconButton {
                    icon: IconSet.X;
                    clicked => State.close-notification(i);
                    rounded: true;
                    height: 24px;
                    width: 24px;
                }
            }
        }
    }
}
