// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { DisplayedOscApp } from "../types.slint";
import { IconButton } from "icon-button.slint";
import { IconSet, IconDisplay } from "@lucide";
import { MyPalette } from "../styling.slint";
import { Logic } from "../logic.slint";

export component OscAppCard inherits Card {
    in property <DisplayedOscApp> app;

    callback open-info();
    callback install();
    callback wiiload();

    width: 172px;
    height: self.min-height;

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        HorizontalLayout {
            alignment: space-between;

            HorizontalLayout {
                spacing: 5px;

                IconDisplay {
                    icon: IconSet.Tag;
                    size: 13px;
                    stroke: MyPalette.foreground;
                }

                Text {
                    text: app.version;
                    wrap: no-wrap;
                    overflow: elide;
                }
            }

            Text {
                text: "\{app.uncompressed-size-mib.to-fixed(2)} MiB";
                wrap: no-wrap;
                horizontal-alignment: right;
            }
        }

        Image {
            source: app.icon;
            height: 48px;
        }

        Text {
            text: app.name;
            horizontal-alignment: center;
            wrap: no-wrap;
            overflow: elide;
        }

        HorizontalLayout {
            spacing: 5px;

            IconButton {
                label: "Info";
                icon: IconSet.Info;
                clicked => open-info();
            }

            IconButton {
                width: self.height + 1px;
                icon: IconSet.HardDriveDownload;
                tooltip: "Install";
                disabled: Logic.config.mount-point.is-empty;
                clicked => install();
            }

            IconButton {
                width: self.height + 1px;
                icon: IconSet.MonitorUp;
                tooltip: "Wiiload";
                clicked => wiiload();
            }
        }
    }
}
