// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { OscFilter } from "osc-filter.slint";
import { Logic } from "../logic.slint";
import { Link } from "link.slint";

export component OscOtherToolbar inherits HorizontalLayout {
    alignment: space-between;
    height: 38px;
    padding-right: 10px;

    OscFilter { }

    VerticalLayout {
        height: parent.height;
        alignment: center;

        HorizontalLayout {
            spacing: 20px;

            Text {
                text: "refreshed \{Logic.osc-refreshed-x-hours-ago}h \{Logic.osc-refreshed-x-minutes-ago}m ago";
            }

            Link {
                uri: "https://oscwii.org/";
                label: "oscwii.org";
            }
        }
    }
}
