// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView, Palette } from "std-widgets.slint";
import { OscApp } from "../types.slint";
import { IconSet, IconDisplay } from "@lucide";
import { Link } from "link.slint";
import { Card } from "card.slint";
import { HorizontalLine } from "horizontal-line.slint";
import { MyPalette } from "../styling.slint";
import { IconButton, IconButtonKind } from "icon-button.slint";
import { Developers } from "../developers.slint";
import { Modal } from "modal.slint";

export component OscAppInfoModal inherits Modal {
    in property <OscApp> app;

    callback closed();

    VerticalLayout {
        alignment: space-between;

        VerticalLayout {
            alignment: space-between;

            VerticalLayout {
                padding: 20px;
                spacing: 10px;

                Text {
                    text: app.meta.name;
                    font-size: 18px;
                    overflow: elide;
                }

                Link {
                    label: "https://oscwii.org/library/app/\{app.meta.slug}";
                    uri: "https://oscwii.org/library/app/\{app.meta.slug}";
                }
            }

            HorizontalLayout {
                alignment: space-between;
                padding-right: 20px;

                VerticalLayout {
                    spacing: 5px;
                    padding: 20px;
                    alignment: start;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Tag;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Version: \{app.meta.version}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Calendar;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Release date: \{app.release-date}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: Developers.get-icon(app.meta.author);
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Author: \{app.meta.author}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.NotepadText;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Description: \{app.meta.description.short}";
                        }
                    }

                    HorizontalLayout {
                        padding: 5px;
                        HorizontalLine { }
                    }

                    ScrollView {
                        width: 400px;
                        height: 100px;
                        viewport-height: v.preferred-height;

                        v := VerticalLayout {
                            Text {
                                text: app.meta.description.long;
                                wrap: word-wrap;
                            }
                        }
                    }
                }

                Image {
                    source: app.icon;
                    height: 96px;
                }
            }

            VerticalLayout { }
        }

        VerticalLayout {
            height: self.min-height;

            HorizontalLine { }

            HorizontalLayout {
                alignment: end;
                padding: 10px;
                spacing: 10px;

                IconButton {
                    label: "Close";
                    kind: IconButtonKind.Primary;
                    clicked => closed();
                }
            }
        }
    }
}
