// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconSet, IconDisplay } from "@lucide";
import { VerticalLine } from "vertical-line.slint";
import { IconButton } from "icon-button.slint";
import { DisplayedOscApp } from "../types.slint";
import { MyPalette } from "../styling.slint";

export component OscAppRow inherits Rectangle {
    in property <DisplayedOscApp> app;

    callback open-info();
    callback install();

    height: 24px;

    Text {
        x: 5px;
        y: 5px;
        text: "\{app.name} (\{app.version})";
        overflow: elide;
    }

    Text {
        x: parent.width - 50px - self.preferred-width - 5px;
        y: 5px;
        text: "\{app.uncompressed-size-mib.to-fixed(2)} MiB";
    }

    VerticalLine {
        x: parent.width - 75px;
        y: 0px;
        height: 24px;
    }

    IconButton {
        x: parent.width - 74px;
        y: 0px;
        tooltip: "App info";
        icon: IconSet.Info;
        height: 24px;
        width: 24px;
        squared: true;
        clicked => open-info();
    }

    VerticalLine {
        x: parent.width - 50px;
        y: 0px;
        height: 24px;
    }

    IconButton {
        x: parent.width - 49px;
        y: 0px;
        tooltip: "Install";
        icon: IconSet.HardDriveDownload;
        height: 24px;
        width: 24px;
        squared: true;
        clicked => install();
    }

    VerticalLine {
        x: parent.width - 25px;
        y: 0px;
        height: 24px;
    }

    IconButton {
        x: parent.width - 24px;
        y: 0px;
        icon: IconSet.MonitorUp;
        tooltip: "Wiiload";
        height: 24px;
        width: 24px;
        squared: true;
    }
}
