// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconButton, IconButtonKind } from "icon-button.slint";
import { Config } from "../types.slint";
import { IconSet, IconDisplay } from "@lucide";
import { ViewAs } from "view-as.slint";
import { MyPalette } from "../styling.slint";
import { Link } from "link.slint";
import { Rust } from "../rust.slint";

export component OscToolbar inherits HorizontalLayout {
    in property <Config> config;

    alignment: space-between;
    height: 38px;

    HorizontalLayout {
        padding-top: 10px;
        spacing: 5px;

        IconDisplay {
            icon: IconSet.ChevronRight;
            size: 18px;
            stroke: MyPalette.foreground;
        }

        Text {
            text: "Open Shop Channel";
            font-size: 18px;
        }

        VerticalLayout {
            alignment: center;
            height: 18px;
            padding-left: 20px;

            Link {
                uri: "https://oscwii.org/";
                label: "oscwii.org";
            }
        }
    }

    HorizontalLayout {
        spacing: 10px;

        ViewAs {
            config: config;
        }

        VerticalLayout {
            alignment: center;

            IconButton {
                icon: IconSet.RotateCw;
                tooltip: "Force refresh (automatic refreshes are performed every 24 hours)";
                rounded: true;
                kind: IconButtonKind.Primary;
                font-size: 18px;
                width: 34px;
                height: 34px;
                clicked => Rust.force-osc-refresh();
            }
        }
    }
}
