// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { OscAppMeta } from "../types.slint";
import { IconButton } from "icon-button.slint";
import { IconSet, IconDisplay } from "@lucide";
import { State } from "../state.slint";
import { MyPalette } from "../styling.slint";

export component OscAppCard inherits Card {
    in property <OscAppMeta> app;
    in property <image> icon;

    width: 172px;
    height: self.min-height;

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        HorizontalLayout {
            alignment: space-between;

            HorizontalLayout {
                spacing: 5px;

                IconDisplay {
                    icon: IconSet.Tag;
                    size: 13px;
                    stroke: MyPalette.foreground;
                }

                Text {
                    text: app.version;
                    wrap: no-wrap;
                    overflow: elide;
                }
            }

            Text {
                text: "\{(app.uncompressed-size / 1024.0 / 1024.0).to-fixed(2)} MiB";
                wrap: no-wrap;
                horizontal-alignment: right;
            }
        }

        Image {
            source: icon;
            height: 48px;
        }

        Text {
            text: app.name;
            horizontal-alignment: center;
            wrap: no-wrap;
            overflow: elide;
        }

        HorizontalLayout {
            spacing: 5px;

            IconButton {
                label: "Info";
                icon: IconSet.Info;
            }

            IconButton {
                icon: IconSet.MonitorUp;
                tooltip: "Wiiload";
            }
        }
    }
}
