// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconButton } from "icon-button.slint";
import { IconButtonKind } from "../types.slint";
import { IconSet, IconDisplay } from "@lucide";
import { State } from "../state.slint";
import { ViewAs } from "view-as.slint";
import { MyPalette } from "../styling.slint";
import { Link } from "link.slint";

export component OscToolbar inherits HorizontalLayout {
    alignment: space-between;
    height: 38px;

    HorizontalLayout {
        padding-top: 10px;
        spacing: 5px;

        IconDisplay {
            icon: IconSet.ChevronRight;
            size: 18px;
            stroke: MyPalette.foreground;
        }

        Text {
            text: "Open Shop Channel";
            font-size: 18px;
        }

        VerticalLayout {
            alignment: center;
            height: 18px;
            padding-left: 20px;

            Link {
                uri: "https://oscwii.org/";
                label: "oscwii.org";
            }
        }
    }

    HorizontalLayout {
        spacing: 10px;

        ViewAs { }
    }
}
