// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { OscFilter } from "osc-filter.slint";
import { Logic } from "../logic.slint";

export component OscOtherToolbar inherits HorizontalLayout {
    alignment: space-between;
    height: 38px;
    padding-right: 10px;

    OscFilter { }

    Text {
        height: parent.height;
        vertical-alignment: center;
        horizontal-alignment: end;
        text: "refreshed \{Logic.osc-refreshed-x-hours-ago} hours and \{Logic.osc-refreshed-x-minutes-ago} minutes ago";
    }
}
