// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { MyPalette } from "../styling.slint";
import { Icon, IconDisplay, IconSet } from "@lucide";
import { HorizontalLine } from "horizontal-line.slint";
import { Card } from "card.slint";
import { UiState } from "../ui-state.slint";
import { Message, Dispatcher } from "../messages.slint";

export component SettingCard inherits Card {
    in property <string> label;
    in property <Icon> icon;
    in property <[{ value: string, label: string}]> items;
    in property <string> active-item;
    in property <Message> set-property;

    callback changed();

    width: 100%;

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        HorizontalLayout {
            spacing: 5px;

            IconDisplay {
                icon: icon;
                stroke: MyPalette.foreground;
                size: 14px;
            }

            Text {
                text: label;
            }
        }

        HorizontalLine { }

        for item in items: Rectangle {
            HorizontalLayout {
                spacing: 5px;

                IconDisplay {
                    icon: item.value == active-item ? IconSet.Disc : IconSet.Circle;
                    stroke: item.value == active-item ? MyPalette.accent-background : MyPalette.foreground;
                    size: 14px;
                }

                Text {
                    text: item.label;
                }
            }

            TouchArea {
                clicked => {
                    if item.value != active-item {
                        Dispatcher.dispatch(set-property, item.value);
                        changed();
                    }
                }
            }
        }
    }
}
