// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { VerticalBox } from "std-widgets.slint";
import { MyPalette } from "../styling.slint";
import { Icon, IconDisplay, IconSet } from "@lucide";
import { HorizontalLine } from "horizontal-line.slint";
import { Card } from "card.slint";
import { State } from "../state.slint";

export component Setting inherits Card {
    in property <string> label;
    in property <Icon> icon;
    in property <[{value: string, label: string}]> items;
    in-out property <string> active-value;

    width: 100%;

    VerticalBox {
        height: 100%;

        HorizontalLayout {
            IconDisplay {
                icon: icon;
                stroke: MyPalette.foreground;
                size: 14px;
            }

            Text {
                text: " " + label;
            }
        }

        HorizontalLine { }

        for item in items: Rectangle {
            HorizontalLayout {
                IconDisplay {
                    icon: item.value == active-value ? IconSet.Disc : IconSet.Circle;
                    stroke: item.value == active-value ? MyPalette.accent-background : MyPalette.foreground;
                    size: 14px;
                }

                Text {
                    text: " " + item.label;
                }
            }

            TouchArea {
                clicked => {
                    active-value = item.value;
                    State.write-config();
                }
            }
        }
    }
}
