// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { MyPalette } from "../styling.slint";
import { Icon, IconDisplay, IconSet } from "@lucide";
import { HorizontalLine } from "horizontal-line.slint";
import { Card } from "card.slint";
import { State } from "../state.slint";

export component SettingCard inherits Card {
    in property <string> label;
    in property <Icon> icon;
    in property <[string]> items;
    in property <int> active-item;

    callback selected(int);

    width: 100%;

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        HorizontalLayout {
            spacing: 5px;

            IconDisplay {
                icon: icon;
                stroke: MyPalette.foreground;
                size: 14px;
            }

            Text {
                text: label;
            }
        }

        HorizontalLine { }

        for item[i] in items: Rectangle {
            HorizontalLayout {
                spacing: 5px;

                IconDisplay {
                    icon: i == active-item ? IconSet.Disc : IconSet.Circle;
                    stroke: i == active-item ? MyPalette.accent-background : MyPalette.foreground;
                    size: 14px;
                }

                Text {
                    text: item;
                }
            }

            TouchArea {
                clicked => selected(i);
            }
        }
    }
}
