// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { CheckBox } from "std-widgets.slint";
import { TooltipArea } from "tooltip-area.slint";
import { VerticalLine } from "vertical-line.slint";
import { IconDisplay, IconSet } from "@lucide";
import { Logic } from "../logic.slint";

export component ShowWiiGc inherits Card {
    height: 38px;

    HorizontalLayout {
        padding-left: 10px;
        padding-right: 8px;
        spacing: 5px;

        CheckBox {
            checked: Logic.config.show-wii;
            toggled => Logic.set-show-wii(self.checked);
        }

        TooltipArea {
            tooltip: "Show Wii";
            width: wii.preferred-width;

            wii := Text {
                height: 38px;
                vertical-alignment: center;
                text: "Wii";
            }
        }

        VerticalLine { }

        CheckBox {
            checked: Logic.config.show-gc;
            toggled => Logic.set-show-gc(self.checked);
        }

        TooltipArea {
            tooltip: "Show GameCube";
            width: gc.preferred-width;

            gc := Text {
                height: 38px;
                vertical-alignment: center;
                text: "GC";
            }
        }
    }
}
