// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { HorizontalBox, CheckBox } from "std-widgets.slint";
import { TooltipArea } from "tooltip-area.slint";
import { VerticalLine } from "vertical-line.slint";
import { IconDisplay, IconSet } from "@lucide";
import { State } from "../state.slint";
import { MyPalette } from "../styling.slint";

export component ShowWiiGc inherits Card {
    height: 38px;
    width: 100px;

    CheckBox {
        x: 10px;
        y: parent.height / 2 - self.height / 2;

        checked <=> State.config.contents.show-wii;
        changed checked => {
            State.write-config();
        }
    }

    TooltipArea {
        x: 30px;
        y: 0;

        tooltip: "Show Wii";
        width: 14px;

        IconDisplay {
            icon: IconSet.Pointer;
            size: 14px;
            stroke: MyPalette.foreground;
        }
    }

    VerticalLine {
        x: 49px;
        y: 0;
    }

    CheckBox {
        x: 58px;
        y: parent.height / 2 - self.height / 2;

        checked <=> State.config.contents.show-gc;
        changed checked => {
            State.write-config();
        }
    }

    TooltipArea {
        x: 78px;
        y: 0;

        tooltip: "Show GameCube";
        width: 14px;

        IconDisplay {
            icon: IconSet.Box;
            size: 14px;
            stroke: MyPalette.foreground;
        }
    }
}
