// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { CheckBox } from "std-widgets.slint";
import { TooltipArea } from "tooltip-area.slint";
import { VerticalLine } from "vertical-line.slint";
import { IconDisplay, IconSet } from "@lucide";
import { State } from "../state.slint";
import { MyPalette } from "../styling.slint";

export component ShowWiiGc inherits Card {
    height: 38px;

    HorizontalLayout {
        padding-left: 10px;
        padding-right: 8px;
        spacing: 5px;

        CheckBox {
            checked: State.config.contents.show-wii;
            toggled => {
                State.config.contents.show-wii = self.checked;
                State.write-config();
            }
        }

        TooltipArea {
            tooltip: "Show Wii";
            width: wii.preferred-width;

            wii := Text {
                height: 38px;
                vertical-alignment: center;
                text: "Wii";
            }
        }

        VerticalLine { }

        CheckBox {
            checked: State.config.contents.show-gc;
            toggled => {
                State.config.contents.show-gc = self.checked;
                State.write-config();
            }
        }

        TooltipArea {
            tooltip: "Show GameCube";
            width: gc.preferred-width;

            gc := Text {
                height: 38px;
                vertical-alignment: center;
                text: "GC";
            }
        }
    }
}
