// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { IconDisplay, IconSet } from "@lucide";
import { TooltipArea } from "tooltip-area.slint";
import { MyPalette } from "../styling.slint";
import { Logic } from "../logic.slint";

export component SortGamesAndHomebrewApps inherits Card {
    pure function get-bg(current-sort-by: bool, hovered: bool) -> color {
        if current-sort-by {
            MyPalette.selection-background
        } else if hovered {
            MyPalette.alternate-background
        } else {
            transparent
        }
    }

    height: 38px;
    clip: true;
    border-radius: 10px;

    HorizontalLayout {
        TooltipArea {
            width: 24px;
            height: 38px;

            tooltip: "Sort by name";
            background: get-bg(Logic.config.sort-by < 2, self.has-hover);
            clicked => {
                if Logic.config.sort-by == 0 {
                    Logic.set-sort-by(1);
                } else {
                    Logic.set-sort-by(0);
                }
            }

            IconDisplay {
                icon: Logic.config.sort-by == 1 ? IconSet.ArrowUpAZ : IconSet.ArrowDownAZ;
                size: 14px;
                stroke: MyPalette.foreground;
            }
        }

        TooltipArea {
            width: 24px;
            height: 38px;

            tooltip: "Sort by size";
            background: get-bg(Logic.config.sort-by >= 2, self.has-hover);
            clicked => {
                if Logic.config.sort-by == 2 {
                    Logic.set-sort-by(3);
                } else {
                    Logic.set-sort-by(2);
                }
            }

            IconDisplay {
                icon: Logic.config.sort-by == 3 ? IconSet.ArrowUp01 : IconSet.ArrowDown01;
                size: 14px;
                stroke: MyPalette.foreground;
            }
        }
    }
}
