// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { IconDisplay, IconSet } from "@lucide";
import { TooltipArea } from "tooltip-area.slint";
import { MyPalette } from "../styling.slint";
import { UiState } from "../ui-state.slint";
import { Message, Dispatcher } from "../messages.slint";

export component SortGamesAndHomebrewApps inherits Card {
    pure function get-bg(current-sort-by: bool, hovered: bool) -> color {
        if current-sort-by {
            MyPalette.selection-background
        } else if hovered {
            MyPalette.alternate-background
        } else {
            transparent
        }
    }

    height: 38px;
    clip: true;
    border-radius: 10px;

    HorizontalLayout {
        TooltipArea {
            width: 24px;
            height: 38px;

            tooltip: "Sort by name";
            background: get-bg(UiState.config.sort-by == "NameDescending" || UiState.config.sort-by == "NameAscending", self.has-hover);
            clicked => {
                if UiState.config.sort-by == "NameDescending" {
                    Dispatcher.dispatch(Message.SetSortBy, "NameAscending");
                } else {
                    Dispatcher.dispatch(Message.SetSortBy, "NameDescending");
                }
            }

            IconDisplay {
                icon: UiState.config.sort-by == "NameAscending" ? IconSet.ArrowUpAZ : IconSet.ArrowDownAZ;
                size: 14px;
                stroke: MyPalette.foreground;
            }
        }

        TooltipArea {
            width: 24px;
            height: 38px;

            tooltip: "Sort by size";
            background: get-bg(UiState.config.sort-by == "SizeDescending" || UiState.config.sort-by == "SizeAscending", self.has-hover);
            clicked => {
                if UiState.config.sort-by == "SizeDescending" {
                    Dispatcher.dispatch(Message.SetSortBy, "SizeAscending");
                } else {
                    Dispatcher.dispatch(Message.SetSortBy, "SizeDescending");
                }
            }

            IconDisplay {
                icon: UiState.config.sort-by == "SizeAscending" ? IconSet.ArrowUp01 : IconSet.ArrowDown01;
                size: 14px;
                stroke: MyPalette.foreground;
            }
        }
    }
}
