// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { IconDisplay, IconSet } from "@lucide";
import { TooltipArea } from "tooltip-area.slint";
import { State } from "../state.slint";
import { MyPalette } from "../styling.slint";
import { SortBy } from "../types.slint";

export component SortGamesAndHbcApps inherits Card {
    pure function get-bg(current-sort-by: bool, hovered: bool) -> color {
        if current-sort-by {
            MyPalette.selection-background
        } else if hovered {
            MyPalette.background
        } else {
            transparent
        }
    }

    height: 38px;
    clip: true;
    border-radius: 10px;

    HorizontalLayout {
        TooltipArea {
            width: 24px;
            height: 38px;

            tooltip: "Sort by name";
            background: get-bg(State.config.contents.sort-by == SortBy.NameAscending || State.config.contents.sort-by == SortBy.NameDescending, self.has-hover);
            clicked => {
                if State.config.contents.sort-by == SortBy.NameAscending {
                    State.config.contents.sort-by = SortBy.NameDescending;
                } else {
                    State.config.contents.sort-by = SortBy.NameAscending;
                }

                State.apply-sorting();
            }

            IconDisplay {
                icon: State.config.contents.sort-by == SortBy.NameDescending ? IconSet.ArrowUpAZ : IconSet.ArrowDownAZ;
                size: 14px;
                stroke: MyPalette.foreground;
            }
        }

        TooltipArea {
            width: 24px;
            height: 38px;

            tooltip: "Sort by size";
            background: get-bg(State.config.contents.sort-by == SortBy.SizeAscending || State.config.contents.sort-by == SortBy.SizeDescending, self.has-hover);
            clicked => {
                if State.config.contents.sort-by == SortBy.SizeAscending {
                    State.config.contents.sort-by = SortBy.SizeDescending;
                } else {
                    State.config.contents.sort-by = SortBy.SizeAscending;
                }

                State.apply-sorting();
            }

            IconDisplay {
                icon: State.config.contents.sort-by == SortBy.SizeDescending ? IconSet.ArrowUp01 : IconSet.ArrowDown01;
                size: 14px;
                stroke: MyPalette.foreground;
            }
        }
    }
}
