// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { HorizontalBox } from "std-widgets.slint";
import { IconDisplay, IconSet } from "@lucide";
import { TooltipArea } from "tooltip-area.slint";
import { State } from "../state.slint";
import { MyPalette } from "../styling.slint";

export component SortGames inherits Card {
    pure function get-bg(sort-by: string, hovered: bool) -> color {
        if State.config.contents.sort-by == sort-by {
            MyPalette.selection-background
        } else if hovered {
            MyPalette.alternate-background
        } else {
            transparent
        }
    }

    HorizontalLayout {
        Rectangle {
            width: 80px;
            height: 38px;
            clip: true;
            border-radius: 10px;

            TooltipArea {
                x: 0;
                y: 0;
                width: 20px;
                height: 38px;

                tooltip: "Sort by name (A→Z)";
                background: get-bg("name_ascending", self.has-hover);
                clicked => {
                    State.config.contents.sort-by = "name_ascending";
                }

                IconDisplay {
                    icon: IconSet.ArrowDownAZ;
                    size: 14px;
                    stroke: MyPalette.foreground;
                }
            }

            TooltipArea {
                x: 20px;
                y: 0;
                width: 20px;
                height: 38px;

                tooltip: "Sort by name (Z→A)";
                background: get-bg("name_descending", self.has-hover);
                clicked => {
                    State.config.contents.sort-by = "name_descending";
                }

                IconDisplay {
                    icon: IconSet.ArrowDownZA;
                    size: 14px;
                    stroke: MyPalette.foreground;
                }
            }

            TooltipArea {
                x: 40px;
                y: 0;
                width: 20px;
                height: 38px;

                tooltip: "Sort by size (small→large)";
                background: get-bg("size_ascending", self.has-hover);
                clicked => {
                    State.config.contents.sort-by = "size_ascending";
                }

                IconDisplay {
                    icon: IconSet.ArrowDown01;
                    size: 14px;
                    stroke: MyPalette.foreground;
                }
            }

            TooltipArea {
                x: 60px;
                y: 0;
                width: 20px;
                height: 38px;

                tooltip: "Sort by size (large→small)";
                background: get-bg("size_descending", self.has-hover);
                clicked => {
                    State.config.contents.sort-by = "size_descending";
                }

                IconDisplay {
                    icon: IconSet.ArrowDown10;
                    size: 14px;
                    stroke: MyPalette.foreground;
                }
            }
        }
    }
}
