// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { State } from "../state.slint";

export component TooltipArea inherits Rectangle {
    in property <string> tooltip;
    out property <bool> has-hover: t.has-hover;

    callback clicked;

    r := Rectangle {
        @children
    }

    t := TouchArea {
        width: r.width;
        height: r.height;

        clicked => {
            State.tooltip.text = "";
            clicked();
        }

        pointer-event(event) => {
            if event.kind == PointerEventKind.move {
                State.tooltip.mouse-x = self.absolute-position.x + self.mouse-x;
                State.tooltip.mouse-y = self.absolute-position.y + self.mouse-y;
            }
        }

        changed has-hover => {
            if self.has-hover {
                State.tooltip.text = tooltip;
                State.tooltip.mouse-x = self.absolute-position.x + self.mouse-x;
                State.tooltip.mouse-y = self.absolute-position.y + self.mouse-y;
            } else {
                State.tooltip.text = "";
            }
        }
    }
}
