// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Tooltip } from "../tooltip.slint";
import { MyPalette } from "../styling.slint";

export component TooltipArea inherits Rectangle {
    in property <string> tooltip;
    out property <bool> has-hover: t.has-hover;
    in property <bool> disabled: false;

    callback clicked;

    r := Rectangle {
        @children
    }

    if disabled: Rectangle {
        x: 0;
        y: 0;
        width: r.width;
        height: r.height;
        background: MyPalette.background.transparentize(0.4);
    }

    t := TouchArea {
        width: r.width;
        height: r.height;

        mouse-cursor: disabled ? MouseCursor.not-allowed : MouseCursor.default;

        clicked => {
            Tooltip.text = "";

            if !disabled {
                clicked();
            }
        }

        pointer-event(event) => {
            if event.kind == PointerEventKind.move {
                Tooltip.mouse-x = self.absolute-position.x + self.mouse-x;
                Tooltip.mouse-y = self.absolute-position.y + self.mouse-y;
            }
        }

        changed has-hover => {
            if self.has-hover {
                Tooltip.text = tooltip;
                Tooltip.mouse-x = self.absolute-position.x + self.mouse-x;
                Tooltip.mouse-y = self.absolute-position.y + self.mouse-y;
            } else {
                Tooltip.text = "";
            }
        }
    }
}
