// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { TooltipArea } from "tooltip-area.slint";
import { IconSet, IconDisplay } from "@lucide";
import { MyPalette } from "../styling.slint";
import { ViewAs } from "../types.slint";
import { Config } from "../types.slint";
import { Rust } from "../rust.slint";

export component ViewAs inherits Card {
    in property <Config> config;

    pure function get-bg(view-as: ViewAs, hovered: bool) -> color {
        if config.contents.view-as == view-as {
            MyPalette.selection-background
        } else if hovered {
            MyPalette.alternate-background
        } else {
            transparent
        }
    }

    height: 38px;
    clip: true;
    border-radius: 10px;

    HorizontalLayout {
        TooltipArea {
            width: 25px;
            height: 38px;

            tooltip: "View as grid";
            background: get-bg(ViewAs.Grid, self.has-hover);
            clicked => {
                config.contents.view-as = ViewAs.Grid;
                Rust.set-config(config);
            }

            IconDisplay {
                icon: IconSet.LayoutGrid;
                size: 14px;
                stroke: MyPalette.foreground;
            }
        }

        TooltipArea {
            width: 25px;
            height: 38px;

            tooltip: "View as table";
            background: get-bg(ViewAs.Table, self.has-hover);
            clicked => {
                config.contents.view-as = ViewAs.Table;
                Rust.set-config(config);
            }

            IconDisplay {
                icon: IconSet.Table;
                size: 14px;
                stroke: MyPalette.foreground;
            }
        }
    }
}
