// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { TooltipArea } from "tooltip-area.slint";
import { IconSet, IconDisplay } from "@lucide";
import { MyPalette } from "../styling.slint";
import { Logic } from "../logic.slint";
import { Action } from "../types.slint";

export component ViewAs inherits Card {
    pure function get-bg(current: bool, hovered: bool) -> color {
        if current {
            MyPalette.selection-background
        } else if hovered {
            MyPalette.alternate-background
        } else {
            transparent
        }
    }

    height: 38px;
    clip: true;
    border-radius: 10px;

    HorizontalLayout {
        TooltipArea {
            width: 25px;
            height: 38px;

            tooltip: "View as grid";
            background: get-bg(Logic.config.view-as == "Grid", self.has-hover);
            clicked => Logic.dispatch(Action.SetViewAs, "Grid");

            IconDisplay {
                icon: IconSet.LayoutGrid;
                size: 14px;
                stroke: MyPalette.foreground;
            }
        }

        TooltipArea {
            width: 25px;
            height: 38px;

            tooltip: "View as table";
            background: get-bg(Logic.config.view-as == "Table", self.has-hover);
            clicked => Logic.dispatch(Action.SetViewAs, "Table");

            IconDisplay {
                icon: IconSet.Table;
                size: 14px;
                stroke: MyPalette.foreground;
            }
        }
    }
}
