// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Modal } from "modal.slint";
import { HorizontalLine } from "horizontal-line.slint";
import { IconButton, IconButtonKind } from "icon-button.slint";
import { IconSet } from "@lucide";
import { UiState } from "../ui-state.slint";
import { DisplayedOscApp } from "../types.slint";
import { LineEdit } from "std-widgets.slint";
import { Message, Dispatcher } from "../messages.slint";

export component WiiloadOscAppModal inherits Modal {
    w: 300px;
    h: 150px;

    VerticalLayout {
        VerticalLayout {
            padding-left: 20px;
            padding-right: 20px;
            spacing: 10px;
            alignment: center;

            Text {
                text: "Sending \{UiState.wiiloading-osc-app.name} via Wiiload";
            }

            HorizontalLayout {
                spacing: 10px;

                VerticalLayout {
                    alignment: center;

                    Text {
                        text: "Wii IP:";
                    }
                }

                ip := LineEdit {
                    text: UiState.config.wii-ip;
                }
            }
        }

        VerticalLayout {
            height: self.min-height;

            HorizontalLine { }

            HorizontalLayout {
                alignment: end;
                padding: 10px;
                spacing: 10px;

                IconButton {
                    label: "Cancel";
                    clicked => {
                        UiState.wiiloading-osc-app = { };
                    }
                }

                IconButton {
                    label: "Send";
                    kind: IconButtonKind.Primary;
                    icon: IconSet.MonitorUp;
                    clicked => {
                        Dispatcher.dispatch(Message.WiiloadOscApp, "\{ip.text} \{UiState.wiiloading-osc-app.slug}");
                        UiState.wiiloading-osc-app = { };
                    }
                }
            }
        }
    }
}
