[package]
name = "TinyWiiBackupManager"
version = "6.1.0"
edition = "2024"
rust-version = "1.98"
authors = ["Manuel Quarneti <mq1@ik.me>"]
license = "GPL-3.0-only"
repository = "https://github.com/mq1/TinyWiiBackupManager"
description = "A tiny game backup and homebrew app manager for the Wii"

[features]
default = ["native-https"]
native-https = ["ureq/native-tls"]
static-https = ["ureq/rustls", "ureq/platform-verifier"]

[dependencies]
iced = { version = "0.14", default-features = false, features = [
  "crisp",
  "linux-theme-detection",
  "tiny-skia",
  "wayland",
  "wgpu-bare",
  "x11",
  "smol",
  "sipper",
  "image-without-codecs",
  "advanced",
] }
iced_palace = "0.14"
image = { version = "0.25", default-features = false, features = ["png"] }
lucide-icons = { version = "1", features = ["iced"] }
sipper = "0.1"
rfd = "0.17"
smol = "2"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
directories = "6"
sys-locale = "0.3"
size = "0.5"
fs4 = { version = "1", default-features = false }
which-fs = "0.2"
ureq = { version = "3", default-features = false, features = ["gzip", "json"] }
open = "5"
wii-disc-info = { version = "0.10", features = ["async"] }
twbm-idmap = { version = "0.5", features = ["ascii-titles"] }
itertools = "0.15"
either = "1"
sanitize-filename = "=0.7.0-beta"
split-write = "0.2"
tempfile = "3"
arrayvec = "0.7"
zip = { version = "8", default-features = false, features = [
  "deflate-flate2-zlib-rs",
] }
enumflags2 = "0.7"
strum = "0.28"
strum_macros = "0.28"

[target.'cfg(any(target_os = "linux", all(target_os = "macos", target_arch = "aarch64")))'.dependencies]
mundy = { version = "0.2", default-features = false, features = [
  "accent-color",
  "color-scheme",
] }

[target.'cfg(any(target_os = "windows", all(target_os = "macos", target_arch = "x86_64")))'.dependencies]
dark-light = { version = "3", default-features = false }

# windows x86 has issues with bzip2 + lld
[target.'cfg(all(target_os = "windows", target_arch = "x86"))'.dependencies]
nod = { git = "https://github.com/wiidev/nod", branch = "fix-block-handling", default-features = false, features = [
  "compress-lzma-vendored",
  "compress-zlib-vendored",
  "compress-zstd-vendored",
  "threading",
] }

[target.'cfg(not(all(target_os = "windows", target_arch = "x86")))'.dependencies]
nod = { git = "https://github.com/wiidev/nod", branch = "fix-block-handling" }

[target.'cfg(target_os = "windows")'.dependencies]
wgpu = { version = "27.0", default-features = false, features = [
  "std",
  "parking_lot",
  "dx12",
] }
winsafe = { version = "0.0.29", features = ["dwm"] }

[target.'cfg(target_os = "linux")'.dependencies]
wgpu = { version = "27.0", default-features = false, features = [
  "std",
  "parking_lot",
  "vulkan",
] }

[target.'cfg(target_os = "macos")'.dependencies]
wgpu = { version = "27.0", default-features = false, features = [
  "std",
  "parking_lot",
  "metal",
] }


[build-dependencies]
hex = { version = "0.4", default-features = false }

# tiny and fast
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"

# speed dev builds
[profile.dev]
debug = "line-tables-only"
split-debuginfo = "unpacked"

# faster dev builds
[profile.dev.package."*"]
opt-level = 3
