[package]
name = "TinyWiiBackupManager"
version = "6.1.0"
edition = "2024"
rust-version = "1.97"
authors = ["Manuel Quarneti <mq1@ik.me>"]
license = "GPL-3.0-only"
repository = "https://github.com/mq1/TinyWiiBackupManager"
description = "A tiny game backup and homebrew app manager for the Wii"

[features]
default = ["native-https"]
native-https = ["isahc/native-tls"]
static-https = ["isahc/static-curl", "isahc/native-tls-static"]

[dependencies]
iced = { version = "0.14", default-features = false, features = [
    "crisp",
    "linux-theme-detection",
    "tiny-skia",
    "wayland",
    "wgpu-bare",
    "x11",
    "smol",
    "sipper",
    "image-without-codecs",
    "advanced",
] }
iced_palace = "0.14"
image = { version = "0.25", default-features = false, features = ["png"] }
lucide-icons = { version = "1", features = ["iced"] }
sipper = "0.1"
rfd = "0.17"
smol = "2"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
directories = "6"
sys-locale = "0.3"
size = "0.5"
fs4 = { version = "1", default-features = false }
which-fs = "0.2"
isahc = { version = "2", default-features = false }
open = "5"
wii-disc-info = { git = "https://github.com/mq1/wii-disc-info-rs", branch = "async" }
async_zip = { version = "0.0.18", features = ["deflate"] }
twbm-idmap = { version = "0.5", features = ["ascii-titles"] }
itertools = "0.15"
futures = "0.3"
either = "1"
sanitize-filename = "=0.7.0-beta"
path-clean = "1"
split-write = "0.2"
tempfile = "3"

# windows x86 has issues with bzip2 + lld
[target.'cfg(all(target_os = "windows", target_arch = "x86"))'.dependencies]
nod = { git = "https://github.com/wiidev/nod", branch = "fix-block-handling", default-features = false, features = [
    "compress-lzma-vendored",
    "compress-zlib-vendored",
    "compress-zstd-vendored",
    "threading",
] }

[target.'cfg(not(all(target_os = "windows", target_arch = "x86")))'.dependencies]
nod = { git = "https://github.com/wiidev/nod", branch = "fix-block-handling" }

[target.'cfg(target_os = "windows")'.dependencies]
wgpu = { version = "27.0", default-features = false, features = [
    "std",
    "parking_lot",
    "dx12",
] }

[target.'cfg(target_os = "linux")'.dependencies]
wgpu = { version = "27.0", default-features = false, features = [
    "std",
    "parking_lot",
    "vulkan",
] }

[target.'cfg(target_os = "macos")'.dependencies]
wgpu = { version = "27.0", default-features = false, features = [
    "std",
    "parking_lot",
    "metal",
] }

[build-dependencies]
hex = { version = "0.4", default-features = false }

# tiny and fast
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"

# speed up conversions in dev builds
[profile.dev.package."*"]
opt-level = 3
