// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { MyPalette } from "styling.slint";
import { IconDisplay, IconSet } from "@lucide";
import { Link } from "components/link.slint";
import { Rust } from "rust.slint";
import { Card } from "components/card.slint";
import { HorizontalLine } from "components/horizontal-line.slint";

export component AboutPage inherits Rectangle {
    Card {
        width: 600px;
        height: self.min-height;
        x: parent.width / 2 - self.width / 2;
        y: parent.height / 2 - self.height / 2;

        VerticalLayout {
            padding: 20px;
            spacing: 10px;
            alignment: start;

            HorizontalLayout {
                padding: 10px;
                spacing: 10px;

                Image {
                    source: @image-url("../assets/TinyWiiBackupManager-256x256.png");
                    width: 128px;
                    height: 128px;
                }

                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;
                    alignment: center;

                    Text {
                        text: "TinyWiiBackupManager v\{State.version}";
                        font-size: 18px;
                        font-weight: 700;
                    }

                    HorizontalLayout {
                        spacing: 50px;

                        Text {
                            text: "Copyright © 2026 Manuel Quarneti";
                        }

                        Link {
                            label: "github/mq1";
                            uri: "https://github.com/mq1";
                        }
                    }

                    Link {
                        label: "GPL-3.0-only";
                        uri: "https://www.gnu.org/licenses/gpl-3.0.html";
                        icon: IconSet.Scale;
                    }
                }
            }

            HorizontalLayout {
                spacing: 10px;

                VerticalLayout {
                    alignment: center;

                    IconDisplay {
                        icon: IconSet.TriangleAlert;
                        stroke: MyPalette.foreground;
                    }
                }

                Text {
                    text: "TinyWiiBackupManager is intended strictly for legal homebrew use and is not affiliated with or endorsed by Nintendo. Use of TinyWiiBackupManager for pirated or unauthorized copies of games is strictly prohibited.";
                    wrap: word-wrap;
                }
            }

            HorizontalLine { }

            HorizontalLayout {
                IconDisplay {
                    icon: IconSet.Heart;
                    stroke: MyPalette.foreground;
                    size: 15px;
                }

                Text {
                    text: " Special thanks to";
                    font-size: 16px;
                }
            }

            HorizontalLayout {
                Link {
                    label: "Luke Street";
                    uri: "https://github.com/encounter";
                    icon: IconSet.Triangle;
                }

                Text {
                    text: " for developing nod and helping TWBM leverage it effectively.";
                }
            }

            HorizontalLayout {
                Link {
                    label: "blackb0x";
                    uri: "https://github.com/wiidev";
                    icon: IconSet.WandSparkles;
                }

                Text {
                    text: " for invaluable feedback and advice during TWBM's development.";
                }
            }
        }
    }

    HorizontalLayout {
        x: 10px;
        y: parent.height - self.min-height - 10px;

        spacing: 10px;

        Link {
            label: "Data directory";
            uri: State.data-dir;
            icon: IconSet.Folder;
        }

        Link {
            label: "Source code";
            uri: "https://github.com/mq1/TinyWiiBackupManager";
        }

        Link {
            label: "Wiki";
            uri: "https://github.com/mq1/TinyWiiBackupManager/wiki";
        }
    }
}
