// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Palette } from "std-widgets.slint";
import { Navbar } from "components/navbar.slint";
import { GameGridPage } from "game-grid-page.slint";
import { SettingsPage } from "settings-page.slint";
import { AboutPage } from "about-page.slint";
import { Page } from "types.slint";
import { State, InitializeState } from "state.slint";
import { MyPalette } from "styling.slint";
import { Rust } from "rust.slint";
import { VerticalLine } from "components/vertical-line.slint";
import { Card } from "components/card.slint";
import { GameTablePage } from "game-table-page.slint";
import { Notifications } from "components/notifications.slint";
import { GameInfoModal } from "components/game-info-modal.slint";
import { DeletingDirModal } from "components/deleting-dir-modal.slint";
import {
    ConfirmConversionModal,
} from "components/confirm-conversion-modal.slint";
import { HomebrewAppsGridPage } from "homebrew-apps-grid-page.slint";
import { HomebrewAppInfoModal } from "components/homebrew-app-info-modal.slint";
import { HomebrewAppsTablePage } from "homebrew-apps-table-page.slint";
import { ScrubbingGameModal } from "components/scrubbing-game-modal.slint";

export * from "types.slint";
export { State, Rust }

export component AppWindow inherits Window {
    min-width: 800px;
    min-height: 600px;
    background: MyPalette.background;
    title: "TinyWiiBackupManager  ›  \{State.drive-info.label.is-empty ? "No drive selected" : State.drive-info.label}  (\{State.drive-info.used-gib.to-fixed(2)}/\{State.drive-info.total-gib.to-fixed(2)} GiB)";
    default-font-size: 14px;

    pure function is-modal-open() -> bool {
        !State.current-game.path.is-empty || !State.current-homebrew-app.path.is-empty || State.adding-games.length > 0 || !State.deleting-dir.is-empty || !State.scrubbing-game.path.is-empty
    }

    InitializeState { }

    HorizontalLayout {
        Navbar { }

        VerticalLayout {
            Rectangle {
                background: MyPalette.alternate-background;
                border-top-left-radius: 10px;
                border-width: 1px;
                border-color: MyPalette.border;

                if State.current-page == Page.Games && !State.config.contents.view-as-table: GameGridPage { }
                if State.current-page == Page.Games && State.config.contents.view-as-table: GameTablePage { }
                if State.current-page == Page.HomebrewApps && !State.config.contents.view-as-table: HomebrewAppsGridPage { }
                if State.current-page == Page.HomebrewApps && State.config.contents.view-as-table: HomebrewAppsTablePage { }
                if State.current-page == Page.Settings: SettingsPage { }
                if State.current-page == Page.About: AboutPage { }
            }

            if !State.status.is-empty: HorizontalLayout {
                VerticalLine { }

                HorizontalLayout {
                    padding: 10px;

                    Text {
                        text: State.status;
                    }
                }
            }
        }
    }

    if is-modal-open(): TouchArea {
        x: 0px;
        y: 0px;
        width: root.width;
        height: root.height;
    }

    if is-modal-open(): Rectangle {
        x: 0px;
        y: 0px;
        width: root.width;
        height: root.height;
        background: MyPalette.overlay;

        if !State.scrubbing-game.path.is-empty: ScrubbingGameModal {
            x: (root.width - self.width) / 2;
            y: (root.height - self.height) / 2;
        }
        if State.scrubbing-game.path.is-empty && !State.current-game.path.is-empty: GameInfoModal {
            x: (root.width - self.width) / 2;
            y: (root.height - self.height) / 2;
        }
        if !State.current-homebrew-app.path.is-empty: HomebrewAppInfoModal {
            x: (root.width - self.width) / 2;
            y: (root.height - self.height) / 2;
        }
        if State.adding-games.length > 0: ConfirmConversionModal {
            x: (root.width - self.width) / 2;
            y: (root.height - self.height) / 2;
        }
        if !State.deleting-dir.is-empty: DeletingDirModal {
            x: (root.width - self.width) / 2;
            y: (root.height - self.height) / 2;
        }
    }

    if State.notifications.length > 0: Notifications {
        x: root.width - self.width;
        y: root.height - self.height;
    }

    if !State.tooltip.text.is-empty: Card {
        x: State.tooltip.mouse-x + t.preferred-width + 18px > root.width ? State.tooltip.mouse-x - t.preferred-width - 18px : State.tooltip.mouse-x;
        y: State.tooltip.mouse-y;

        width: t.preferred-width + 18px;
        height: t.preferred-height + 16px;

        HorizontalLayout {
            padding-top: 8px;
            padding-bottom: 8px;
            padding-left: 9px;
            padding-right: 9px;

            t := Text {
                text: State.tooltip.text;
            }
        }
    }
}
