// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Button, VerticalBox, Palette, HorizontalBox } from "std-widgets.slint";
import { Navbar } from "components/navbar.slint";
import { GameGridPage } from "game-grid-page.slint";
import { SettingsPage } from "settings-page.slint";
import { AboutPage } from "about-page.slint";
import { Page } from "types.slint";
import { Styles } from "styles.slint";
import { State } from "state.slint";
import { Rust } from "rust.slint";
import { MessagePage } from "message-page.slint";
import { VerticalLine } from "components/vertical-line.slint";
import { Card } from "components/card.slint";
import { GamePage } from "game-page.slint";

export * from "types.slint";
export { State, Rust }

export component AppWindow inherits Window {
    min-width: 800px;
    min-height: 600px;
    background: State.message.text.is-empty ? Styles.card-bg() : Palette.background;
    title: "TinyWiiBackupManager  ›  " + (State.config.contents.mount-point.is-empty ? "No drive selected" : State.config.contents.mount-point) + "  (" + State.drive-usage.a-used + "/" + State.drive-usage.b-total + " GiB)";
    default-font-size: 14px;

    if !State.message.text.is-empty: MessagePage { }

    if State.message.text.is-empty: HorizontalLayout {
        Navbar { }

        VerticalLayout {
            Rectangle {
                background: Palette.background;
                border-top-left-radius: 10px;
                border-width: 1px;
                border-color: Palette.border;

                if State.current-page == Page.GameGrid: GameGridPage { }
                if State.current-page == Page.Settings: SettingsPage { }
                if State.current-page == Page.About: AboutPage { }
                if State.current-page == Page.Game: GamePage { }
            }

            if !State.status.is-empty: HorizontalLayout {
                VerticalLine {
                    width: 2px;
                }

                HorizontalBox {
                    Text {
                        text: State.status;
                    }
                }
            }
        }
    }

    if !State.tooltip.a-text.is-empty: Card {
        x: State.tooltip.b-mouse-x + t.preferred-width + 18px > root.width ? State.tooltip.b-mouse-x - t.preferred-width - 18px : State.tooltip.b-mouse-x;
        y: State.tooltip.c-mouse-y;

        width: t.preferred-width + 18px;
        height: t.preferred-height + 16px;

        HorizontalLayout {
            padding-top: 8px;
            padding-bottom: 8px;
            padding-left: 9px;
            padding-right: 9px;

            t := Text {
                text: State.tooltip.a-text;
            }
        }
    }
}
