// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Button, VerticalBox, Palette, HorizontalBox } from "std-widgets.slint";
import { Navbar } from "components/navbar.slint";
import { GamesPage } from "games_page.slint";
import { SettingsPage } from "settings_page.slint";
import { AboutPage } from "about_page.slint";
import { Page } from "types.slint";
import { Styles } from "styles.slint";
import { State } from "state.slint";
import { Rust } from "rust.slint";
import { MessagePage } from "message_page.slint";
import { VerticalLine } from "components/vertical_line.slint";

export * from "types.slint";
export { State, Rust }

export component AppWindow inherits Window {
    min-width: 800px;
    min-height: 600px;
    background: Styles.card_bg();
    title: "TinyWiiBackupManager  ›  " + (State.config.contents.mount_point.is-empty ? "No drive selected" : State.config.contents.mount_point) + "  (" + State.drive_usage.a_used + "/" + State.drive_usage.b_total + " GiB)";
    default-font-size: 14px;

    if !State.message.text.is-empty: MessagePage { }

    if State.message.text.is-empty: HorizontalLayout {
        Navbar { }

        VerticalLayout {
            Rectangle {
                background: Palette.background;
                border-top-left-radius: 10px;
                border-width: 1px;
                border-color: Palette.border;

                if State.current_page == Page.Games: GamesPage { }
                if State.current_page == Page.Settings: SettingsPage { }
                if State.current_page == Page.About: AboutPage { }
            }

            if !State.hint.is-empty: HorizontalLayout {
                VerticalLine {
                    width: 2px;
                }

                HorizontalBox {
                    Text {
                        text: "Hint: " + State.hint;
                    }
                }
            }

            if State.hint.is-empty && !State.status.is-empty: HorizontalLayout {
                VerticalLine {
                    width: 2px;
                }

                HorizontalBox {

                    Text {
                        text: State.status;
                    }
                }
            }
        }
    }
}
