// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

export enum Console {
    Wii,
    GameCube,
    Unknown,
}

@rust-attr(derive(serde::Serialize, serde::Deserialize))
export enum WiiOutputFormat {
    Wbfs,
    Iso,
}

@rust-attr(derive(serde::Serialize, serde::Deserialize))
export enum GcOutputFormat {
    Ciso,
    Iso,
}

@rust-attr(derive(serde::Serialize, serde::Deserialize))
export enum ArchiveFormat {
    Rvz,
    Iso,
}

@rust-attr(derive(serde::Serialize, serde::Deserialize))
export struct Config {
    mount_point: string,
    remove_sources_games: bool,
    remove_sources_apps: bool,
    scrub_update_partition: bool,
    wii_output_format: WiiOutputFormat,
    archive_format: ArchiveFormat,
    always_split: bool,
    wii_ip: string,
}

export struct Game {
    id: string,
    title: string,
    display_title: string,
    path: string,
    image: image,
    size: string,
    console: Console,
}

export struct HbcApp {
    slug: string,
    name: string,
    coder: string,
    version: string,
    release_date: string,
    short_description: string,
    long_description: string,
    path: string,
    image: image,
    size: string,
}

export enum TaskType {
    Converting,
    Archiving,
    CheckingForUpdates,
    DownloadingCovers,
    InstallingApps,
    DownloadingFolder,
    DownloadingFile,
    Unknown,
}

export struct UpdateInfo {
    version: string,
    url: string,
}

export struct OscWiiApp {
    slug: string,
    name: string,
    author: string,
    version: string,
    release_date: string,
    size: string,
    zip_url: string,
}
