// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { VerticalBox, HorizontalBox, ScrollView } from "std-widgets.slint";
import { State } from "state.slint";
import { MyPalette } from "styling.slint";
import { IconButton } from "components/icon-button.slint";
import { IconSet } from "@lucide";
import { Card } from "components/card.slint";
import { IconButtonKind } from "types.slint";
import { HorizontalLine } from "components/horizontal-line.slint";

export component ConfirmConversionPage inherits VerticalBox {
    alignment: center;

    HorizontalBox {
        alignment: center;

        Card {
            width: 500px;
            height: 400px;

            VerticalBox {
                ScrollView {
                    VerticalLayout {
                        alignment: start;
                        spacing: 5px;

                        Text {
                            text: "Picked \{State.adding-games.length} games, are you sure you want to continue?\n\n";
                        }

                        for game in State.adding-games: Text {
                            text: "• \{game.in-path}";
                        }
                    }
                }

                HorizontalLine { }

                HorizontalLayout {
                    alignment: end;
                    spacing: 10px;

                    IconButton {
                        label: "  Cancel  ";
                        kind: IconButtonKind.Secondary;
                        clicked => {
                            State.adding-games = [];
                        }
                    }

                    IconButton {
                        label: "  Ok  ";
                        kind: IconButtonKind.Primary;
                        clicked => {
                            State.add-to-queue();
                            State.start-conversion();
                        }
                    }
                }
            }
        }
    }
}
