// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { VerticalBox, HorizontalBox, ScrollView } from "std-widgets.slint";
import { State } from "state.slint";
import { MyPalette } from "styling.slint";
import { IconButton } from "components/icon-button.slint";
import { HorizontalLine } from "components/horizontal-line.slint";
import { IconSet } from "@lucide";
import { Card } from "components/card.slint";
import { IconButtonKind } from "types.slint";

export component DeleteDirPage inherits VerticalBox {
    alignment: center;

    HorizontalBox {
        alignment: center;

        Card {
            width: 500px;
            height: 400px;

            VerticalBox {
                Text {
                    text: "Are you sure you want to delete \"\{State.deleting-dir}\"?\nThis is irreversible!";
                }

                HorizontalLine { }

                HorizontalLayout {
                    alignment: end;
                    spacing: 10px;

                    IconButton {
                        label: "  Cancel  ";
                        kind: IconButtonKind.Secondary;
                        clicked => {
                            State.deleting-dir = "";
                        }
                    }

                    IconButton {
                        label: "  Delete  ";
                        kind: IconButtonKind.Danger;
                        clicked => State.delete-dir();
                    }
                }
            }
        }
    }
}
