// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Dialog, Vertical, MaterialText, HorizontalDivider, Icon } from "@material";
import { MyScrollView } from "scroll_view.slint";
import { DiscInfo } from "common.slint";

export component DiscInfoDialog inherits Dialog {
    in property <string> display_title;
    in property <DiscInfo> info;
    title: display_title;
    icon: @image-url("../mdi/information.svg");
    default-action-text: "Close";

    actions: ["Verify Hash", "GameTDB Page", "Game Directory"];

    callback open_url(string);
    callback verify_game(string);

    default_action_clicked => {
        self.close();
    }

    action-clicked(i) => {
        if i == 0 {
            verify_game(info.game-dir);
        }
        if i == 1 {
            open_url("https://www.gametdb.com/Wii/" + info.game-id);
        }
        if i == 2 {
            open_url(info.game-dir);
        }
    }

    MyScrollView {
        width: root.width * 0.75;
        height: root.height / 2;

        Vertical {
            alignment: start;

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/folder.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Path:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.game-dir;
                }
            }

            HorizontalDivider { }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/tag.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "ID:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.game-id;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/tag-edit.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Embedded Title:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.game-title;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/tennis.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Is Wii:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.is-wii ? "Yes" : "No";
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/cube-outline.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Is GameCube:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.is-gamecube ? "Yes" : "No";
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/counter.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Disc Number:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.disc-num;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/tag.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Disc Version:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.disc-version;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/earth.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Region:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.region;
                }
            }

            HorizontalDivider { }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/file-find.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Format:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.format;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/folder-zip.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Compression:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.compression;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/ruler.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Block Size:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.block-size;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/lock-question.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Decrypted:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.decrypted ? "Yes" : "No";
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/alert.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Needs Hash Recovery:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.needs-hash-recovery ? "Yes" : "No";
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/check-all.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Lossless:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.lossless ? "Yes" : "No";
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/scale.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Disc Size:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.disc-size;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/file-check.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "CRC32:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.crc32;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/file-check.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "MD5:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.md5;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/file-check.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "SHA1:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.sha1;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/file-check.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "XXH64:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: info.xxh64;
                }
            }
        }
    }
}
