// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { MyPalette } from "styling.slint";
import { GameCard } from "components/game-card.slint";
import { IconSet, IconDisplay } from "@lucide";
import { GamesToolbar } from "components/games-toolbar.slint";
import { GamesOtherToolbar } from "components/games-other-toolbar.slint";
import { Logic } from "logic.slint";

export component GameGridPage inherits VerticalLayout {
    callback open-info(int);

    private property <int> col-count: max(1, floor((self.width - 10px) / (172px + 10px)));

    HorizontalLayout {
        padding: 10px;

        GamesToolbar { }
    }

    ScrollView {
        width: parent.width;
        viewport-height: v.preferred-height;

        v := VerticalLayout {
            padding: 10px;
            padding-top: 0px;
            spacing: 10px;

            GamesOtherToolbar { }

            GridLayout {
                spacing: 10px;

                for game[i] in Logic.games: GameCard {
                    row: i / col-count;
                    col: mod(i, col-count);

                    game: game;
                    open-info() => open-info(i);
                }
            }
        }
    }
}
