// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Vertical, Horizontal, IconButton, ElevatedCard, MaterialText, MaterialStyleMetrics } from "@material";
import { Game, Console } from "common.slint";

export component GameCardBackground inherits Vertical {
    in property <Game> game;
    padding: MaterialStyleMetrics.padding_4;

    ElevatedCard {
        Vertical {
            Horizontal {
                spacing: 4px;

                if game.console == Console.Wii: Image {
                    source: @image-url("../mdi/tennis.svg");
                    height: 14px;
                    width: 14px;
                }

                if game.console == Console.Wii: MaterialText {
                    text: "Wii";
                }

                if game.console == Console.GameCube: Image {
                    source: @image-url("../mdi/cube-outline.svg");
                    height: 14px;
                    width: 14px;
                }

                if game.console == Console.GameCube: MaterialText {
                    text: "GC";
                }

                if game.console == Console.Unknown: MaterialText {
                    text: "???";
                }

                Rectangle {
                    horizontal-stretch: 1;
                }

                MaterialText {
                    text: game.size;
                }
            }

            Image {
                source: game.image;
            }

            MaterialText {
                horizontal-alignment: center;
                text: game.display-title;
            }

            Rectangle {
                height: 30px;
            }
        }
    }
}

export component GameCardButtons inherits Horizontal {
    alignment: center;
    height: 34px;
    callback open_game_info();
    callback open_game_dir();

    IconButton {
        icon: @image-url("../mdi/information.svg");
        tooltip: "Game Information";
        inline: true;
        clicked => {
            open_game_info();
        }
    }

    IconButton {
        icon: @image-url("../mdi/folder-open.svg");
        tooltip: "Open Game Directory";
        inline: true;
        clicked => {
            open_game_dir();
        }
    }

    IconButton {
        icon: @image-url("../mdi/check-all.svg");
        tooltip: "Verify Hashes";
        inline: true;
    }

    IconButton {
        icon: @image-url("../mdi/package-down.svg");
        tooltip: "Archive Game to rvz";
        inline: true;
    }

    IconButton {
        icon: @image-url("../mdi/trash-can.svg");
        tooltip: "Delete Game";
        inline: true;
    }
}
