// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { GamesToolbar } from "components/games-toolbar.slint";
import { ScrollView } from "std-widgets.slint";
import { HorizontalLine } from "components/horizontal-line.slint";
import { IconSet, IconDisplay } from "@lucide";
import { Card } from "components/card.slint";
import { MyPalette } from "styling.slint";
import { GameRow } from "components/game-row.slint";
import { GamesOtherToolbar } from "components/games-other-toolbar.slint";
import { UiState } from "ui-state.slint";
import { DisplayedGame } from "types.slint";
import { NoDrive } from "components/no-drive.slint";

export component GameTablePage inherits VerticalLayout {
    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        GamesToolbar { }

        if !UiState.config.mount-point.is-empty: GamesOtherToolbar { }
    }

    if UiState.config.mount-point.is-empty: NoDrive { }

    if !UiState.config.mount-point.is-empty: ScrollView {
        width: parent.width;
        viewport-height: v.preferred-height;

        v := VerticalLayout {
            padding: 10px;
            padding-top: 0px;

            Card {
                clip: true;
                height: v2.preferred-height;

                v2 := VerticalLayout {
                    for game[i] in UiState.games: VerticalLayout {
                        GameRow {
                            game: game;
                        }

                        HorizontalLine { }
                    }
                }
            }
        }
    }
}
