// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { VerticalBox, ScrollView, HorizontalBox } from "std-widgets.slint";
import { State } from "state.slint";
import { GameCard, GameCardConsts } from "components/game-card.slint";

export component GamesPage inherits VerticalLayout {
    alignment: start;

    VerticalBox {
        Text {
            text: "Games";
            font-size: 18px;
            font-weight: 600;
        }
    }

    ScrollView {
        height: parent.height - 40px;

        property <int> columns: Math.max(1, Math.floor((self.width - 20px) / GameCardConsts.spaced-width));

        for game[i] in State.game-list.games: GameCard {
            game: game;

            x: 12px + mod(i, columns) * GameCardConsts.spaced-width;
            y: Math.floor(i / columns) * GameCardConsts.spaced-height;
        }
    }
}
