// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { GamesToolbar } from "components/games-toolbar.slint";
import { ScrollView } from "std-widgets.slint";
import { HorizontalLine } from "components/horizontal-line.slint";
import { IconSet, IconDisplay } from "@lucide";
import { Card } from "components/card.slint";
import { MyPalette } from "styling.slint";
import { GameRow } from "components/game-row.slint";
import { GamesOtherToolbar } from "components/games-other-toolbar.slint";
import { Game, Config, DriveInfo } from "types.slint";

export component GameTablePage inherits VerticalLayout {
    in property <[Game]> games;
    in property <Config> config;
    in property <DriveInfo> drive-info;

    callback open-info(int);

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        GamesToolbar {
            config: config;
        }

        GamesOtherToolbar {
            games: games;
            drive-info: drive-info;
        }
    }

    ScrollView {
        width: parent.width;
        viewport-height: v.preferred-height;

        v := VerticalLayout {
            padding: 10px;
            padding-top: 0px;

            Card {
                clip: true;
                height: v2.preferred-height;

                v2 := VerticalLayout {
                    for game[i] in games: VerticalLayout {
                        GameRow {
                            game: game;
                            open-info => open-info(i);
                        }

                        HorizontalLine { }
                    }
                }
            }
        }
    }
}
