// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { VerticalBox, ScrollView, Palette } from "std-widgets.slint";
import { Game } from "types.slint";
import { IconSet, IconDisplay } from "@lucide";
import { State } from "state.slint";
import { Link } from "components/link.slint";
import { Card } from "components/card.slint";
import { HorizontalLine } from "components/horizontal-line.slint";
import { MyPalette } from "styling.slint";

export component GamePage inherits VerticalLayout {
    alignment: start;

    VerticalBox {
        Text {
            text: State.current-game.title;
            font-size: 18px;
        }

        Link {
            icon: IconSet.Folder;
            label: "Path: " + State.current-game.path;
            uri: State.current-game.path;
        }
    }

    ScrollView {
        height: parent.height - 40px;

        VerticalBox {
            padding-top: 0px;
            padding-right: 20px;
            height: 100%;

            Card {
                height: i.preferred-height;

                i := VerticalBox {
                    HorizontalLayout {
                        IconDisplay {
                            icon: IconSet.Disc3;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: " Disc info";
                        }
                    }

                    HorizontalLine { }

                    Text {
                        text: "ID: " + State.current-disc-info.id;
                    }

                    Text {
                        text: "Title: " + State.current-disc-info.title;
                    }
                }
            }
        }
    }
}
