// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView, Vertical, TextField, SegmentedButton, Horizontal } from "@material";
import { Game, ArchiveFormat } from "common.slint";
import { GameCard, GameCardButtons } from "game_card.slint";

export component GameGrid inherits ScrollView {
    in property <[Game]> games;
    out property <string> filter: "";
    property <bool> as_list: false;
    in property <ArchiveFormat> archive_format;

    property <length> card_w: as_list ? self.width - 16px : 176px;
    property <length> card_h: as_list ? 42px : 230px;

    property <int> columns: as_list ? 1 : (self.width / card_w).floor();
    property <int> rows: as_list ? games.length : (games.length / columns).ceil();

    callback open_url(string);
    callback remove_dir(string);
    callback update_filter(string);
    callback archive_game(string);
    callback verify_game(string);

    horizontal-stretch: 1;
    vertical-stretch: 1;
    viewport_height: rows * card_h + 56px + 16px;

    Vertical {
        Horizontal {
            TextField {
                height: 56px;
                leading_icon: @image-url("../mdi/magnify.svg");
                label: "Filter";
                placeholder-text: "Search...";
                edited(text) => {
                    filter = text;
                    update_filter(text.to-lowercase());
                }
            }

            SegmentedButton {
                height: 56px;

                items: [
                    { text: "As List", icon: @image-url("../mdi/view-list.svg") },
                    { text: "As Grid", icon: @image-url("../mdi/view-grid.svg") }
                ];
                current_index: as_list ? 0 : 1;
                index_changed(index) => {
                    as_list = index == 0;
                }
            }
        }

        Rectangle {
            for game[index] in games: GameCard {
                x: mod(index, columns) * card_w;
                y: (index / columns).floor() * card_h;
                is_li: as_list;
                width: card_w;
                height: card_h;
                game: game;
            }

            for game[index] in games: GameCardButtons {
                x: mod(index, columns) * card_w;
                y: (index / columns).floor() * card_h + (card_h - 38px);
                width: card_w;
                alignment: as_list ? end : center;
                padding-right: as_list ? 16px : 4px;
                archive_format: archive_format;
                open_game_info => {
                    open_url("https://www.gametdb.com/Wii/" + game.id);
                }
                open_game_dir => {
                    open_url(game.path);
                }
                remove_game => {
                    remove_dir(game.path);
                }
                archive_game => {
                    archive_game(game.path);
                }
                verify_game => {
                    verify_game(game.path);
                }
            }
        }
    }
}
