// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView, Vertical, Horizontal, Icon, MaterialPalette, FilledIconButton, IconButton } from "@material";
import { LineEdit } from "std-widgets.slint";
import { Game, Config } from "common.slint";
import { GameGrid } from "game_grid.slint";
import { GameList } from "game_list.slint";

export component GamesPage inherits VerticalLayout {
    in property <[Game]> games;
    out property <string> filter: "";
    in-out property <Config> config;

    callback add_games();
    callback update_filter(string);
    callback update_config();
    callback open_game_info(Game);
    callback open_game_dir(Game);
    callback remove_game(Game);
    callback archive_game(Game);
    callback verify_game(Game);
    callback trigger_sort(string);

    Rectangle {
        background: MaterialPalette.surface_variant;
        z: 2.0;

        Horizontal {
            VerticalLayout {
                alignment: center;
                Icon {
                    source: @image-url("../mdi/magnify.svg");
                }
            }

            LineEdit {
                height: 37px;
                placeholder-text: "Search...";
                text: filter;
                edited(text) => {
                    filter = text;
                    update_filter(text.to-lowercase());
                }
            }

            Rectangle {
                height: 37px;
                border-color: MaterialPalette.outline_variant;
                border-width: 1px;
                border-radius: 12px;

                HorizontalLayout {
                    IconButton {
                        checked: !config.sort_by_size;
                        icon: @image-url("../mdi/sort-alphabetical-ascending.svg");
                        tooltip: "Sort by Name";
                        clicked => {
                            config.sort-by-size = false;
                            update_config();
                            trigger_sort(filter);
                        }
                    }

                    IconButton {
                        checked: config.sort_by_size;
                        icon: @image-url("../mdi/sort-ascending.svg");
                        tooltip: "Sort by Size";
                        clicked => {
                            config.sort-by-size = true;
                            update_config();
                            trigger_sort(filter);
                        }
                    }
                }
            }

            Rectangle {
                height: 37px;
                border-color: MaterialPalette.outline_variant;
                border-width: 1px;
                border-radius: 12px;

                HorizontalLayout {
                    IconButton {
                        checked: !config.as_list;
                        icon: @image-url("../mdi/view-grid.svg");
                        tooltip: "Grid view";
                        clicked => {
                            config.as_list = false;
                            update_config();
                        }
                    }

                    IconButton {
                        checked: config.as_list;
                        icon: @image-url("../mdi/view-list.svg");
                        tooltip: "List view";
                        clicked => {
                            config.as_list = true;
                            update_config();
                        }
                    }
                }
            }

            FilledIconButton {
                height: 37px;
                width: 37px;
                icon: @image-url("../mdi/plus.svg");
                tooltip: "Add Games      ";
                clicked => {
                    add_games();
                }
            }
        }
    }

    if !config.as_list: GameGrid {
        games: games;
        archive_format: config.archive_format;
        open_game_info(game) => open_game_info(game);
        open_game_dir(game) => open_game_dir(game);
        remove_game(game) => remove_game(game);
        archive_game(game) => archive_game(game);
        verify_game(game) => verify_game(game);
    }

    if config.as_list: GameList {
        games: games;
        archive_format: config.archive_format;
        open_game_info(game) => open_game_info(game);
        open_game_dir(game) => open_game_dir(game);
        remove_game(game) => remove_game(game);
        archive_game(game) => archive_game(game);
        verify_game(game) => verify_game(game);
    }
}
