// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { MyPalette } from "styling.slint";
import { GameCard } from "components/game-card.slint";
import { IconSet, IconDisplay } from "@lucide";
import { GamesToolbar } from "components/games-toolbar.slint";
import { GamesOtherToolbar } from "components/games-other-toolbar.slint";
import { UiState } from "ui-state.slint";
import { DisplayedGame } from "types.slint";
import { NoDrive } from "components/no-drive.slint";

export component GameGridPage inherits VerticalLayout {
    private property <int> col-count: max(1, floor((self.width - 10px) / (172px + 10px)));

    HorizontalLayout {
        padding: 10px;

        GamesToolbar { }
    }

    if UiState.config.mount-point.is-empty: NoDrive { }

    if !UiState.config.mount-point.is-empty: ScrollView {
        width: parent.width;
        viewport-height: v.preferred-height;

        v := VerticalLayout {
            padding: 10px;
            padding-top: 0px;
            spacing: 10px;

            GamesOtherToolbar { }

            GridLayout {
                spacing: 10px;

                for game[i] in UiState.games: GameCard {
                    row: i / col-count;
                    col: mod(i, col-count);

                    game: game;
                }
            }
        }
    }
}
