// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { State } from "state.slint";
import { MyPalette } from "styling.slint";
import { GameCard } from "components/game-card.slint";
import { IconSet, IconDisplay } from "@lucide";
import { GamesToolbar } from "components/games-toolbar.slint";

export component GameGridPage inherits VerticalLayout {
    alignment: start;

    GamesToolbar { }

    ScrollView {
        height: parent.height - 40px;
        viewport-height: v.preferred-height;

        v := VerticalLayout {
            padding: 5px;

            if State.game-filter.is-empty && State.config.contents.show-wii: HorizontalLayout {
                padding-left: 5px;
                padding-bottom: 5px;

                IconDisplay {
                    icon: IconSet.Pointer;
                    size: 18px;
                    stroke: MyPalette.foreground;
                }

                Text {
                    text: " Wii games: " + State.game-list.wii-count + " found (" + State.game-list.wii-size + " GiB)";
                    font-size: 18px;
                }
            }

            if State.game-filter.is-empty && State.config.contents.show-wii: FlexBoxLayout {
                for game[i] in State.game-list.games: HorizontalLayout {
                    padding: game.is-wii ? 5px : 0px;

                    if game.is-wii: GameCard {
                        game: game;
                    }
                }
            }

            if State.game-filter.is-empty && State.config.contents.show-wii && State.config.contents.show-gc: HorizontalLayout {
                padding: 10px;
            }

            if State.game-filter.is-empty && State.config.contents.show-gc: HorizontalLayout {
                padding-left: 5px;
                padding-bottom: 5px;

                IconDisplay {
                    icon: IconSet.Box;
                    size: 18px;
                    stroke: MyPalette.foreground;
                }

                Text {
                    text: " GameCube games: " + State.game-list.gc-count + " found (" + State.game-list.gc-size + " GiB)";
                    font-size: 18px;
                }
            }

            if State.game-filter.is-empty && State.config.contents.show-gc: FlexBoxLayout {
                for game[i] in State.game-list.games: HorizontalLayout {
                    padding: game.is-wii ? 0px : 5px;

                    if !game.is-wii: GameCard {
                        game: game;
                    }
                }
            }

            if !State.game-filter.is-empty: FlexBoxLayout {
                for game[i] in State.filtered-games: HorizontalLayout {
                    padding: 5px;

                    GameCard {
                        game: game;
                    }
                }
            }
        }
    }
}
