// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { State } from "state.slint";
import { MyPalette } from "styling.slint";
import { IconSet, IconDisplay } from "@lucide";
import { HbcAppsToolbar } from "components/hbc-apps-toolbar.slint";
import { HbcAppCard } from "components/hbc-app-card.slint";
import { HbcAppsFilter } from "components/hbc-apps-filter.slint";

export component HbcAppsGridPage inherits Rectangle {
    toolbar := HbcAppsToolbar {
        x: 10px;
        y: 10px;
        width: parent.width - 20px;
    }

    ScrollView {
        x: 0px;
        y: toolbar.height + 10px;
        height: parent.height - toolbar.height - 10px;
        width: parent.width;

        VerticalLayout {
            padding: 10px;

            HorizontalLayout {
                alignment: space-between;
                padding-bottom: 10px;

                HbcAppsFilter { }

                HorizontalLayout {
                    Text {
                        vertical-alignment: center;
                        text: "\{State.hbc-app-list.apps.length} app\{State.hbc-app-list.apps.length == 1 ? "" : "s"}   ~ \{State.hbc-app-list.total-size.to-fixed(2)} MiB";
                    }
                }
            }

            if State.hbc-app-list.filter.is-empty: FlexboxLayout {
                spacing: 10px;

                for app in State.hbc-app-list.apps: HbcAppCard {
                    app: app;
                }
            }

            if !State.hbc-app-list.filter.is-empty: FlexboxLayout {
                spacing: 10px;

                for app in State.hbc-app-list.filtered-apps: HbcAppCard {
                    app: app;
                }
            }
        }
    }
}
