// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { State } from "state.slint";
import { MyPalette } from "styling.slint";
import { IconSet, IconDisplay } from "@lucide";
import { HbcAppsToolbar } from "components/hbc-apps-toolbar.slint";
import { HbcAppCard } from "components/hbc-app-card.slint";

export component HbcAppsGridPage inherits Rectangle {
    toolbar := HbcAppsToolbar {
        x: 10px;
        y: 10px;
        width: parent.width - 20px;
    }

    ScrollView {
        x: 0px;
        y: toolbar.height + 20px;
        height: parent.height - toolbar.height - 20px;
        width: parent.width;

        if State.hbc-app-list.filter.is-empty: FlexboxLayout {
            x: 10px;
            width: parent.width - 20px;
            spacing: 10px;

            for app in State.hbc-app-list.apps: HbcAppCard {
                app: app;
            }
        }

        if !State.hbc-app-list.filter.is-empty: FlexboxLayout {
            x: 10px;
            width: parent.width - 20px;
            spacing: 10px;

            for app in State.hbc-app-list.filtered-apps: HbcAppCard {
                app: app;
            }
        }
    }
}
