// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconButton, Horizontal, Icon, MaterialPalette, FilledIconButton, FilledButton } from "@material";
import { LineEdit } from "std-widgets.slint";
import { HbcApp, Config } from "common.slint";
import { HbcAppGrid } from "hbc_app_grid.slint";
import { HbcAppList } from "hbc_app_list.slint";

export component HbcAppsPage inherits VerticalLayout {
    in property <[HbcApp]> apps;
    out property <string> filter: "";
    in-out property <Config> config;

    callback add_apps();
    callback update_filter(string);
    callback update_config();
    callback open_app_info(HbcApp);
    callback open_app_dir(HbcApp);
    callback remove_app(HbcApp);
    callback open_wiiload();
    callback trigger_sort(string);

    Rectangle {
        background: MaterialPalette.surface_variant;
        z: 2.0;

        Horizontal {
            VerticalLayout {
                alignment: center;
                Icon {
                    source: @image-url("../mdi/magnify.svg");
                }
            }

            LineEdit {
                height: 37px;
                placeholder-text: "Search...";
                text: filter;
                edited(text) => {
                    filter = text;
                    update_filter(text.to-lowercase());
                }
            }

            Rectangle {
                height: 37px;
                border-color: MaterialPalette.outline_variant;
                border-width: 1px;
                border-radius: 12px;

                HorizontalLayout {
                    IconButton {
                        checked: !config.sort_by_size;
                        icon: @image-url("../mdi/sort-alphabetical-ascending.svg");
                        tooltip: "Sort by Name";
                        clicked => {
                            config.sort-by-size = false;
                            update_config();
                            trigger_sort(filter);
                        }
                    }

                    IconButton {
                        checked: config.sort_by_size;
                        icon: @image-url("../mdi/sort-ascending.svg");
                        tooltip: "Sort by Size";
                        clicked => {
                            config.sort-by-size = true;
                            update_config();
                            trigger_sort(filter);
                        }
                    }
                }
            }

            Rectangle {
                height: 37px;
                border-color: MaterialPalette.outline_variant;
                border-width: 1px;
                border-radius: 12px;

                HorizontalLayout {
                    IconButton {
                        checked: !config.as_list;
                        icon: @image-url("../mdi/view-grid.svg");
                        tooltip: "Grid view";
                        clicked => {
                            config.as_list = false;
                            update_config();
                        }
                    }

                    IconButton {
                        checked: config.as_list;
                        icon: @image-url("../mdi/view-list.svg");
                        tooltip: "List view";
                        clicked => {
                            config.as_list = true;
                            update_config();
                        }
                    }
                }
            }

            FilledIconButton {
                height: 37px;
                width: 37px;
                tooltip: "Add Apps";
                icon: @image-url("../mdi/plus.svg");
                clicked => {
                    add_apps();
                }
            }

            FilledButton {
                height: 37px;
                text: "WiiLoad";
                icon: @image-url("../mdi/upload-network.svg");
                clicked => {
                    open_wiiload();
                }
            }
        }
    }

    if !config.as_list: HbcAppGrid {
        apps: apps;
        open_app_info(app) => open_app_info(app);
        open_app_dir(app) => open_app_dir(app);
        remove_app(app) => remove_app(app);
    }

    if config.as_list: HbcAppList {
        apps: apps;
        open_app_info(app) => open_app_info(app);
        open_app_dir(app) => open_app_dir(app);
        remove_app(app) => remove_app(app);
    }
}
