// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Dialog, Vertical, MaterialText, HorizontalDivider, Icon } from "@material";
import { HbcApp } from "common.slint";
import { MyScrollView } from "scroll_view.slint";

export component HbcAppInfo inherits Dialog {
    in property <HbcApp> app;
    title: app.name;
    icon: @image-url("../mdi/information.svg");
    default-action-text: "Close";
    actions: ["App Directory"];

    callback open_url(string);

    default_action_clicked => {
        self.close();
    }

    action-clicked(i) => {
        if i == 0 {
            open_url(app.path);
        }
    }

    MyScrollView {
        width: root.width * 0.75;
        height: root.height / 2;

        Vertical {
            alignment: start;

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/account.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Coder:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: app.coder;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/tag.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Version:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: app.version;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/calendar.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Release Date:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: app.release-date;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/text-box.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Short Description:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: app.short-description;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/scale.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Size:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: app.size;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 4px;

                Icon {
                    source: @image-url("../mdi/folder.svg");
                }

                MaterialText {
                    vertical-alignment: center;
                    text: "Path:";
                }

                MaterialText {
                    vertical-alignment: center;
                    text: app.path;
                }
            }

            HorizontalDivider { }

            MaterialText {
                text: app.long-description;
                wrap: TextWrap.char-wrap;
            }
        }
    }
}
