// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ElevatedCard, Vertical, Horizontal, IconButton, MaterialText, Dialog, HorizontalDivider } from "@material";
import { HbcApp } from "common.slint";

export component HbcAppCard inherits VerticalLayout {
    in property <HbcApp> app;
    padding: 4px;

    ElevatedCard {
        Vertical {
            Horizontal {
                alignment: end;
                MaterialText {
                    text: app.size;
                }
            }

            Image {
                source: app.image;
            }

            MaterialText {
                horizontal-alignment: center;
                text: app.name;
            }

            Rectangle {
                height: 30px;
            }
        }
    }
}

export component HbcAppCardButtons inherits Horizontal {
    alignment: center;
    height: 34px;

    callback open_app_info();
    callback open_app_dir();
    callback remove_app();

    IconButton {
        icon: @image-url("../mdi/information.svg");
        tooltip: "App Information";
        inline: true;
        clicked => {
            open_app_info();
        }
    }

    IconButton {
        icon: @image-url("../mdi/folder-open.svg");
        tooltip: "Open App Directory";
        inline: true;
        clicked => {
            open_app_dir();
        }
    }

    IconButton {
        icon: @image-url("../mdi/trash-can.svg");
        tooltip: "Delete App";
        inline: true;
        clicked => {
            remove_app();
        }
    }
}

export component HbcAppInfo inherits Dialog {
    in property <HbcApp> app;
    title: app.name;
    default-action-text: "Close";

    default_action_clicked => {
        self.close();
    }

    Vertical {
        width: root.width * 0.75;

        Horizontal {
            alignment: start;

            MaterialText {
                text: "Coder: ";
            }

            MaterialText {
                text: app.coder;
            }
        }

        Horizontal {
            alignment: start;

            MaterialText {
                text: "Version: ";
            }

            MaterialText {
                text: app.version;
            }
        }

        Horizontal {
            alignment: start;

            MaterialText {
                text: "Release Date: ";
            }

            MaterialText {
                text: app.release-date;
            }
        }

        Horizontal {
            alignment: start;

            MaterialText {
                text: "Short Description: ";
            }

            MaterialText {
                text: app.short-description;
            }
        }

        Horizontal {
            alignment: start;

            MaterialText {
                text: "Size: ";
            }

            MaterialText {
                text: app.size;
            }
        }

        Horizontal {
            alignment: start;

            MaterialText {
                text: "Path: ";
            }

            MaterialText {
                text: app.path;
            }
        }

        HorizontalDivider { }

        MaterialText {
            text: app.long-description;
            wrap: TextWrap.char-wrap;
        }
    }
}
