// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import {
    Vertical,
    Horizontal,
    IconButton,
    MaterialText,
    HorizontalDivider,
    Icon,
    MaterialPalette,
    ScrollView
} from "@material";
import { HbcApp } from "common.slint";

component HbcAppCard inherits Rectangle {
    in property <HbcApp> app;

    callback open_app_info();
    callback remove_app();

    width: 166px;
    height: 200px;
    background: MaterialPalette.surface;
    border-color: MaterialPalette.outline_variant;
    border-radius: 12px;
    border-width: 1px;

    visible: !app.slug.is-empty;

    Vertical {
        alignment: space-between;

        Horizontal {
            alignment: end;

            MaterialText {
                vertical-alignment: center;
                text: app.size;
            }
        }

        Image {
            source: app.image;
        }

        MaterialText {
            horizontal-alignment: center;
            text: app.name;
        }

        Horizontal {
            alignment: center;

            IconButton {
                icon: @image-url("../mdi/information.svg");
                tooltip: "App Information";
                inline: true;
                clicked => {
                    open_app_info();
                }
            }

            IconButton {
                icon: @image-url("../mdi/trash-can.svg");
                tooltip: "Delete App";
                inline: true;
                clicked => {
                    remove_app();
                }
            }
        }
    }
}

export component HbcAppGrid inherits ScrollView {
    in property <[HbcApp]> apps;

    private property <int> cols: max(1, self.width / 180px);
    private property <int> rows: ceil(apps.length / cols);
    viewport_height: 32px + rows * 208px;

    callback open_app_info(HbcApp);
    callback remove_app(HbcApp);

    for i in apps.length: HbcAppCard {
        x: 16px + mod((apps.length - 1 - i), cols) * 174px;
        y: 16px + floor((apps.length - 1 - i) / cols) * 208px;

        app: apps[apps.length - 1 - i];
        open_app_info => open_app_info(apps[apps.length - 1 - i]);
        remove_app => remove_app(apps[apps.length - 1 - i]);
    }
}
