// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ElevatedCard, Vertical, Horizontal, IconButton, MaterialText, Dialog, HorizontalDivider, ScrollView, VerticalDivider, Icon } from "@material";
import { HbcApp } from "common.slint";

export component HbcAppCard inherits VerticalLayout {
    in property <HbcApp> app;
    in property <bool> is_li;
    padding: 4px;

    ElevatedCard {
        if !is_li: Vertical {
            Image {
                source: app.image;
            }

            MaterialText {
                horizontal-alignment: center;
                text: app.name;
            }

            HorizontalDivider { }

            Rectangle {
                vertical-stretch: 1;
            }

            Horizontal {
                padding: 4px;

                Icon {
                    source: @image-url("../mdi/account.svg");
                }

                MaterialText {
                    text: app.coder;
                }
            }

            Horizontal {
                padding: 4px;

                Icon {
                    source: @image-url("../mdi/tag.svg");
                }

                MaterialText {
                    text: app.version;
                }
            }

            Horizontal {
                padding: 4px;

                Icon {
                    source: @image-url("../mdi/calendar.svg");
                }

                MaterialText {
                    text: app.release-date;
                }
            }

            Horizontal {
                padding: 4px;

                Icon {
                    source: @image-url("../mdi/scale.svg");
                }

                MaterialText {
                    text: app.size;
                }
            }

            Rectangle {
                vertical-stretch: 1;
            }

            Rectangle {
                height: 30px;
            }
        }

        if is_li: Horizontal {
            alignment: start;
            spacing: 16px;
            padding-left: 12px;
            padding-right: 12px;

            MaterialText {
                vertical-alignment: center;
                text: app.name;
            }

            VerticalDivider { }

            Icon {
                source: @image-url("../mdi/account.svg");
            }

            MaterialText {
                vertical-alignment: center;
                text: app.coder;
            }

            VerticalDivider { }

            Icon {
                source: @image-url("../mdi/scale.svg");
            }

            MaterialText {
                vertical-alignment: center;
                text: app.size;
            }
        }
    }
}

export component HbcAppCardButtons inherits Horizontal {
    height: 34px;

    callback open_app_info();
    callback open_app_dir();
    callback remove_app();

    IconButton {
        icon: @image-url("../mdi/information.svg");
        tooltip: "App Information";
        inline: true;
        clicked => {
            open_app_info();
        }
    }

    IconButton {
        icon: @image-url("../mdi/folder-open.svg");
        tooltip: "Open App Directory";
        inline: true;
        clicked => {
            open_app_dir();
        }
    }

    IconButton {
        icon: @image-url("../mdi/trash-can.svg");
        tooltip: "Delete App";
        inline: true;
        clicked => {
            remove_app();
        }
    }
}

export component HbcAppInfo inherits Dialog {
    in property <HbcApp> app;
    title: app.name;
    default-action-text: "Close";

    default_action_clicked => {
        self.close();
    }

    ScrollView {
        width: root.width * 0.75;
        height: root.height / 2;

        VerticalLayout {
            spacing: 4px;

            Horizontal {
                alignment: start;
                padding: 4px;

                MaterialText {
                    text: "Coder: ";
                }

                MaterialText {
                    text: app.coder;
                }
            }

            Horizontal {
                alignment: start;
                padding: 4px;

                MaterialText {
                    text: "Version: ";
                }

                MaterialText {
                    text: app.version;
                }
            }

            Horizontal {
                alignment: start;
                padding: 4px;

                MaterialText {
                    text: "Release Date: ";
                }

                MaterialText {
                    text: app.release-date;
                }
            }

            Horizontal {
                alignment: start;
                padding: 4px;

                MaterialText {
                    text: "Short Description: ";
                }

                MaterialText {
                    text: app.short-description;
                }
            }

            Horizontal {
                alignment: start;
                padding: 4px;

                MaterialText {
                    text: "Size: ";
                }

                MaterialText {
                    text: app.size;
                }
            }

            Horizontal {
                alignment: start;
                padding: 4px;

                MaterialText {
                    text: "Path: ";
                }

                MaterialText {
                    text: app.path;
                }
            }

            HorizontalDivider { }

            MaterialText {
                text: app.long-description;
                wrap: TextWrap.char-wrap;
            }
        }
    }
}
