// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Horizontal, Icon, IconButton, TonalButton, FilledIconButton, MaterialPalette, TonalIconButton } from "@material";
import { LineEdit } from "std-widgets.slint";
import { HbcApp, Config, ViewAs, SortBy } from "common.slint";
import { HbcAppGrid } from "hbc_app_grid.slint";
import { HbcAppList } from "hbc_app_list.slint";

export component HbcAppsPage inherits VerticalLayout {
    private property <string> filter: "";
    in-out property <Config> config;

    callback add_apps();
    callback update_config();
    callback open_app_info(HbcApp);
    callback open_app_dir(HbcApp);
    callback remove_app(HbcApp);
    callback open_wiiload();
    callback trigger_sort(string);
    callback refresh();

    pure callback get_apps(string) -> [HbcApp];

    Rectangle {
        background: MaterialPalette.surface_container;
        z: 2.0;

        Horizontal {
            VerticalLayout {
                padding-left: 4px;
                alignment: center;
                Icon {
                    source: @image-url("../mdi/magnify.svg");
                }
            }

            LineEdit {
                height: 36px;
                placeholder-text: "Search...";
                text <=> filter;
            }

            VerticalLayout {
                alignment: center;

                Rectangle {
                    border-color: MaterialPalette.outline_variant;
                    border-radius: 12px;
                    border-width: 1px;

                    Horizontal {
                        IconButton {
                            checked: config.sort-by == SortBy.NameAscending || config.sort-by == SortBy.NameDescending;
                            icon: config.sort-by == SortBy.NameAscending || config.sort-by == SortBy.SizeAscending || config.sort-by == SortBy.SizeDescending ? @image-url("../mdi/sort-alphabetical-ascending.svg") : @image-url("../mdi/sort-alphabetical-descending.svg");
                            tooltip: "Sort by Name";
                            inline: true;
                            clicked => {
                                if config.sort-by == SortBy.NameAscending {
                                    config.sort-by = SortBy.NameDescending;
                                } else if config.sort-by == SortBy.NameDescending {
                                    config.sort-by = SortBy.NameAscending;
                                } else if config.sort-by == SortBy.SizeAscending || config.sort-by == SortBy.SizeDescending {
                                    config.sort-by = SortBy.NameAscending;
                                }
                                update_config();
                                trigger_sort(filter);
                            }
                        }

                        IconButton {
                            checked: config.sort-by == SortBy.SizeAscending || config.sort-by == SortBy.SizeDescending;
                            icon: config.sort-by == SortBy.SizeAscending || config.sort-by == SortBy.NameAscending || config.sort-by == SortBy.NameDescending ? @image-url("../mdi/sort-ascending.svg") : @image-url("../mdi/sort-descending.svg");
                            tooltip: "Sort by Size";
                            inline: true;
                            clicked => {
                                if config.sort-by == SortBy.SizeAscending {
                                    config.sort-by = SortBy.SizeDescending;
                                } else if config.sort-by == SortBy.SizeDescending {
                                    config.sort-by = SortBy.SizeAscending;
                                } else if config.sort-by == SortBy.NameAscending || config.sort-by == SortBy.NameDescending {
                                    config.sort-by = SortBy.SizeAscending;
                                }
                                update_config();
                                trigger_sort(filter);
                            }
                        }
                    }
                }
            }

            VerticalLayout {
                alignment: center;

                Rectangle {
                    border-color: MaterialPalette.outline_variant;
                    border-radius: 12px;
                    border-width: 1px;

                    Horizontal {
                        alignment: center;

                        IconButton {
                            checked: config.view-as == ViewAs.Grid;
                            icon: @image-url("../mdi/view-grid.svg");
                            tooltip: "Grid view";
                            inline: true;
                            clicked => {
                                config.view-as = ViewAs.Grid;
                                update_config();
                            }
                        }

                        IconButton {
                            checked: config.view-as == ViewAs.List;
                            icon: @image-url("../mdi/view-list.svg");
                            tooltip: "List view";
                            inline: true;
                            clicked => {
                                config.view-as = ViewAs.List;
                                update_config();
                            }
                        }
                    }
                }
            }

            TonalButton {
                height: 36px;
                text: "WiiLoad";
                icon: @image-url("../mdi/upload-network.svg");
                clicked => {
                    open_wiiload();
                }
            }

            TonalIconButton {
                height: 36px;
                width: 36px;
                icon: @image-url("../mdi/refresh.svg");
                tooltip: "Refresh";
                clicked => {
                    refresh();
                }
            }

            FilledIconButton {
                height: 36px;
                width: 36px;
                tooltip: "Add Apps   ";
                icon: @image-url("../mdi/plus.svg");
                clicked => {
                    add_apps();
                }
            }
        }
    }

    if config.view-as == ViewAs.Grid: HbcAppGrid {
        x: -4px;
        apps: get_apps(filter.to-lowercase());
        open_app_info(app) => open_app_info(app);
        remove_app(app) => remove_app(app);
    }

    if config.view-as == ViewAs.List: HbcAppList {
        x: -4px;
        apps: get_apps(filter.to-lowercase());
        open_app_info(app) => open_app_info(app);
        remove_app(app) => remove_app(app);
    }
}
