// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView, Vertical, Horizontal, Icon, MaterialPalette, MaterialText, HorizontalDivider, IconButton } from "@material";
import { HbcApp } from "common.slint";

export component HbcAppList inherits ScrollView {
    in property <[HbcApp]> apps;

    callback open_app_info(HbcApp);
    callback open_app_dir(HbcApp);
    callback remove_app(HbcApp);

    Horizontal {
        Vertical {
            for app in apps: Vertical {
                HorizontalLayout {
                    spacing: 4px;
                    Icon {
                        source: @image-url("../mdi/star.svg");
                    }

                    MaterialText {
                        vertical-alignment: center;
                        text: app.name;
                    }
                }

                HorizontalDivider { }
            }
        }

        Vertical {
            for app in apps: Vertical {
                HorizontalLayout {
                    spacing: 4px;
                    Icon {
                        source: @image-url("../mdi/account.svg");
                    }

                    MaterialText {
                        vertical-alignment: center;
                        text: app.coder;
                    }
                }

                HorizontalDivider { }
            }
        }

        Vertical {
            for app in apps: Vertical {
                HorizontalLayout {
                    spacing: 4px;
                    Icon {
                        source: @image-url("../mdi/tag.svg");
                    }

                    MaterialText {
                        vertical-alignment: center;
                        text: app.version;
                    }
                }

                HorizontalDivider { }
            }
        }

        Vertical {
            for app in apps: Vertical {
                HorizontalLayout {
                    spacing: 4px;
                    Icon {
                        source: @image-url("../mdi/scale.svg");
                    }

                    MaterialText {
                        vertical-alignment: center;
                        text: app.size;
                    }
                }

                HorizontalDivider { }
            }
        }

        Vertical {
            for app in apps: Vertical {
                HorizontalLayout {
                    spacing: 4px;

                    padding-left: -22px;
                    Icon { }

                    IconButton {
                        icon: @image-url("../mdi/information.svg");
                        tooltip: "App Information";
                        inline: true;
                        clicked => {
                            open_app_info(app);
                        }
                    }

                    IconButton {
                        icon: @image-url("../mdi/folder-open.svg");
                        tooltip: "Open App Directory";
                        inline: true;
                        clicked => {
                            open_app_dir(app);
                        }
                    }

                    IconButton {
                        icon: @image-url("../mdi/trash-can.svg");
                        tooltip: "Delete App";
                        inline: true;
                        clicked => {
                            remove_app(app);
                        }
                    }
                }

                HorizontalDivider { }
            }
        }
    }
}
