// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import {
    IconButton,
    MaterialText,
    HorizontalDivider,
    Icon,
    MaterialPalette,
    ScrollView
} from "@material";
import { HbcApp } from "common.slint";

component HbcAppCard inherits Rectangle {
    in property <HbcApp> app;

    callback open_app_info();
    callback remove_app();

    width: 166px;
    height: 16px + 14px + 8px + 96px + 8px + 14px + 16px + 1px + 4px + 18px + 8px;
    background: MaterialPalette.surface;
    border-color: MaterialPalette.outline_variant;
    border-radius: 12px;
    border-width: 1px;

    MaterialText {
        x: parent.width - self.width - 16px;
        y: 16px;
        text: app.size;
    }

    Image {
        x: 16px;
        y: 16px + 14px + 8px;
        height: 96px;
        width: parent.width - 32px;
        image-fit: contain;
        source: app.image;
    }

    MaterialText {
        x: 16px;
        y: 16px + 14px + 8px + 96px + 8px;
        width: parent.width - 32px;
        horizontal-alignment: center;
        text: app.name;
    }

    HorizontalDivider {
        x: 16px;
        y: 16px + 14px + 8px + 96px + 8px + 14px + 16px;
        width: parent.width - 32px;
    }

    Rectangle {
        y: 16px + 14px + 8px + 96px + 8px + 14px + 16px + 1px + 4px;
        x: parent.width / 2 - (18px + 4px + 18px + 4px) / 2;
        height: 18px;

        IconButton {
            x: 0px;
            icon: @image-url("../mdi/information.svg");
            tooltip: "App Information";
            inline: true;
            clicked => {
                open_app_info();
            }
        }

        IconButton {
            x: 18px + 4px;
            icon: @image-url("../mdi/trash-can.svg");
            tooltip: "Delete App";
            inline: true;
            clicked => {
                remove_app();
            }
        }
    }
}

export component HbcAppGrid inherits ScrollView {
    in property <[HbcApp]> apps;

    private property <int> cols: max(1, self.width / 180px);
    private property <int> rows: ceil(apps.length / cols);
    viewport_height: 32px + rows * 208px;

    callback open_app_info(HbcApp);
    callback remove_app(HbcApp);

    for i in apps.length: HbcAppCard {
        x: 16px + mod((apps.length - 1 - i), cols) * 174px;
        y: 16px + floor((apps.length - 1 - i) / cols) * (16px + 14px + 8px + 96px + 8px + 14px + 16px + 1px + 4px + 18px + 8px + 8px);

        app: apps[apps.length - 1 - i];
        open_app_info => open_app_info(apps[apps.length - 1 - i]);
        remove_app => remove_app(apps[apps.length - 1 - i]);
    }
}
