// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Horizontal, Icon, MaterialPalette, MaterialText, HorizontalDivider, IconButton } from "@material";
import { HbcApp } from "common.slint";
import { MyScrollView } from "scroll_view.slint";

export component HbcAppList inherits MyScrollView {
    in property <[HbcApp]> apps;

    callback open_app_info(HbcApp);
    callback remove_app(HbcApp);

    viewport_height: (4px + 18px + 4px) * apps.length + 36px;

    // Draw the horizontal separator lines
    for i in apps.length - 1: HorizontalDivider {
        x: 8px;
        y: (4px + 18px + 4px) * (i + 1) + 3px;
        width: parent.width - 16px;
    }

    Horizontal {
        Rectangle {
            horizontal-stretch: 2;

            for app[i] in apps: MaterialText {
                x: 0px;
                y: (4px + 18px + 4px) * i + 2px;
                text: app.name;
                width: parent.width;
            }
        }

        Rectangle {
            horizontal-stretch: 1;

            for i in apps.length: Icon {
                x: 0px;
                y: (4px + 18px + 4px) * i + 2px;
                height: 14px;
                width: 14px;
                source: @image-url("../mdi/account.svg");
            }

            for app[i] in apps: MaterialText {
                x: 14px + 4px;
                y: (4px + 18px + 4px) * i + 2px;
                text: app.coder;
                width: parent.width - 14px - 4px;
            }
        }

        Rectangle {
            horizontal-stretch: 1;

            for i in apps.length: Icon {
                x: 0px;
                y: (4px + 18px + 4px) * i + 2px;
                height: 14px;
                width: 14px;
                source: @image-url("../mdi/tag.svg");
            }

            for app[i] in apps: MaterialText {
                x: 14px + 4px;
                y: (4px + 18px + 4px) * i + 2px;
                text: app.version;
                width: parent.width - 14px - 4px;
            }
        }

        Rectangle {
            horizontal-stretch: 1;

            for i in apps.length: Icon {
                x: 0px;
                y: (4px + 18px + 4px) * i + 2px;
                height: 14px;
                width: 14px;
                source: @image-url("../mdi/scale.svg");
            }

            for app[i] in apps: MaterialText {
                x: 14px + 4px;
                y: (4px + 18px + 4px) * i + 2px;
                text: app.size;
                width: parent.width - 14px - 4px;
            }
        }

        // We draw bottom to top to preserve the tooltips
        Rectangle {
            horizontal-stretch: 1;
            width: 18px + 4px + 18px;

            for i in apps.length: Rectangle {
                x: 0px;
                y: (4px + 18px + 4px) * (apps.length - i - 1);

                IconButton {
                    x: 0px;
                    y: 0px;
                    height: 18px;
                    width: 18px;
                    icon: @image-url("../mdi/information.svg");
                    tooltip: "App Information    ";
                    inline: true;
                    clicked => {
                        open_app_info(apps[apps.length - i - 1]);
                    }
                }

                IconButton {
                    x: 18px + 4px;
                    y: 0px;
                    height: 18px;
                    width: 18px;
                    icon: @image-url("../mdi/trash-can.svg");
                    tooltip: "Delete App          ";
                    inline: true;
                    clicked => {
                        remove_app(apps[apps.length - i - 1]);
                    }
                }
            }
        }
    }
}
