// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { MyPalette } from "styling.slint";
import { IconSet, IconDisplay } from "@lucide";
import { HomebrewAppsToolbar } from "components/homebrew-apps-toolbar.slint";
import { HomebrewAppCard } from "components/homebrew-app-card.slint";
import {
    HomebrewAppsOtherToolbar,
} from "components/homebrew-apps-other-toolbar.slint";
import { UiState } from "ui-state.slint";
import { DisplayedHomebrewApp } from "types.slint";
import { NoDrive } from "components/no-drive.slint";

export component HomebrewAppsGridPage inherits VerticalLayout {
    private property <int> col-count: max(1, floor((self.width - 10px) / (172px + 10px)));

    HorizontalLayout {
        padding: 10px;

        HomebrewAppsToolbar { }
    }

    if UiState.config.mount-point.is-empty: NoDrive { }

    if !UiState.config.mount-point.is-empty: ScrollView {
        width: parent.width;
        viewport-height: v.preferred-height;

        v := VerticalLayout {
            padding: 10px;
            padding-top: 0px;
            spacing: 10px;

            HomebrewAppsOtherToolbar { }

            GridLayout {
                spacing: 10px;

                for app[i] in UiState.homebrew-apps: HomebrewAppCard {
                    row: i / col-count;
                    col: mod(i, col-count);

                    app: app;
                }
            }
        }
    }
}
