// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { HorizontalLine } from "components/horizontal-line.slint";
import { IconSet, IconDisplay } from "@lucide";
import { Card } from "components/card.slint";
import { MyPalette } from "styling.slint";
import { HomebrewAppsToolbar } from "components/homebrew-apps-toolbar.slint";
import {
    HomebrewAppsOtherToolbar,
} from "components/homebrew-apps-other-toolbar.slint";
import { HomebrewAppRow } from "components/homebrew-app-row.slint";
import { HomebrewApp, Config } from "types.slint";

export component HomebrewAppsTablePage inherits VerticalLayout {
    in property <[HomebrewApp]> apps;
    in-out property <Config> config;

    callback open-info(int);

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        HomebrewAppsToolbar {
            config <=> config;
        }

        HomebrewAppsOtherToolbar {
            apps: apps;
        }
    }

    ScrollView {
        width: parent.width;
        viewport-height: v.preferred-height;

        v := VerticalLayout {
            padding: 10px;
            padding-top: 0px;

            Card {
                clip: true;
                height: v2.preferred-height;

                v2 := VerticalLayout {
                    for app[i] in apps: VerticalLayout {
                        HomebrewAppRow {
                            app: app;
                            open-info() => open-info(i);
                        }

                        HorizontalLine { }
                    }
                }
            }
        }
    }
}
