// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { State } from "state.slint";
import { HorizontalLine } from "components/horizontal-line.slint";
import { IconSet, IconDisplay } from "@lucide";
import { Card } from "components/card.slint";
import { MyPalette } from "styling.slint";
import { HomebrewAppsToolbar } from "components/homebrew-apps-toolbar.slint";
import {
    HomebrewAppsOtherToolbar,
} from "components/homebrew-apps-other-toolbar.slint";
import { HomebrewAppRow } from "components/homebrew-app-row.slint";

export component HomebrewAppsTablePage inherits VerticalLayout {
    padding: 10px;
    spacing: 10px;

    HomebrewAppsToolbar { }

    HomebrewAppsOtherToolbar { }

    Card {
        height: parent.height - 38px * 2 - 40px;
        clip: true;

        ScrollView {
            height: parent.height;

            VerticalLayout {
                for app in State.homebrew-app-list.apps: VerticalLayout {
                    HomebrewAppRow {
                        app: app;
                    }

                    HorizontalLine { }
                }
            }
        }
    }
}
