// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { HorizontalLine } from "components/horizontal-line.slint";
import { IconSet, IconDisplay } from "@lucide";
import { Card } from "components/card.slint";
import { MyPalette } from "styling.slint";
import { HomebrewAppsToolbar } from "components/homebrew-apps-toolbar.slint";
import {
    HomebrewAppsOtherToolbar,
} from "components/homebrew-apps-other-toolbar.slint";
import { HomebrewAppRow } from "components/homebrew-app-row.slint";
import { UiState } from "ui-state.slint";
import { DisplayedHomebrewApp } from "types.slint";
import { NoDrive } from "components/no-drive.slint";

export component HomebrewAppsTablePage inherits VerticalLayout {
    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        HomebrewAppsToolbar { }

        if !UiState.config.mount-point.is-empty: HomebrewAppsOtherToolbar { }
    }

    if UiState.config.mount-point.is-empty: NoDrive { }

    if !UiState.config.mount-point.is-empty: ScrollView {
        width: parent.width;
        viewport-height: v.preferred-height;

        v := VerticalLayout {
            padding: 10px;
            padding-top: 0px;

            Card {
                clip: true;
                height: v2.preferred-height;

                v2 := VerticalLayout {
                    for app[i] in UiState.homebrew-apps: VerticalLayout {
                        HomebrewAppRow {
                            app: app;
                        }

                        HorizontalLine { }
                    }
                }
            }
        }
    }
}
