// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import {
    DisplayedConfig,
    DisplayedDriveInfo,
    DisplayedGame,
    DisplayedHomebrewApp,
    DisplayedOscApp,
    DisplayedNotification,
    DisplayedDiscInfo,
    QueuedConversion,
} from "types.slint";

export global Logic {
    in-out property <DisplayedConfig> config;
    in-out property <string> app-version;
    in-out property <string> data-dir;
    in-out property <DisplayedDriveInfo> drive-info;
    in-out property <[DisplayedGame]> games;
    in-out property <[DisplayedHomebrewApp]> homebrew-apps;
    in-out property <[DisplayedOscApp]> osc-apps;
    in-out property <[DisplayedNotification]> notifications;
    in-out property <[QueuedConversion]> conversion-queue;
    in-out property <[QueuedConversion]> conversion-queue-buffer;
    in-out property <string> status;
    in-out property <string> crc32-status;
    in-out property <int> osc-refreshed-x-hours-ago;
    in-out property <int> osc-refreshed-x-minutes-ago;
    in-out property <DisplayedDiscInfo> current-disc-info;

    callback filter-games(string);
    callback filter-homebrew-apps(string);
    callback filter-osc-apps(string);
    callback cache-osc-contents(bool);
    callback refresh-all();
    callback confirm-conversion-queue-buffer();
    callback clear-conversion-queue-buffer();
    callback archive-game(int);
    callback scrub-game(int);
    callback delete-game(int);
    callback delete-homebrew-app(int);
    callback pick-games(bool);
    callback open-that(string);
    callback close-notification(int);
    callback pick-homebrew-apps();
    callback checksum(int);
    callback set-window-color(bool);
    callback pair-homebrew-osc();
    callback install-osc-app(int);
    callback download-osc-icons();
    callback load-game-info(int);

    // config
    callback pick-mount-point();
    callback set-wii-output-format(int);
    callback set-gc-output-format(int);
    callback set-always-split(bool);
    callback set-scrub-update-partition(bool);
    callback set-remove-sources-games(bool);
    callback set-remove-sources-apps(bool);
    callback set-txt-codes-source(int);
    callback set-theme-preference(int);
    callback set-view-as(int);
    callback set-sort-by(int);
    callback set-show-wii(bool);
    callback set-show-gc(bool);

    // util
    callback sync-config();
    callback notify-error(string);
    callback notify-info(string);
    callback trigger-conversion();
    callback set-status(string);
    callback set-crc32-status(string);
    callback reload-osc-icon(int);
    callback reload-cover(int);
    callback finished-downloading-covers();
    callback osc-contents-cached();
}
