// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import {
    DisplayedConfig,
    DisplayedDriveInfo,
    DisplayedGame,
    DisplayedHomebrewApp,
    DisplayedOscApp,
    Notification,
    DisplayedDiscInfo,
    QueuedConversion,
    Action,
} from "types.slint";

export global Logic {
    in-out property <DisplayedConfig> config;
    in-out property <string> app-version;
    in-out property <string> data-dir;
    in-out property <DisplayedDriveInfo> drive-info;
    in-out property <[DisplayedGame]> games;
    in-out property <[DisplayedHomebrewApp]> homebrew-apps;
    in-out property <[DisplayedOscApp]> osc-apps;
    in-out property <[Notification]> notifications;
    in-out property <[QueuedConversion]> conversion-queue;
    in-out property <[QueuedConversion]> conversion-queue-buffer;
    in-out property <string> status;
    in-out property <string> crc32-status;
    in-out property <int> osc-refreshed-x-hours-ago;
    in-out property <int> osc-refreshed-x-minutes-ago;
    in-out property <DisplayedDiscInfo> current-disc-info;
    in-out property <string> latest-version;

    callback dispatch(Action, string);
}
