// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconButton, Vertical, MaterialText, Modal, ElevatedCard } from "@material";
import { SideBar } from "sidebar.slint";
import { GameGrid } from "game_grid.slint";
import { Game, HbcApp, WiiOutputFormat, ArchiveFormat } from "common.slint";
import { HbcAppGrid } from "hbc_app_grid.slint";
import { SettingsPage } from "settings.slint";

export * from "common.slint";

export component MainWindow inherits Window {
    in property <string> app_name: "";
    in-out property <string> dir_name: "";
    in property <string> disk_usage: "";
    in property <bool> is_macos: false;
    in-out property <int> current_index: 0;
    in property <[Game]> games;
    in property <[HbcApp]> hbc_apps;
    in-out property <string> status;

    callback choose_mount_point();
    callback open_game_info(string);
    callback open_game_dir(string);
    callback remove_game(string);
    callback add_games();
    callback wii_output_format_changed(WiiOutputFormat);
    callback archive_format_changed(ArchiveFormat);
    callback remove_update_partition_changed(bool);

    preferred-width: 800px;
    preferred-height: 600px;
    title: app_name + " • " + games.length + " Games" + (dir_name.is_empty ? "" : " • " + dir_name + " (" + disk_usage + ")");

    HorizontalLayout {
        SideBar {
            current_index <=> current_index;
            is_macos: is_macos;
            game_count: games.length;
            choose_mount_point => {
                choose_mount_point();
            }
            set-window-title(title) => {
                root.title = app_name + title + (dir_name.is_empty ? "" : " • " + dir_name + " (" + disk_usage + ")");
            }
            add_games => {
                add_games();
            }
        }

        VerticalLayout {
            if current_index == 0 && !dir_name.is-empty: GameGrid {
                games: games;
                open_game_info(id) => {
                    open_game_info(id);
                }
                open_game_dir(path) => {
                    open_game_dir(path);
                }
                remove_game(path) => {
                    remove_game(path);
                }
            }

            if current_index == 1 && !dir_name.is-empty: HbcAppGrid {
                apps: hbc_apps;
            }

            if current_index == 3: SettingsPage { }

            if dir_name.is-empty: Vertical {
                alignment: end;
                padding-bottom: 16px;

                MaterialText {
                    text: "⬅  Choose a drive or directory";
                    font-size: 18px;
                }
            }
        }
    }

    if !status.is_empty: Modal {
        width: root.width;
        height: root.height;

        ElevatedCard {
            width: root.width / 2;
            height: root.height / 2;
            x: (root.width - self.width) / 2;
            y: (root.height - self.height) / 2;

            MaterialText {
                text: status;
            }
        }
    }
}
