// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { VerticalBox, HorizontalBox, ScrollView } from "std-widgets.slint";
import { State } from "state.slint";
import { MyPalette } from "styling.slint";
import { IconButton } from "components/icon-button.slint";
import { IconSet } from "@lucide";
import { Card } from "components/card.slint";
import { MessageKind, IconButtonKind } from "types.slint";

export component MessagePage inherits VerticalBox {
    alignment: center;

    HorizontalBox {
        alignment: center;

        Card {
            width: 500px;
            height: 400px;

            VerticalBox {
                ScrollView {
                    VerticalLayout {
                        alignment: start;

                        Text {
                            text: State.message.text;
                        }
                    }
                }

                Rectangle {
                    border-color: MyPalette.border;
                    border-width: 1px;
                    height: 1px;
                }

                HorizontalLayout {
                    alignment: end;
                    spacing: 5px;

                    if State.message.kind == MessageKind.Info: IconButton {
                        label: "Ok";
                        kind: IconButtonKind.Primary;
                        clicked => State.dismiss();
                    }

                    if State.message.kind == MessageKind.Error: IconButton {
                        label: "Ok";
                        kind: IconButtonKind.Warning;
                        clicked => State.dismiss();
                    }

                    if State.message.kind == MessageKind.DeleteDir || State.message.kind == MessageKind.GamesPicked: IconButton {
                        label: "Cancel";
                        kind: IconButtonKind.Secondary;
                        clicked => State.dismiss();
                    }

                    if State.message.kind == MessageKind.DeleteDir: IconButton {
                        label: "Delete";
                        kind: IconButtonKind.Danger;
                        clicked => State.delete-dir();
                    }

                    if State.message.kind == MessageKind.GamesPicked: IconButton {
                        label: "Ok";
                        kind: IconButtonKind.Primary;
                        clicked => {
                            State.add-to-queue(State.adding-games);
                            State.adding-games = [];
                            State.conversion-confirmed();
                            State.dismiss();
                        }
                    }
                }
            }
        }
    }
}
