// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { State } from "state.slint";
import { MyPalette } from "styling.slint";
import { IconSet, IconDisplay } from "@lucide";
import { OscToolbar } from "components/osc-toolbar.slint";
import { OscOtherToolbar } from "components/osc-other-toolbar.slint";
import { OscAppCard } from "components/osc-app-card.slint";

export component OscGridPage inherits VerticalLayout {
    HorizontalLayout {
        padding: 10px;
        OscToolbar { }
    }

    ScrollView {
        width: parent.width;
        viewport-height: v.preferred-height;

        v := VerticalLayout {
            padding: 10px;
            padding-top: 0px;
            spacing: 10px;

            OscOtherToolbar { }

            if State.osc-contents.filter.is-empty: FlexboxLayout {
                spacing: 10px;

                for app in State.osc-contents.apps: OscAppCard {
                    app: app;
                }
            }

            if !State.osc-contents.filter.is-empty: FlexboxLayout {
                spacing: 10px;

                for app in State.osc-contents.filtered-apps: OscAppCard {
                    app: app;
                }
            }
        }
    }
}
