// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { MyPalette } from "styling.slint";
import { IconSet, IconDisplay } from "@lucide";
import { OscToolbar } from "components/osc-toolbar.slint";
import { OscOtherToolbar } from "components/osc-other-toolbar.slint";
import { OscAppCard } from "components/osc-app-card.slint";
import { Logic } from "logic.slint";

export component OscGridPage inherits VerticalLayout {
    callback open-info(int);

    private property <int> col-count: max(1, floor((self.width - 10px) / (172px + 10px)));

    HorizontalLayout {
        padding: 10px;

        OscToolbar { }
    }

    if Logic.osc-apps.length == 0: HorizontalLayout {
        padding-left: 20px;

        Text {
            text: "Loading...";
        }
    }

    if Logic.osc-apps.length > 0: ScrollView {
        width: parent.width;
        viewport-height: v.preferred-height;

        v := VerticalLayout {
            padding: 10px;
            padding-top: 0px;
            spacing: 10px;

            OscOtherToolbar { }

            GridLayout {
                spacing: 10px;

                for app[i] in Logic.osc-apps: OscAppCard {
                    row: i / col-count;
                    col: mod(i, col-count);

                    app: app;
                    open-info() => open-info(i);
                    install() => Logic.install-osc-app(i);
                }
            }
        }
    }
}
