// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { State } from "state.slint";
import { HorizontalLine } from "components/horizontal-line.slint";
import { IconSet, IconDisplay } from "@lucide";
import { Card } from "components/card.slint";
import { MyPalette } from "styling.slint";
import { OscToolbar } from "components/osc-toolbar.slint";
import { OscOtherToolbar } from "components/osc-other-toolbar.slint";
import { OscAppRow } from "components/osc-app-row.slint";

export component OscTablePage inherits VerticalLayout {
    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        OscToolbar { }

        OscOtherToolbar { }
    }

    ScrollView {
        width: parent.width;
        viewport-height: v.preferred-height;

        v := VerticalLayout {
            padding: 10px;
            padding-top: 0px;

            Card {
                clip: true;
                height: v2.preferred-height;

                v2 := VerticalLayout {
                    for app in State.osc-apps: VerticalLayout {
                        OscAppRow {
                            app: app;
                        }

                        HorizontalLine { }
                    }
                }
            }
        }
    }
}
