// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import {
    Vertical,
    Horizontal,
    IconButton,
    MaterialText,
    HorizontalDivider,
    Icon,
    MaterialPalette,
} from "@material";
import { OscApp } from "common.slint";
import { MyScrollView } from "scroll_view.slint";

component OscAppCard inherits Rectangle {
    in property <OscApp> app;

    callback open_osc_info();
    callback download_osc();
    callback push_osc();

    width: 166px;
    height: 16px + 14px + 8px + 96px + 8px + 14px + 16px + 1px + 4px + 18px + 8px;
    background: MaterialPalette.surface;
    border-color: MaterialPalette.outline_variant;
    border-radius: 12px;
    border-width: 1px;

    MaterialText {
        x: parent.width - self.width - 16px;
        y: 16px;
        text: app.size;
    }

    Image {
        x: 16px;
        y: 16px + 14px + 8px;
        height: 96px;
        width: parent.width - 32px;
        image-fit: contain;
        source: app.icon;
    }

    MaterialText {
        x: 16px;
        y: 16px + 14px + 8px + 96px + 8px;
        width: parent.width - 32px;
        horizontal-alignment: center;
        text: app.name;
    }

    HorizontalDivider {
        x: 16px;
        y: 16px + 14px + 8px + 96px + 8px + 14px + 16px;
        width: parent.width - 32px;
    }

    Rectangle {
        y: 16px + 14px + 8px + 96px + 8px + 14px + 16px + 1px + 4px;
        x: parent.width / 2 - (18px + 4px + 18px + 4px + 18px) / 2;
        height: 18px;

        IconButton {
            x: 0px;
            icon: @image-url("../mdi/information.svg");
            tooltip: "App Information";
            inline: true;
            clicked => {
                open_osc_info();
            }
        }

        IconButton {
            x: 18px + 4px;
            icon: @image-url("../mdi/download.svg");
            tooltip: "Download";
            inline: true;
            clicked => {
                download_osc();
            }
        }

        IconButton {
            x: 18px + 4px + 18px + 4px;
            icon: @image-url("../mdi/upload-network.svg");
            tooltip: "Wiiload";
            inline: true;
            clicked => {
                push_osc();
            }
        }
    }
}

export component OscAppGrid inherits MyScrollView {
    in property <[OscApp]> apps;

    private property <int> cols: max(1, self.width / 180px);
    private property <int> rows: ceil(apps.length / cols);
    viewport_height: 36px + rows * (16px + 14px + 8px + 96px + 8px + 14px + 16px + 1px + 4px + 18px + 8px + 8px);

    callback open_osc_info(OscApp);
    callback download_osc(OscApp);
    callback push_osc(OscApp);

    for i in apps.length: OscAppCard {
        x: 4px + 16px + mod((apps.length - 1 - i), cols) * 174px;
        y: 16px + floor((apps.length - 1 - i) / cols) * (16px + 14px + 8px + 96px + 8px + 14px + 16px + 1px + 4px + 18px + 8px + 8px);

        app: apps[apps.length - 1 - i];
        open_osc_info => open_osc_info(apps[apps.length - 1 - i]);
        download_osc => download_osc(apps[apps.length - 1 - i]);
        push_osc => push_osc(apps[apps.length - 1 - i]);
    }
}
