// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconButton, Horizontal, Icon, MaterialPalette, MaterialText, VerticalDivider } from "@material";
import { LineEdit } from "std-widgets.slint";
import { OscApp, Config, ViewAs } from "common.slint";
import { OscAppGrid } from "osc_app_grid.slint";
import { OscAppList } from "osc_app_list.slint";

export component OscAppsPage inherits VerticalLayout {
    private property <string> filter: "";
    in property <string> osc_load_status: "";
    in-out property <Config> config;

    callback update_config();
    callback open_osc_info(OscApp);
    callback download_osc(OscApp);
    callback push_osc(OscApp);

    pure callback get_apps(string) -> [OscApp];

    Rectangle {
        background: MaterialPalette.surface_container;
        z: 2.0;

        Horizontal {
            VerticalLayout {
                padding-left: 4px;
                alignment: center;
                Icon {
                    source: @image-url("../mdi/magnify.svg");
                }
            }

            LineEdit {
                height: 36px;
                placeholder-text: "Search...";
                text <=> filter;
            }

            VerticalLayout {
                alignment: center;

                Rectangle {
                    border-color: MaterialPalette.outline_variant;
                    border-radius: 12px;
                    border-width: 1px;

                    Horizontal {
                        alignment: center;

                        IconButton {
                            checked: config.view-as == ViewAs.Grid;
                            icon: @image-url("../mdi/view-grid.svg");
                            tooltip: "Grid view";
                            inline: true;
                            clicked => {
                                config.view-as = ViewAs.Grid;
                                update_config();
                            }
                        }

                        IconButton {
                            checked: config.view-as == ViewAs.List;
                            icon: @image-url("../mdi/view-list.svg");
                            tooltip: "List view";
                            inline: true;
                            clicked => {
                                config.view-as = ViewAs.List;
                                update_config();
                            }
                        }
                    }
                }
            }

            VerticalDivider { }

            VerticalLayout {
                alignment: center;
                Icon {
                    source: @image-url("../mdi/upload-network.svg");
                }
            }

            MaterialText {
                vertical-alignment: center;
                text: "Wii IP:";
            }

            LineEdit {
                height: 36px;
                width: 160px;
                text: config.wii-ip;
                edited(text) => {
                    config.wii-ip = text;
                }
            }
        }
    }

    if !osc_load_status.is-empty: VerticalLayout {
        alignment: center;

        HorizontalLayout {
            alignment: center;

            MaterialText {
                text: osc_load_status;
            }
        }
    }

    if osc_load_status.is-empty && config.view-as == ViewAs.Grid: OscAppGrid {
        x: -4px;
        apps: get_apps(filter.to-lowercase());
        open_osc_info(app) => open_osc_info(app);
        download_osc(app) => download_osc(app);
        push_osc(app) => push_osc(app);
    }

    if osc_load_status.is-empty && config.view-as == ViewAs.List: OscAppList {
        x: -4px;
        apps: get_apps(filter.to-lowercase());
        open_osc_info(app) => open_osc_info(app);
        download_osc(app) => download_osc(app);
        push_osc(app) => push_osc(app);
    }
}
