// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconButton, Horizontal, Icon, MaterialPalette, MaterialText, VerticalDivider } from "@material";
import { LineEdit } from "std-widgets.slint";
import { OscWiiApp, Config, ViewAs } from "common.slint";
import { OscWiiAppGrid } from "oscwii_app_grid.slint";
import { OscWiiAppList } from "oscwii_app_list.slint";

export component OscWiiAppsPage inherits VerticalLayout {
    in property <[OscWiiApp]> apps;
    out property <string> filter: "";
    in-out property <Config> config;

    callback update_filter(string);
    callback update_config();
    callback open_oscwii_info(OscWiiApp);
    callback download_oscwii(OscWiiApp);
    callback push_oscwii(OscWiiApp);

    Rectangle {
        background: MaterialPalette.surface_container;
        z: 2.0;

        Horizontal {
            padding: 6px;

            VerticalLayout {
                padding-left: 2px;
                alignment: center;
                Icon {
                    source: @image-url("../mdi/magnify.svg");
                }
            }

            LineEdit {
                height: 36px;
                placeholder-text: "Search...";
                text: filter;
                edited(text) => {
                    filter = text;
                    update_filter(text.to-lowercase());
                }
            }

            VerticalDivider { }

            VerticalLayout {
                alignment: center;

                IconButton {
                    checked: config.view-as == ViewAs.Grid;
                    icon: @image-url("../mdi/view-grid.svg");
                    tooltip: "Grid view";
                    inline: true;
                    clicked => {
                        config.view-as = ViewAs.Grid;
                        update_config();
                    }
                }
            }

            VerticalLayout {
                alignment: center;
                IconButton {
                    checked: config.view-as == ViewAs.List;
                    icon: @image-url("../mdi/view-list.svg");
                    tooltip: "List view";
                    inline: true;
                    clicked => {
                        config.view-as = ViewAs.List;
                        update_config();
                    }
                }
            }

            VerticalDivider { }

            VerticalLayout {
                alignment: center;
                Icon {
                    source: @image-url("../mdi/upload-network.svg");
                }
            }

            MaterialText {
                vertical-alignment: center;
                text: "Wii IP:";
            }

            LineEdit {
                height: 36px;
                width: 160px;
                text: config.wii-ip;
                edited(text) => {
                    config.wii-ip = text;
                }
            }
        }
    }

    if config.view-as == ViewAs.Grid: OscWiiAppGrid {
        apps: apps;
        open_oscwii_info(app) => open_oscwii_info(app);
        download_oscwii(app) => download_oscwii(app);
        push_oscwii(app) => push_oscwii(app);
    }

    if config.view-as == ViewAs.List: OscWiiAppList {
        apps: apps;
        open_oscwii_info(app) => open_oscwii_info(app);
        download_oscwii(app) => download_oscwii(app);
        push_oscwii(app) => push_oscwii(app);
    }
}
