// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import {
    Vertical,
    Horizontal,
    IconButton,
    MaterialText,
    HorizontalDivider,
    Icon,
    MaterialPalette,
    ScrollView
} from "@material";
import { OscWiiApp } from "common.slint";

component OscWiiAppCard inherits Rectangle {
    in property <OscWiiApp> app;

    callback open_oscwii_info();
    callback download_oscwii();
    callback push_oscwii();

    width: 166px;
    height: 16px + 14px + 8px + 96px + 8px + 14px + 16px + 1px + 4px + 18px + 8px;
    background: MaterialPalette.surface;
    border-color: MaterialPalette.outline_variant;
    border-radius: 12px;
    border-width: 1px;

    MaterialText {
        x: parent.width - self.width - 16px;
        y: 16px;
        text: app.size;
    }

    Image {
        x: 16px;
        y: 16px + 14px + 8px;
        height: 96px;
        width: parent.width - 32px;
        image-fit: contain;
    }

    MaterialText {
        x: 16px;
        y: 16px + 14px + 8px + 96px + 8px;
        width: parent.width - 32px;
        horizontal-alignment: center;
        text: app.name;
    }

    HorizontalDivider {
        x: 16px;
        y: 16px + 14px + 8px + 96px + 8px + 14px + 16px;
        width: parent.width - 32px;
    }

    Rectangle {
        y: 16px + 14px + 8px + 96px + 8px + 14px + 16px + 1px + 4px;
        x: parent.width / 2 - (18px + 4px + 18px + 4px + 18px) / 2;
        height: 18px;

        IconButton {
            x: 0px;
            icon: @image-url("../mdi/information.svg");
            tooltip: "App Information";
            inline: true;
            clicked => {
                open_oscwii_info();
            }
        }

        IconButton {
            x: 18px + 4px;
            icon: @image-url("../mdi/download.svg");
            tooltip: "Download";
            inline: true;
            clicked => {
                download_oscwii();
            }
        }

        IconButton {
            x: 18px + 4px + 18px + 4px;
            icon: @image-url("../mdi/upload-network.svg");
            tooltip: "Wiiload";
            inline: true;
            clicked => {
                push_oscwii();
            }
        }
    }
}

export component OscWiiAppGrid inherits ScrollView {
    in property <[OscWiiApp]> apps;

    private property <int> cols: max(1, self.width / 180px);
    private property <int> rows: ceil(apps.length / cols);
    viewport_height: 32px + rows * 208px;

    callback open_oscwii_info(OscWiiApp);
    callback download_oscwii(OscWiiApp);
    callback push_oscwii(OscWiiApp);

    for i in apps.length: OscWiiAppCard {
        x: 16px + mod((apps.length - 1 - i), cols) * 174px;
        y: 16px + floor((apps.length - 1 - i) / cols) * (16px + 14px + 8px + 96px + 8px + 14px + 16px + 1px + 4px + 18px + 8px + 8px);

        app: apps[apps.length - 1 - i];
        open_oscwii_info => open_oscwii_info(apps[apps.length - 1 - i]);
        download_oscwii => download_oscwii(apps[apps.length - 1 - i]);
        push_oscwii => push_oscwii(apps[apps.length - 1 - i]);
    }
}
