// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView, Horizontal, Icon, MaterialPalette, MaterialText, HorizontalDivider, IconButton } from "@material";
import { OscWiiApp } from "common.slint";

export component OscWiiAppList inherits ScrollView {
    in property <[OscWiiApp]> apps;

    callback open_oscwii_info(OscWiiApp);
    callback download_oscwii(OscWiiApp);
    callback push_oscwii(OscWiiApp);

    viewport_height: (4px + 18px + 4px) * apps.length + 36px;

    // Draw the horizontal separator lines
    for i in apps.length - 1: HorizontalDivider {
        x: 8px;
        y: (4px + 18px + 4px) * (i + 1) + 3px;
        width: parent.width - 16px;
    }

    Horizontal {
        Rectangle {
            horizontal-stretch: 2;

            for app[i] in apps: MaterialText {
                x: 0px;
                y: (4px + 18px + 4px) * i + 2px;
                text: app.name;
                width: parent.width;
            }
        }

        Rectangle {
            horizontal-stretch: 1;

            for i in apps.length: Icon {
                x: 0px;
                y: (4px + 18px + 4px) * i + 2px;
                height: 14px;
                width: 14px;
                source: @image-url("../mdi/account.svg");
            }

            for app[i] in apps: MaterialText {
                x: 14px + 4px;
                y: (4px + 18px + 4px) * i + 2px;
                text: app.author;
                width: parent.width - 14px - 4px;
            }
        }

        Rectangle {
            horizontal-stretch: 1;

            for i in apps.length: Icon {
                x: 0px;
                y: (4px + 18px + 4px) * i + 2px;
                height: 14px;
                width: 14px;
                source: @image-url("../mdi/tag.svg");
            }

            for app[i] in apps: MaterialText {
                x: 14px + 4px;
                y: (4px + 18px + 4px) * i + 2px;
                text: app.version;
                width: parent.width - 14px - 4px;
            }
        }

        Rectangle {
            horizontal-stretch: 1;

            for i in apps.length: Icon {
                x: 0px;
                y: (4px + 18px + 4px) * i + 2px;
                height: 14px;
                width: 14px;
                source: @image-url("../mdi/scale.svg");
            }

            for app[i] in apps: MaterialText {
                x: 14px + 4px;
                y: (4px + 18px + 4px) * i + 2px;
                text: app.size;
                width: parent.width - 14px - 4px;
            }
        }

        // We draw bottom to top to preserve the tooltips
        Rectangle {
            horizontal-stretch: 1;
            width: 18px + 4px + 18px + 4px + 18px;

            for i in apps.length: IconButton {
                x: 0px;
                y: (4px + 18px + 4px) * (apps.length - i - 1);
                height: 18px;
                width: 18px;
                icon: @image-url("../mdi/information.svg");
                tooltip: "App Information";
                inline: true;
                clicked => {
                    open_oscwii_info(apps[apps.length - i - 1]);
                }
            }

            for i in apps.length: IconButton {
                x: 18px + 4px;
                y: (4px + 18px + 4px) * (apps.length - i - 1);
                height: 18px;
                width: 18px;
                icon: @image-url("../mdi/download.svg");
                tooltip: "Download";
                inline: true;
                clicked => {
                    download_oscwii(apps[apps.length - i - 1]);
                }
            }

            for i in apps.length: IconButton {
                x: 18px + 4px + 18px + 4px;
                y: (4px + 18px + 4px) * (apps.length - i - 1);
                height: 18px;
                width: 18px;
                icon: @image-url("../mdi/upload-network.svg");
                tooltip: "Wiiload";
                inline: true;
                clicked => {
                    push_oscwii(apps[apps.length - i - 1]);
                }
            }
        }
    }
}
