// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconButton, Horizontal, Icon, MaterialPalette, MaterialText, VerticalDivider } from "@material";
import { LineEdit } from "std-widgets.slint";
import { OscWiiApp, Config, ViewAs } from "common.slint";
import { OscWiiAppGrid } from "oscwii_app_grid.slint";
import { OscWiiAppList } from "oscwii_app_list.slint";

export component OscWiiAppsPage inherits VerticalLayout {
    private property <string> filter: "";
    in-out property <Config> config;

    callback update_config();
    callback open_oscwii_info(OscWiiApp);
    callback download_oscwii(OscWiiApp);
    callback push_oscwii(OscWiiApp);

    pure callback get_apps(string) -> [OscWiiApp];

    Rectangle {
        background: MaterialPalette.surface_container;
        z: 2.0;

        Horizontal {
            VerticalLayout {
                padding-left: 4px;
                alignment: center;
                Icon {
                    source: @image-url("../mdi/magnify.svg");
                }
            }

            LineEdit {
                height: 36px;
                placeholder-text: "Search...";
                text <=> filter;
            }

            VerticalLayout {
                alignment: center;

                Rectangle {
                    border-color: MaterialPalette.outline_variant;
                    border-radius: 12px;
                    border-width: 1px;

                    Horizontal {
                        alignment: center;

                        IconButton {
                            checked: config.view-as == ViewAs.Grid;
                            icon: @image-url("../mdi/view-grid.svg");
                            tooltip: "Grid view";
                            inline: true;
                            clicked => {
                                config.view-as = ViewAs.Grid;
                                update_config();
                            }
                        }

                        IconButton {
                            checked: config.view-as == ViewAs.List;
                            icon: @image-url("../mdi/view-list.svg");
                            tooltip: "List view";
                            inline: true;
                            clicked => {
                                config.view-as = ViewAs.List;
                                update_config();
                            }
                        }
                    }
                }
            }

            VerticalDivider { }

            VerticalLayout {
                alignment: center;
                Icon {
                    source: @image-url("../mdi/upload-network.svg");
                }
            }

            MaterialText {
                vertical-alignment: center;
                text: "Wii IP:";
            }

            LineEdit {
                height: 36px;
                width: 160px;
                text: config.wii-ip;
                edited(text) => {
                    config.wii-ip = text;
                }
            }
        }
    }

    if config.view-as == ViewAs.Grid: OscWiiAppGrid {
        apps: get_apps(filter.to-lowercase());
        open_oscwii_info(app) => open_oscwii_info(app);
        download_oscwii(app) => download_oscwii(app);
        push_oscwii(app) => push_oscwii(app);
    }

    if config.view-as == ViewAs.List: OscWiiAppList {
        apps: get_apps(filter.to-lowercase());
        open_oscwii_info(app) => open_oscwii_info(app);
        download_oscwii(app) => download_oscwii(app);
        push_oscwii(app) => push_oscwii(app);
    }
}
