// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ElevatedCard, Vertical, Horizontal, IconButton, MaterialText, Dialog, HorizontalDivider, ScrollView } from "@material";
import { OscWiiApp } from "common.slint";

export component OscWiiAppCard inherits VerticalLayout {
    in property <OscWiiApp> app;
    padding: 4px;

    ElevatedCard {
        Vertical {
            MaterialText {
                horizontal-alignment: center;
                text: app.name;
                font-size: 18px;
            }

            HorizontalDivider { }

            MaterialText {
                text: app.author;
            }

            Rectangle {
                height: 30px;
            }
        }
    }
}

export component OscWiiAppCardButtons inherits Horizontal {
    alignment: center;
    height: 34px;

    callback open_oscwii_info();
    callback download_oscwii();
    callback push_oscwii();

    IconButton {
        icon: @image-url("../mdi/information.svg");
        tooltip: "App Information";
        inline: true;
        clicked => {
            open_oscwii_info();
        }
    }

    IconButton {
        icon: @image-url("../mdi/download.svg");
        tooltip: "Download";
        inline: true;
        clicked => {
            download_oscwii();
        }
    }

    IconButton {
        icon: @image-url("../mdi/upload-network.svg");
        tooltip: "Wiiload";
        inline: true;
        clicked => {
            push_oscwii();
        }
    }
}
