// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import {
    Config,
    GameList,
    EmptyResult,
    Game,
    DiscInfo,
    DriveInfo,
    QueuedConversion,
    ConfigContents,
    Notification,
    SortBy,
    HomebrewApp,
    HomebrewAppList,
} from "types.slint";

export global Rust {
    pure callback open(string) -> EmptyResult;
    pure callback pick-mount-point() -> string;
    pure callback get-drive-info(string) -> DriveInfo;
    pure callback load-config() -> Config;
    pure callback write-config(Config) -> EmptyResult;
    pure callback delete-dir(string) -> EmptyResult;
    pure callback get-game-list(string, SortBy) -> GameList;
    pure callback get-homebrew-app-list(string, SortBy) -> HomebrewAppList;
    pure callback filter-games([Game], string) -> [Game];
    pure callback filter-homebrew-apps([HomebrewApp], string) -> [HomebrewApp];
    pure callback get-disc-info(string) -> DiscInfo;
    pure callback pick-games([Game], ConfigContents, DriveInfo) -> [QueuedConversion];
    pure callback pick-games-r([Game], ConfigContents, DriveInfo) -> [QueuedConversion];
    pure callback sort-games([Game], SortBy) -> [Game];
    pure callback add-notification([Notification], Notification);
    pure callback close-notification([Notification], int);
    pure callback add-to-queue([QueuedConversion], [QueuedConversion]);
    pure callback archive-game([QueuedConversion], Game) -> EmptyResult;
    pure callback set-window-color(bool);
    pure callback scrub-game([QueuedConversion], Game) -> EmptyResult;
}
