// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import {
    ViewAs,
    SortBy,
    QueuedConversion,
    WiiOutputFormat,
    GcOutputFormat,
    TxtCodesSource,
    ThemePreference,
    Game,
    HomebrewApp,
    Config,
} from "types.slint";

export global Rust {
    callback filter-games(string);
    callback filter-homebrew-apps(string);
    callback filter-osc-apps(string);
    callback load-osc-apps(bool) -> { h: int, min: int};
    callback set-config(Config);
    callback pick-mount-point() -> Config;
    callback refresh-all();
    callback confirm-conversions();
    callback cancel-conversions();
    callback clear-crc32-status();
    callback archive-game(Game);
    callback scrub-game(Game);
    callback delete-game(Game);
    callback delete-homebrew-app(HomebrewApp);
    callback pick-games(bool);
    callback open-that(string);
    callback close-notification(int);
    callback pick-homebrew-apps();
    callback force-osc-refresh();
    callback checksum(Game);
    callback set-window-color(bool);
}
