// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Vertical, RadioButton, Horizontal, HorizontalDivider, MaterialText } from "@material";

export component SettingsPage inherits Vertical {
    alignment: start;

    MaterialText {
        text: "Wii Output Format";
        font-size: 20px;
    }

    Horizontal {
        alignment: start;
        spacing: 16px;

        RadioButton {
            height: 14px;
            width: 14px;
        }

        MaterialText {
            text: "WBFS Auto Split (recommended)";
        }
    }

    Horizontal {
        alignment: start;
        spacing: 16px;

        RadioButton {
            height: 14px;
            width: 14px;
        }

        MaterialText {
            text: "WBFS Fixed 4GB-32KB Split Size";
        }
    }

    Horizontal {
        alignment: start;
        spacing: 16px;

        RadioButton {
            height: 14px;
            width: 14px;
        }

        MaterialText {
            text: "WBFS Fixed 4GB-64KB Split Size";
        }
    }

    HorizontalDivider { }

    MaterialText {
        text: "Remove Update Partition on WBFS (experimental)";
        font-size: 20px;
    }

    Horizontal {
        alignment: start;
        spacing: 16px;

        RadioButton {
            height: 14px;
            width: 14px;
        }

        MaterialText {
            text: "No (recommended)";
        }
    }

    Horizontal {
        alignment: start;
        spacing: 16px;

        RadioButton {
            height: 14px;
            width: 14px;
        }

        MaterialText {
            text: "Yes (integrity check won't work)";
        }
    }

    HorizontalDivider { }

    MaterialText {
        text: "Archive Format";
        font-size: 20px;
    }

    Horizontal {
        alignment: start;
        spacing: 16px;

        RadioButton {
            height: 14px;
            width: 14px;
        }

        MaterialText {
            text: "RVZ zstd-19 (recommended)";
        }
    }

    Horizontal {
        alignment: start;
        spacing: 16px;

        RadioButton {
            height: 14px;
            width: 14px;
        }

        MaterialText {
            text: "ISO (very large)";
        }
    }
}
