// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView } from "std-widgets.slint";
import { IconSet, IconDisplay } from "@lucide";
import { State } from "state.slint";
import { Setting } from "components/setting.slint";
import { BoolSetting } from "components/bool-setting.slint";
import { MyPalette } from "styling.slint";

export component SettingsPage inherits Rectangle {
    HorizontalLayout {
        x: 10px;
        y: 20px;
        spacing: 5px;

        IconDisplay {
            icon: IconSet.ChevronRight;
            size: 18px;
            stroke: MyPalette.foreground;
        }

        Text {
            text: "Settings";
            font-size: 18px;
        }
    }

    ScrollView {
        x: 0px;
        y: 38px + 20px;
        height: root.height - 38px - 20px;

        VerticalLayout {
            width: 100%;
            padding-left: 10px;
            padding-right: 15px;
            padding-bottom: 10px;
            spacing: 10px;

            Setting {
                icon: IconSet.Disc3;
                label: "Wii output format";
                items: [
                    { value: "wbfs", label: "WBFS (recommended)" },
                    { value: "iso", label: "ISO (very large)" },
                ];
                active-value <=> State.config.contents.wii-output-format;
            }

            Setting {
                icon: IconSet.Disc3;
                label: "GameCube output format";
                items: [
                    { value: "iso", label: "ISO (recommended)" },
                    {
                        value: "ciso",
                        label: "CISO (much smaller, slightly slower, less metadata in game loaders)"
                    },
                ];
                active-value <=> State.config.contents.gc-output-format;
            }

            BoolSetting {
                icon: IconSet.SquareSplitHorizontal;
                label: "Split output";
                items: [
                    { value: false, label: "Only when needed (recommended)" },
                    { value: true, label: "Always 4GB-32KB" },
                ];
                active-value <=> State.config.contents.always-split;
            }

            BoolSetting {
                icon: IconSet.FileMinusCorner;
                label: "Remove update partition on WBFS/CISO";
                items: [
                    { value: false, label: "No (recommended)" },
                    {
                        value: true,
                        label: "Yes (saves some space; update partition is zeroed, but still there)"
                    },
                ];
                active-value <=> State.config.contents.scrub-update-partition;
            }

            BoolSetting {
                icon: IconSet.Trash;
                label: "Delete sources when adding games";
                items: [
                    { value: false, label: "No (recommended)" },
                    { value: true, label: "Yes" },
                ];
                active-value <=> State.config.contents.remove-sources-games;
            }

            BoolSetting {
                icon: IconSet.Trash;
                label: "Delete sources when adding apps";
                items: [
                    { value: false, label: "No (recommended)" },
                    { value: true, label: "Yes" },
                ];
                active-value <=> State.config.contents.remove-sources-apps;
            }

            Setting {
                icon: IconSet.Skull;
                label: "Cheat codes source";
                items: [
                    { value: "web-archive", label: "geckocodes.org-201909 archive (recommended)" },
                    { value: "game-hacking", label: "gamehacking.org (up to date)" },
                    { value: "rc24", label: "codes.rc24.xyz" },
                ];
                active-value <=> State.config.contents.txt-codes-source;
            }

            Setting {
                icon: IconSet.SunMoon;
                label: "Theme";
                items: [
                    { value: "system", label: "System (requires restart)" },
                    { value: "light", label: "Light" },
                    { value: "dark", label: "Dark" },
                ];
                active-value <=> State.config.contents.theme-preference;

                changed active-value => {
                    State.apply-theme();
                }
            }
        }
    }
}
