// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView, Palette } from "std-widgets.slint";
import { IconSet, IconDisplay } from "@lucide";
import { SettingCard } from "components/setting-card.slint";
import { MyPalette } from "styling.slint";
import { Logic } from "logic.slint";

export component SettingsPage inherits VerticalLayout {
    HorizontalLayout {
        height: 48px;
        padding-top: 20px;
        padding-left: 10px;
        spacing: 5px;

        IconDisplay {
            icon: IconSet.ChevronRight;
            size: 18px;
            stroke: MyPalette.foreground;
        }

        Text {
            text: "Settings";
            font-size: 18px;
        }
    }

    ScrollView {
        VerticalLayout {
            width: 100%;
            padding: 10px;
            padding-right: 15px;
            spacing: 10px;
            alignment: start;

            SettingCard {
                icon: IconSet.Disc3;
                label: "Wii output format";
                items: ["WBFS (recommended)", "ISO (very large)"];
                active-item: Logic.config.wii-output-format;

                selected(i) => Logic.set-wii-output-format(i);
            }

            SettingCard {
                icon: IconSet.Disc3;
                label: "GameCube output format";
                items: [
                    "ISO (recommended)",
                    "CISO (much smaller, slightly slower, less metadata in game loaders)"
                ];
                active-item: Logic.config.gc-output-format;

                selected(i) => Logic.set-gc-output-format(i);
            }

            SettingCard {
                icon: IconSet.SquareSplitHorizontal;
                label: "Split output";
                items: ["Only when needed (recommended)", "Always 4GB-32KB"];
                active-item: Logic.config.always-split ? 1 : 0;

                selected(i) => Logic.set-always-split(i == 1);
            }

            SettingCard {
                icon: IconSet.FileMinusCorner;
                label: "Remove update partition on WBFS/CISO";
                items: [
                    "No (recommended)",
                    "Yes (saves some space; update partition is zeroed, but still there)"
                ];
                active-item: Logic.config.scrub-update-partition ? 1 : 0;

                selected(i) => Logic.set-scrub-update-partition(i == 1);
            }

            SettingCard {
                icon: IconSet.Trash;
                label: "Delete sources when adding games";
                items: ["No (recommended)", "Yes"];
                active-item: Logic.config.remove-sources-games ? 1 : 0;

                selected(i) => Logic.set-remove-sources-games(i == 1);
            }

            SettingCard {
                icon: IconSet.Trash;
                label: "Delete sources when adding apps";
                items: ["No (recommended)", "Yes"];
                active-item: Logic.config.remove-sources-apps ? 1 : 0;

                selected(i) => Logic.set-remove-sources-apps(i == 1);
            }

            SettingCard {
                icon: IconSet.Skull;
                label: "Cheat codes source";
                items: [
                    "geckocodes.org-201909 archive (recommended)",
                    "gamehacking.org (up to date)",
                    "codes.rc24.xyz",
                ];
                active-item: Logic.config.txt-codes-source;

                selected(i) => Logic.set-txt-codes-source(i);
            }

            SettingCard {
                icon: IconSet.SunMoon;
                label: "Theme";
                items: ["System (requires restart)", "Light", "Dark"];
                active-item: Logic.config.theme-preference;

                selected(i) => {
                    Logic.set-theme-preference(i);

                    if i == 1 {
                        Palette.color-scheme = ColorScheme.light;
                        Logic.set-window-color(false);
                    } else if i == 2 {
                        Palette.color-scheme = ColorScheme.dark;
                        Logic.set-window-color(true);
                    }
                }
            }
        }
    }
}
