// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView, Palette } from "std-widgets.slint";
import { IconSet, IconDisplay } from "@lucide";
import { SettingCard } from "components/setting-card.slint";
import { MyPalette } from "styling.slint";
import { Logic } from "logic.slint";
import { Action } from "types.slint";

export component SettingsPage inherits VerticalLayout {
    HorizontalLayout {
        height: 58px;
        padding: 20px;
        padding-left: 10px;
        spacing: 5px;

        IconDisplay {
            icon: IconSet.ChevronRight;
            size: 18px;
            stroke: MyPalette.foreground;
        }

        Text {
            text: "Settings";
            font-size: 18px;
        }
    }

    ScrollView {
        VerticalLayout {
            width: 100%;
            padding: 10px;
            padding-top: 0px;
            spacing: 10px;
            alignment: start;

            SettingCard {
                icon: IconSet.Disc3;
                label: "Wii output format";
                items: [
                    { value: "Wbfs", label: "WBFS (recommended)" },
                    { value: "Iso", label: "ISO (very large)" }
                ];
                active-item: Logic.config.wii-output-format;
                set-property: Action.SetWiiOutputFormat;
            }

            SettingCard {
                icon: IconSet.Disc3;
                label: "GameCube output format";
                items: [
                    { value: "Iso", label: "ISO (recommended)" },
                    {
                        value: "Ciso",
                        label: "CISO (much smaller, slightly slower, less metadata in game loaders)"
                    }
                ];
                active-item: Logic.config.gc-output-format;
                set-property: Action.SetGcOutputFormat;
            }

            SettingCard {
                icon: IconSet.SquareSplitHorizontal;
                label: "Split output";
                items: [
                    { value: "false", label: "Only when needed (recommended)" },
                    { value: "true", label: "Always 4GB-32KB" }
                ];
                active-item: Logic.config.always-split;
                set-property: Action.SetAlwaysSplit;
            }

            SettingCard {
                icon: IconSet.FileMinusCorner;
                label: "Remove update partition on WBFS/CISO";
                items: [
                    { value: "false", label: "No (recommended)" },
                    {
                        value: "true",
                        label: "Yes (saves some space; update partition is zeroed, but still there)"
                    }
                ];
                active-item: Logic.config.scrub-update-partition;
                set-property: Action.SetScrubUpdatePartition;
            }

            SettingCard {
                icon: IconSet.Trash;
                label: "Delete sources when adding games";
                items: [{ value: "false", label: "No (recommended)" }, { value: "true", label: "Yes" }];
                active-item: Logic.config.remove-sources-games;
                set-property: Action.SetRemoveSourcesGames;
            }

            SettingCard {
                icon: IconSet.Trash;
                label: "Delete sources when adding apps";
                items: [{ value: "false", label: "No (recommended)" }, { value: "true", label: "Yes" }];
                active-item: Logic.config.remove-sources-apps;
                set-property: Action.SetRemoveSourcesApps;
            }

            SettingCard {
                icon: IconSet.Skull;
                label: "Cheat codes source";
                items: [
                    { value: "WebArchive", label: "geckocodes.org-201909 archive (recommended)" },
                    { value: "GameHacking", label: "gamehacking.org (up to date)" },
                    { value: "Rc24", label: "codes.rc24.xyz" }
                ];
                active-item: Logic.config.txt-codes-source;
                set-property: Action.SetTxtCodesSource;
            }

            SettingCard {
                icon: IconSet.SunMoon;
                label: "Theme";
                items: [
                    { value: "System", label: "System (requires restart)" },
                    { value: "Light", label: "Light" },
                    { value: "Dark", label: "Dark" }
                ];
                active-item: Logic.config.theme-preference;
                set-property: Action.SetThemePreference;

                changed() => {
                    if Logic.config.theme-preference == "Light" {
                        Palette.color-scheme = ColorScheme.light;
                        Logic.dispatch(Action.SetWindowColor, "false")
                    } else if Logic.config.theme-preference == "Dark" {
                        Palette.color-scheme = ColorScheme.dark;
                        Logic.dispatch(Action.SetWindowColor, "true")
                    }
                }
            }

            SettingCard {
                icon: IconSet.ImageDown;
                label: "Preferred language for PAL covers";
                items: [
                    { value: "English", label: "English" },
                    { value: "French", label: "French" },
                    { value: "German", label: "German" },
                    { value: "Spanish", label: "Spanish" },
                    { value: "Italian", label: "Italian" },
                    { value: "Dutch", label: "Dutch" },
                    { value: "Portuguese", label: "Portuguese" },
                    { value: "Swedish", label: "Swedish" },
                    { value: "Danish", label: "Danish" },
                    { value: "Finnish", label: "Finnish" }
                ];
                active-item: Logic.config.preferred-language;
                set-property: Action.SetPreferredLanguage;
            }
        }
    }
}
