// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { VerticalBox, ScrollView } from "std-widgets.slint";
import { IconSet } from "@lucide";
import { State } from "state.slint";
import { Setting } from "components/setting.slint";
import { BoolSetting } from "components/bool_setting.slint";

export component SettingsPage inherits VerticalLayout {
    alignment: start;

    VerticalBox {
        Text {
            text: "Settings";
            font-size: 18px;
            font-weight: 700;
        }
    }

    ScrollView {
        height: parent.height - 40px;

        VerticalBox {
            padding-top: 0px;
            padding-right: 20px;
            height: 100%;

            Setting {
                icon: IconSet.Disc3;
                label: "Wii output format";
                items: [
                    { value: "wbfs", label: "WBFS (recommended)" },
                    { value: "iso", label: "ISO (very large)" },
                ];
                active_value <=> State.config.contents.wii_output_format;
            }

            Setting {
                icon: IconSet.Disc3;
                label: "GameCube output format";
                items: [
                    { value: "iso", label: "ISO (recommended)" },
                    {
                        value: "ciso",
                        label: "CISO (much smaller, slightly slower, less metadata in game loaders)"
                    },
                ];
                active_value <=> State.config.contents.gc_output_format;
            }

            BoolSetting {
                icon: IconSet.SquareSplitHorizontal;
                label: "Split output";
                items: [
                    { value: false, label: "Only when needed (recommended)" },
                    { value: true, label: "Always 4GB-32KB" },
                ];
                active_value <=> State.config.contents.always_split;
            }

            BoolSetting {
                icon: IconSet.FileMinusCorner;
                label: "Remove update partition on WBFS/CISO";
                items: [
                    { value: false, label: "No (recommended)" },
                    {
                        value: true,
                        label: "Yes (saves some space; update partition is zeroed, but still there)"
                    },
                ];
                active_value <=> State.config.contents.scrub_update_partition;
            }

            BoolSetting {
                icon: IconSet.Trash;
                label: "Delete sources when adding games";
                items: [
                    { value: false, label: "No (recommended)" },
                    { value: true, label: "Yes" },
                ];
                active_value <=> State.config.contents.remove_sources_games;
            }

            BoolSetting {
                icon: IconSet.Trash;
                label: "Delete sources when adding apps";
                items: [
                    { value: false, label: "No (recommended)" },
                    { value: true, label: "Yes" },
                ];
                active_value <=> State.config.contents.remove_sources_apps;
            }

            Setting {
                icon: IconSet.Skull;
                label: "Cheat codes source";
                items: [
                    { value: "web_archive", label: "geckocodes.org_201909 archive (recommended)" },
                    { value: "game_hacking", label: "gamehacking.org (up to date)" },
                    { value: "rc24", label: "codes.rc24.xyz" },
                ];
                active_value <=> State.config.contents.txt_codes_source;
            }
        }
    }
}
