// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Vertical, RadioButton, Horizontal, HorizontalDivider, MaterialText, ElevatedButton, Icon, ScrollView, ElevatedCard, FilledIconButton } from "@material";
import { Config, WiiOutputFormat, ArchiveFormat } from "common.slint";

export component SettingsPage inherits Vertical {
    in-out property <Config> config;

    callback update_config();
    callback open_data_dir();

    ElevatedCard {
        ScrollView {
            vertical_scrollbar_policy: ScrollBarPolicy.always-on;

            Vertical {
                Horizontal {
                    alignment: start;
                    padding-left: 6px;

                    Icon {
                        source: @image-url("../mdi/package-up.svg");
                    }

                    MaterialText {
                        text: "Wii Output Format";
                        font-size: 18px;
                    }
                }

                Horizontal {
                    alignment: start;
                    spacing: 16px;

                    RadioButton {
                        height: 14px;
                        width: 14px;
                        checked: config.wii-output-format == WiiOutputFormat.Wbfs;
                        clicked => {
                            config.wii-output-format = WiiOutputFormat.Wbfs;
                            update_config();
                        }
                    }

                    MaterialText {
                        text: "WBFS (recommended)";
                    }
                }

                Horizontal {
                    alignment: start;
                    spacing: 16px;

                    RadioButton {
                        height: 14px;
                        width: 14px;
                        checked: config.wii-output-format == WiiOutputFormat.Iso;
                        clicked => {
                            config.wii-output-format = WiiOutputFormat.Iso;
                            update_config();
                        }
                    }

                    MaterialText {
                        text: "ISO (very large)";
                    }
                }

                HorizontalDivider { }

                Horizontal {
                    alignment: start;
                    padding-left: 6px;

                    Icon {
                        source: @image-url("../mdi/format-page-split.svg");
                    }

                    MaterialText {
                        text: "Split Output";
                        font-size: 18px;
                    }
                }

                Horizontal {
                    alignment: start;
                    spacing: 16px;

                    RadioButton {
                        height: 14px;
                        width: 14px;
                        checked: !config.always-split;
                        clicked => {
                            config.always-split = false;
                            update_config();
                        }
                    }

                    MaterialText {
                        text: "Only when needed (recommended)";
                    }
                }

                Horizontal {
                    alignment: start;
                    spacing: 16px;

                    RadioButton {
                        height: 14px;
                        width: 14px;
                        checked: config.always-split;
                        clicked => {
                            config.always-split = true;
                            update_config();
                        }
                    }

                    MaterialText {
                        text: "Always 4GB-32KB";
                    }
                }

                HorizontalDivider { }

                Horizontal {
                    alignment: start;
                    padding-left: 6px;

                    Icon {
                        source: @image-url("../mdi/trash-can.svg");
                    }

                    MaterialText {
                        text: "Remove Update Partition on WBFS (experimental)";
                        font-size: 18px;
                    }
                }

                Horizontal {
                    alignment: start;
                    spacing: 16px;

                    RadioButton {
                        height: 14px;
                        width: 14px;
                        checked: !config.scrub-update-partition;
                        clicked => {
                            config.scrub-update-partition = false;
                            update_config();
                        }
                    }

                    MaterialText {
                        text: "No (recommended)";
                    }
                }

                Horizontal {
                    alignment: start;
                    spacing: 16px;

                    RadioButton {
                        height: 14px;
                        width: 14px;
                        checked: config.scrub-update-partition;
                        clicked => {
                            config.scrub-update-partition = true;
                            update_config();
                        }
                    }

                    MaterialText {
                        text: "Yes (integrity check won't work)";
                    }
                }

                HorizontalDivider { }

                Horizontal {
                    alignment: start;
                    padding-left: 6px;

                    Icon {
                        source: @image-url("../mdi/package-down.svg");
                    }

                    MaterialText {
                        text: "Archive Format";
                        font-size: 18px;
                    }
                }

                Horizontal {
                    alignment: start;
                    spacing: 16px;

                    RadioButton {
                        height: 14px;
                        width: 14px;
                        checked: config.archive-format == ArchiveFormat.Rvz;
                        clicked => {
                            config.archive-format = ArchiveFormat.Rvz;
                            update_config();
                        }
                    }

                    MaterialText {
                        text: "RVZ zstd-19 (recommended)";
                    }
                }

                Horizontal {
                    alignment: start;
                    spacing: 16px;

                    RadioButton {
                        height: 14px;
                        width: 14px;
                        checked: config.archive-format == ArchiveFormat.Iso;
                        clicked => {
                            config.archive-format = ArchiveFormat.Iso;
                            update_config();
                        }
                    }

                    MaterialText {
                        text: "ISO (very large)";
                    }
                }

                HorizontalDivider { }

                Horizontal {
                    alignment: start;
                    padding-left: 6px;

                    Icon {
                        source: @image-url("../mdi/bomb.svg");
                    }

                    MaterialText {
                        text: "Remove sources when adding games";
                        font-size: 18px;
                    }
                }

                Horizontal {
                    alignment: start;
                    spacing: 16px;

                    RadioButton {
                        height: 14px;
                        width: 14px;
                        checked: !config.remove-sources-games;
                        clicked => {
                            config.remove-sources-games = false;
                            update_config();
                        }
                    }

                    MaterialText {
                        text: "No (recommended)";
                    }
                }

                Horizontal {
                    alignment: start;
                    spacing: 16px;

                    RadioButton {
                        height: 14px;
                        width: 14px;
                        checked: config.remove-sources-games;
                        clicked => {
                            config.remove-sources-games = true;
                            update_config();
                        }
                    }

                    MaterialText {
                        text: "Yes (source files will be lost!)";
                    }
                }

                HorizontalDivider { }

                Horizontal {
                    alignment: start;
                    padding-left: 6px;

                    Icon {
                        source: @image-url("../mdi/bomb.svg");
                    }

                    MaterialText {
                        text: "Remove sources when adding apps";
                        font-size: 18px;
                    }
                }

                Horizontal {
                    alignment: start;
                    spacing: 16px;

                    RadioButton {
                        height: 14px;
                        width: 14px;
                        checked: !config.remove-sources-apps;
                        clicked => {
                            config.remove-sources-apps = false;
                            update_config();
                        }
                    }

                    MaterialText {
                        text: "No (recommended)";
                    }
                }

                Horizontal {
                    alignment: start;
                    spacing: 16px;

                    RadioButton {
                        height: 14px;
                        width: 14px;
                        checked: config.remove-sources-apps;
                        clicked => {
                            config.remove-sources-apps = true;
                            update_config();
                        }
                    }

                    MaterialText {
                        text: "Yes (source files will be lost!)";
                    }
                }
            }
        }
    }

    Horizontal {
        alignment: end;

        ElevatedButton {
            text: "Open Data Directory";
            icon: @image-url("../mdi/folder-open.svg");
            clicked => open_data_dir();
        }
    }
}
