// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { VerticalBox } from "std-widgets.slint";
import { Card } from "components/card.slint";
import { Radio } from "components/radio.slint";
import { IconSet } from "@lucide";
import { State } from "state.slint";


export component SettingsPage inherits VerticalBox {
    alignment: start;

    Text {
        text: "Settings";
        font-size: 18px;
        font-weight: 700;
    }

    Card {
        width: 100%;

        Radio {
            height: 100%;

            icon: IconSet.Disc3;
            label: "Wii output format";
            items: [
                { value: "wbfs", label: "WBFS (recommended)" },
                { value: "iso", label: "ISO (very large)" },
            ];
            active_value <=> State.config.contents.wii_output_format;
            changed => State.write_config();
        }
    }
}
