// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { NavigationRail, MaterialPalette, Vertical, TonalIconButton, IconButton, ToolTip, PopupMenu } from "@material";
import { UpdateInfo } from "common.slint";

export component SideBar inherits VerticalLayout {
    in-out property <int> current_index: 0;
    in property <bool> is_macos: false;
    in property <int> game_count: 0;
    in property <int> app_count: 0;
    in property <UpdateInfo> update_info;

    callback set_window_title(string);
    callback choose_mount_point();
    callback open_url(string);
    callback dot_clean();
    callback download_wiitdb();
    callback download_all_covers();

    padding-top: -44px + 12px; // 44px is NavigationRail top padding

    NavigationRail {
        width: 80px;
        alignment: start;
        current-index <=> current_index;

        items: [
            { icon: @image-url("../mdi/controller.svg"), text: "Games" },
            { icon: @image-url("../mdi/star.svg"), text: "Apps" },
            { icon: @image-url("../mdi/storefront.svg"), text: "OSCWii" },
            { icon: @image-url("../mdi/cog.svg"), text: "Settings" }
        ];

        index-changed(i) => {
            if i == 0 {
                set_window_title(" • " + game_count + " Games");
            }
            if i == 1 {
                set_window_title(" • " + app_count + " Apps");
            }
            if i == 2 {
                set_window_title(" • OSCWii");
            }
            if i == 3 {
                set_window_title(" • Settings");
            }
        }
    }

    Rectangle {
        width: 80px;
        background: MaterialPalette.surface;

        Vertical {
            padding-bottom: 16px;

            if !update_info.version.is-empty: IconButton {
                z: 2.0;
                icon: @image-url("../mdi/bell-plus.svg");
                tooltip: "Update\navailable!\nv" + update_info.version;
                clicked => {
                    open_url(update_info.url);
                }
            }

            IconButton {
                icon: @image-url("../mdi/information.svg");
                z: 1.9;
                tooltip: "Wiki";
                clicked => {
                    open_url("https://github.com/mq1/TinyWiiBackupManager/wiki");
                }
            }

            menu_button := IconButton {
                icon: @image-url("../mdi/menu.svg");
                clicked => {
                    menu.show();
                }
            }

            menu := PopupMenu {
                x: menu_button.x + menu_button.width;
                y: menu_button.y;
                width: 250px;
                items: [
                    {
                        icon: @image-url("../mdi/harddisk.svg"),
                        text: "Choose Drive/Directory",
                        enabled: true,
                    },
                    {
                        icon: @image-url("../mdi/file-download.svg"),
                        text: "Download wiitdb.xml",
                        enabled: true,
                    },
                    {
                        icon: @image-url("../mdi/image-multiple.svg"),
                        text: "Download all Covers",
                        enabled: true,
                    },
                    {
                        icon: @image-url("../mdi/ghost.svg"),
                        text: "dot_clean (macOS only)",
                        enabled: is_macos,
                    }
                ];
                activated(i) => {
                    if i == 0 {
                        choose_mount_point();
                    }
                    if i == 1 {
                        download_wiitdb();
                    }
                    if i == 2 {
                        download_all_covers();
                    }
                    if i == 3 {
                        dot_clean();
                    }
                    self.close();
                }
            }
        }
    }
}
