// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import {
    Page,
    Config,
    Message,
    IconButtonKind,
    GameList,
    MessageKind,
    Game,
    DiscInfoResult,
    DriveInfo,
    QueuedConversion,
    Notification,
} from "types.slint";
import { Rust } from "rust.slint";
import { MyPalette } from "styling.slint";
import { Palette } from "std-widgets.slint";
import { IconSet } from "@lucide";

export global State {
    in property <string> version;
    in-out property <Page> current-page;
    in-out property <Game> current-game;
    in-out property <DiscInfoResult> current-disc-info;
    in property <string> data-dir;
    in-out property <Config> config;
    in-out property <Message> message;
    in-out property <DriveInfo> drive-info;
    in-out property <GameList> game-list;
    in-out property <[Game]> filtered-games;
    in-out property <string> game-filter;
    in property <string> status;
    in property <{text: string, mouse-x: length, mouse-y: length}> tooltip;
    in-out property <[QueuedConversion]> conversion-queue;
    in-out property <bool> is-converting;
    in-out property <string> deleting-dir;
    in-out property <[QueuedConversion]> adding-games;
    in-out property <[Notification]> notifications;

    // ↑ Model
    // ---------
    // ↓ Update

    callback close-notification(int);
    callback apply-sorting();
    callback add-to-queue();

    public function info(info: string) {
        if !info.is-empty {
            message.text = info;
            message.kind = MessageKind.Info;
        }
    }

    public function err(err: string) {
        if !err.is-empty {
            message.text = err;
            message.kind = MessageKind.Error;
        }
    }

    public function dismiss() {
        message.text = "";
    }

    public function write-config() {
        let res = Rust.write-config(config);
        err(res.err);
    }

    public function filter-games() {
        if game-filter.is-empty {
            filtered-games = [];
        } else {
            filtered-games = Rust.filter-games(game-list.games, game-filter);
        }
    }

    public function toggle-dark-mode() {
        Palette.color-scheme = Palette.color-scheme == ColorScheme.dark ? ColorScheme.light : ColorScheme.dark;
    }

    public function refresh-all() {
        drive-info = Rust.get-drive-info(config.contents.mount-point);
        game-list = Rust.get-game-list(config.contents.mount-point, config.contents.sort-by);
        filtered-games = [];
    }

    public function pick-mount-point() {
        let path = Rust.pick-mount-point();
        if !path.is-empty {
            config.contents.mount-point = path;
            write-config();
            refresh-all();
        }
    }

    public function delete-dir() {
        dismiss();
        let res = Rust.delete-dir(deleting-dir);
        err(res.err);
        refresh-all();
    }

    public function open-game-info(game: Game) {
        current-page = Page.Game;
        current-game = game;
        current-disc-info = Rust.get-disc-info(current-game.path);
    }

    public function pick-games() {
        let res = Rust.pick-games(game-list, config.contents, drive-info);
        if res.a.length > 0 {
            message.text = "Picked " + res.a.length + " games, are you sure you want to continue?\n\n" + res.b;
            message.kind = MessageKind.GamesPicked;
            adding-games = res.a;
        }
    }

    public function conversion-confirmed() {
        if !is-converting {
            Rust.start-conversion(conversion-queue);
        }
    }
}
