// SPDX-FileCopyrightText: 2025 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Horizontal, CircularProgressIndicator, MaterialText, MaterialPalette, VerticalDivider } from "@material";
import { TaskType } from "common.slint";

export component Status inherits Rectangle {
    background: MaterialPalette.surface;

    in property <string> status;
    in property <TaskType> task_type: TaskType.Unknown;

    pure callback get_tasks_count() -> int;

    function tasks_count_str() -> string {
        let count = get_tasks_count();
        return count == 1 ? "1 task" : count + " tasks";
    }

    Horizontal {
        alignment: start;

        CircularProgressIndicator {
            indeterminate: true;
            height: 14px;
            width: 14px;
        }

        MaterialText {
            text: tasks_count_str() + " in queue";
        }

        VerticalDivider { }

        if task_type == TaskType.Converting: Image {
            source: @image-url("../mdi/package-up.svg");
            colorize: MaterialPalette.on_background;
            height: 14px;
            width: 14px;
        }

        MaterialText {
            text: status;
        }
    }
}
