// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import {
    Page,
    Config,
    IconButtonKind,
    GameList,
    Game,
    DriveInfo,
    DiscInfo,
    QueuedConversion,
    Notification,
} from "types.slint";
import { Rust } from "rust.slint";
import { MyPalette } from "styling.slint";
import { Palette } from "std-widgets.slint";
import { IconSet } from "@lucide";

export global State {
    in property <string> version;
    in-out property <Page> current-page;
    in-out property <Game> current-game;
    in-out property <DiscInfo> current-disc-info;
    in property <string> data-dir;
    in-out property <Config> config;
    in-out property <DriveInfo> drive-info;
    in-out property <GameList> game-list;
    in-out property <[Game]> filtered-games;
    in-out property <string> game-filter;
    in property <string> status;
    in property <{text: string, mouse-x: length, mouse-y: length}> tooltip;
    in-out property <[QueuedConversion]> conversion-queue;
    in-out property <bool> is-converting;
    in-out property <string> deleting-dir;
    in-out property <[QueuedConversion]> adding-games;
    in-out property <[Notification]> notifications;

    // ↑ Model
    // ---------
    // ↓ Update

    callback start-conversion();

    public function notify(notification: Notification) {
        Rust.add-notification(notifications, notification);
    }

    public function write-config() {
        let res = Rust.write-config(config);
        if !res.err.is-empty {
            notify({ text: res.err, critical: true });
        }
    }

    public function filter-games() {
        if game-filter.is-empty {
            filtered-games = [];
        } else {
            filtered-games = Rust.filter-games(game-list.games, game-filter);
        }
    }

    public function apply-theme() {
        if config.contents.theme-preference == "light" {
            Palette.color-scheme = ColorScheme.light;
        } else if config.contents.theme-preference == "dark" {
            Palette.color-scheme = ColorScheme.dark;
        }
    }

    public function apply-sorting() {
        game-list.games = Rust.sort-games(game-list.games, config.contents.sort-by);
    }

    public function refresh-all() {
        drive-info = Rust.get-drive-info(config.contents.mount-point);
        game-list = Rust.get-game-list(config.contents.mount-point, config.contents.sort-by);
        apply-sorting();
        filtered-games = [];
    }

    public function pick-mount-point() {
        let path = Rust.pick-mount-point();
        if !path.is-empty {
            config.contents.mount-point = path;
            write-config();
            refresh-all();
        }
    }

    public function delete-dir() {
        let res = Rust.delete-dir(deleting-dir);
        if !res.err.is-empty {
            notify({ text: res.err, critical: true });
        }
        refresh-all();
        deleting-dir = "";
    }

    public function open-game-info(game: Game) {
        current-page = Page.Game;
        current-game = game;
        current-disc-info = Rust.get-disc-info(current-game.path);
    }

    public function pick-games() {
        adding-games = Rust.pick-games(game-list.games, config.contents, drive-info);
    }

    public function pick-games-r() {
        adding-games = Rust.pick-games-r(game-list.games, config.contents, drive-info);
    }

    public function close-notification(i: int) {
        Rust.close-notification(notifications, i);
    }

    public function add-to-queue() {
        Rust.add-to-queue(conversion-queue, adding-games);
    }
}
