// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Palette } from "std-widgets.slint";

export global Styles {
    public pure function card-bg() -> color {
        if Platform.os == OperatingSystemType.macos {
            if Palette.color-scheme == ColorScheme.light {
                #ffffff
            } else {
                #1e1e1e
            }
        } else {
            Palette.alternate-background
        }
    }
}
