// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Palette } from "std-widgets.slint";

export global MyPalette {
    out property <brush> background: Palette.background;
    out property <brush> foreground: Palette.foreground;
    out property <brush> card-background: Palette.color-scheme == ColorScheme.light ? #ffffff : #1e1e1e;
    out property <brush> alternate-background: Palette.alternate-background;
    out property <brush> border: Palette.border.transparentize(-0.5);
    out property <brush> selection-background: Palette.selection-background;
    out property <brush> accent-background: Palette.accent-background;
    out property <brush> accent-foreground: Palette.accent-foreground;

    out property <brush> primary-hover: Palette.color-scheme == ColorScheme.light ? Palette.accent-background.darker(0.1) : Palette.accent-background.brighter(0.2);
    out property <brush> secondary-hover: Palette.color-scheme == ColorScheme.light ? Palette.alternate-background.darker(0.1) : Palette.alternate-background.brighter(0.2);
    out property <brush> warning-background: Colors.yellow;
    out property <brush> warning-hover: Palette.color-scheme == ColorScheme.light ? Colors.yellow.darker(0.1) : Colors.yellow.brighter(0.2);
    out property <brush> danger-background: Colors.red;
    out property <brush> danger-hover: Palette.color-scheme == ColorScheme.light ? Colors.red.darker(0.1) : Colors.red.brighter(0.2);
}
