// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconSet, IconDisplay } from "@lucide";
import { ScrollView, LineEdit } from "std-widgets.slint";
import { MyPalette } from "styling.slint";
import { Card } from "components/card.slint";
import { HorizontalLine } from "components/horizontal-line.slint";
import { Logic } from "logic.slint";
import { Link } from "components/link.slint";
import { IconButton } from "components/icon-button.slint";

export component ToolboxPage inherits VerticalLayout {
    in-out property <bool> scrubbing-all-games;

    private property <int> optimal-allocation-granularity: (Logic.drive-info.total-gib <= 32 * 1024 * 1024 * 1024) ? 32768 : 65536;
    private property <bool> is-optimal-allocation-granularity: Logic.drive-info.allocation-granularity == optimal-allocation-granularity;
    private property <bool> should-reformat: Logic.drive-info.fs-kind != "FAT32" || !is-optimal-allocation-granularity;
    private property <string> allocation-granularity-comment: is-optimal-allocation-granularity ? "✓ optimal" : "⚠ not optimal, but should work";

    pure function fs-comment(fs-kind: string) -> string {
        if fs-kind == "FAT32" {
            "✓ optimal choice for game backups and homebrew apps"
        } else if fs-kind == "NTFS" || fs-kind == "exFAT" {
            "⚠ limited support for game backups and homebrew apps"
        } else {
            "⚠ won't work for game backups and homebrew apps"
        }
    }

    HorizontalLayout {
        height: 58px;
        padding: 20px;
        padding-left: 10px;
        spacing: 5px;

        IconDisplay {
            icon: IconSet.ChevronRight;
            size: 18px;
            stroke: MyPalette.foreground;
        }

        Text {
            text: "Toolbox";
            font-size: 18px;
        }
    }

    ScrollView {
        VerticalLayout {
            width: 100%;
            padding: 10px;
            padding-top: 0px;
            spacing: 10px;
            alignment: start;

            Card {
                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.HardDrive;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Drive info";
                        }

                        HorizontalLayout {
                            alignment: end;

                            if should-reformat: Link {
                                label: "Drive formatting guide";
                                uri: "https://gbatemp.net/threads/usb-loader-gx-troubleshooting-guide.617564/#fs";
                            }
                        }
                    }

                    HorizontalLine { }

                    Text {
                        text: "Filesystem: \{Logic.drive-info.fs-kind}  (\{fs-comment(Logic.drive-info.fs-kind)})";
                    }

                    Text {
                        text: "Allocation granularity: \{Logic.drive-info.allocation-granularity}  (\{allocation-granularity-comment})";
                    }
                }
            }

            Card {
                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.ImageDown;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Covers";
                        }
                    }

                    HorizontalLine { }

                    HorizontalLayout {
                        spacing: 10px;

                        b := IconButton {
                            icon: IconSet.Play;
                            width: self.height;
                            clicked => Logic.download-all-covers(false);
                        }

                        Text {
                            height: b.height;
                            vertical-alignment: center;
                            text: "Download covers for USB Loader GX";
                        }
                    }

                    HorizontalLayout {
                        spacing: 10px;

                        IconButton {
                            icon: IconSet.Play;
                            width: self.height;
                            clicked => Logic.download-all-covers(true);
                        }

                        Text {
                            height: b.height;
                            vertical-alignment: center;
                            text: "Download covers for WiiFlow";
                        }
                    }
                }
            }

            Card {
                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.BrushCleaning;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Cleanup";
                        }
                    }

                    HorizontalLine { }

                    HorizontalLayout {
                        spacing: 10px;

                        IconButton {
                            icon: IconSet.Play;
                            width: self.height;
                            clicked => Logic.normalize-dir-layout();
                        }

                        Text {
                            height: b.height;
                            vertical-alignment: center;
                            text: "Normalize paths (makes sure the game directories' layouts are correct)";
                        }
                    }

                    HorizontalLayout {
                        spacing: 10px;

                        IconButton {
                            icon: IconSet.Play;
                            width: self.height;
                            clicked => {
                                scrubbing-all-games = true;
                            }
                        }

                        Text {
                            height: b.height;
                            vertical-alignment: center;
                            text: "Remove the update partition from all .wbfs files";
                        }
                    }
                }
            }

            Card {
                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.MonitorUp;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Wiiload";
                        }
                    }

                    HorizontalLine { }

                    Text {
                        text: "Wiiload is a method of loading .dol and .elf files over the network.\nAlso, you can use Wiiload to install homebrew applications directly onto your SD card.\nIf the icon in the very bottom right of the Homebrew Channel is lit up, it should work for you.\nPressing the home button in the Homebrew Channel will reveal your Wii's IP.";
                    }

                    HorizontalLine { }

                    HorizontalLayout {
                        alignment: space-between;

                        VerticalLayout {
                            alignment: center;

                            IconButton {
                                icon: IconSet.FileUp;
                                label: "Choose a zip/dol/elf";
                                clicked => Logic.wiiload-local-file(ip.text);
                            }
                        }

                        HorizontalLayout {
                            spacing: 10px;

                            VerticalLayout {
                                alignment: center;

                                Text {
                                    text: "Wii IP:";
                                }
                            }

                            ip := LineEdit {
                                width: 200px;
                                text: Logic.config.wii-ip;
                            }
                        }
                    }
                }
            }

            if Platform.os == OperatingSystemType.macos: Card {
                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Apple;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "macOS";
                        }
                    }

                    HorizontalLine { }

                    HorizontalLayout {
                        spacing: 10px;

                        IconButton {
                            icon: IconSet.Play;
                            width: self.height;
                            clicked => Logic.run-dot-clean();
                        }

                        Text {
                            height: b.height;
                            vertical-alignment: center;
                            text: "Run dot_clean (removes ._ files)";
                        }
                    }
                }
            }
        }
    }
}
