// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconSet, IconDisplay, Icon } from "@lucide";
import { ScrollView, LineEdit } from "std-widgets.slint";
import { MyPalette } from "styling.slint";
import { Card } from "components/card.slint";
import { HorizontalLine } from "components/horizontal-line.slint";
import { UiState } from "ui-state.slint";
import { Link } from "components/link.slint";
import { IconButton } from "components/icon-button.slint";
import { Message, Dispatcher } from "messages.slint";

export component ToolboxPage inherits VerticalLayout {
    private property <int> optimal-allocation-granularity: (UiState.drive-info.total-gib <= 32) ? 32768 : 65536;
    private property <bool> is-optimal-allocation-granularity: UiState.drive-info.allocation-granularity == optimal-allocation-granularity;
    private property <bool> should-reformat: UiState.drive-info.fs-kind != "FAT32" || !is-optimal-allocation-granularity;

    pure function fs-icon(fs-kind: string) -> Icon {
        if fs-kind == "FAT32" {
            IconSet.Check
        } else {
            IconSet.TriangleAlert
        }
    }

    pure function fs-comment(fs-kind: string) -> string {
        if fs-kind == "FAT32" {
            "optimal choice for game backups and homebrew apps"
        } else if fs-kind == "NTFS" || fs-kind == "exFAT" {
            "limited support for game backups and homebrew apps"
        } else {
            "won't work for game backups and homebrew apps"
        }
    }

    pure function allocation-granularity-icon(optimal: bool) -> Icon {
        if optimal {
            IconSet.Check
        } else {
            IconSet.TriangleAlert
        }
    }

    pure function allocation-granularity-comment(optimal: bool) -> string {
        if optimal {
            "optimal"
        } else {
            "not optimal, but should work"
        }
    }

    HorizontalLayout {
        height: 58px;
        padding: 20px;
        padding-left: 10px;
        spacing: 5px;

        IconDisplay {
            icon: IconSet.ChevronRight;
            size: 18px;
            stroke: MyPalette.foreground;
        }

        Text {
            text: "Toolbox";
            font-size: 18px;
        }
    }

    ScrollView {
        VerticalLayout {
            width: 100%;
            padding: 10px;
            padding-top: 0px;
            spacing: 10px;
            alignment: start;

            if !UiState.config.mount-point.is-empty: Card {
                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.HardDrive;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Drive info";
                        }

                        HorizontalLayout {
                            alignment: end;

                            if should-reformat: Link {
                                label: "Drive formatting guide";
                                uri: "https://gbatemp.net/threads/usb-loader-gx-troubleshooting-guide.617564/#fs";
                            }
                        }
                    }

                    HorizontalLine { }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: fs-icon(UiState.drive-info.fs-kind);
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Filesystem: \{UiState.drive-info.fs-kind}  (\{fs-comment(UiState.drive-info.fs-kind)})";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: allocation-granularity-icon(is-optimal-allocation-granularity);
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Allocation granularity: \{UiState.drive-info.allocation-granularity}  (\{allocation-granularity-comment(is-optimal-allocation-granularity)})";
                        }
                    }
                }
            }

            if !UiState.config.mount-point.is-empty: Card {
                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Loader;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Game backup loaders";
                        }
                    }

                    HorizontalLine { }

                    HorizontalLayout {
                        spacing: 10px;

                        IconButton {
                            icon: IconSet.Play;
                            width: self.height;
                            clicked => Dispatcher.dispatch(Message.DownloadAllCoversForUsbLoaderGX, "");
                        }

                        Text {
                            height: b.height;
                            vertical-alignment: center;
                            text: "Download covers for USB Loader GX";
                        }
                    }

                    HorizontalLayout {
                        spacing: 10px;

                        IconButton {
                            icon: IconSet.Play;
                            width: self.height;
                            clicked => Dispatcher.dispatch(Message.DownloadAllBanners, "");
                        }

                        Text {
                            height: b.height;
                            vertical-alignment: center;
                            text: "Download banners for USB Loader GX (GameCube games)";
                        }
                    }

                    HorizontalLayout {
                        spacing: 10px;

                        IconButton {
                            icon: IconSet.Play;
                            width: self.height;
                            clicked => Dispatcher.dispatch(Message.DownloadWiitdbXml, "");
                        }

                        Text {
                            height: b.height;
                            vertical-alignment: center;
                            text: "Download wiitdb.xml for USB Loader GX";
                        }
                    }

                    HorizontalLayout {
                        spacing: 10px;

                        IconButton {
                            icon: IconSet.Play;
                            width: self.height;
                            clicked => Dispatcher.dispatch(Message.DownloadAllCoversForWiiFlow, "");
                        }

                        Text {
                            height: b.height;
                            vertical-alignment: center;
                            text: "Download covers for WiiFlow";
                        }
                    }
                }
            }

            if !UiState.config.mount-point.is-empty: Card {
                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.BrushCleaning;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Cleanup";
                        }
                    }

                    HorizontalLine { }

                    HorizontalLayout {
                        spacing: 10px;

                        IconButton {
                            icon: IconSet.Play;
                            width: self.height;
                            clicked => Dispatcher.dispatch(Message.NormalizeDirLayout, "");
                        }

                        Text {
                            height: b.height;
                            vertical-alignment: center;
                            text: "Normalize paths (makes sure the game directories' layouts are correct)";
                        }
                    }

                    HorizontalLayout {
                        spacing: 10px;

                        IconButton {
                            icon: IconSet.Play;
                            width: self.height;
                            clicked => {
                                UiState.scrubbing-all-games = true;
                            }
                        }

                        Text {
                            height: b.height;
                            vertical-alignment: center;
                            text: "Remove the update partition from all .wbfs files";
                        }
                    }
                }
            }

            Card {
                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.MonitorUp;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Wiiload";
                        }
                    }

                    HorizontalLine { }

                    Text {
                        text: "Wiiload is a method of loading .dol and .elf files over the network.\nAlso, you can use Wiiload to install homebrew applications directly onto your SD card.\nIf the icon in the very bottom right of the Homebrew Channel is lit up, it should work for you.\nPressing the home button in the Homebrew Channel will reveal your Wii's IP.";
                    }

                    HorizontalLine { }

                    HorizontalLayout {
                        alignment: space-between;

                        VerticalLayout {
                            alignment: center;

                            IconButton {
                                icon: IconSet.FileUp;
                                label: "Choose a zip/dol/elf";
                                clicked => Dispatcher.dispatch(Message.WiiloadLocalFile, ip.text);
                            }
                        }

                        HorizontalLayout {
                            spacing: 10px;

                            VerticalLayout {
                                alignment: center;

                                Text {
                                    text: "Wii IP:";
                                }
                            }

                            ip := LineEdit {
                                width: 200px;
                                text: UiState.config.wii-ip;
                            }
                        }
                    }
                }
            }

            Card {
                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Shuffle;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Manual conversion (using NOD)";
                        }

                        HorizontalLayout {
                            alignment: end;

                            if should-reformat: Link {
                                label: "https://github.com/encounter/nod";
                                uri: "https://github.com/encounter/nod";
                            }
                        }
                    }

                    HorizontalLine { }

                    HorizontalLayout {
                        spacing: 10px;

                        b := IconButton {
                            icon: IconSet.Play;
                            width: self.height;
                            clicked => Dispatcher.dispatch(Message.ArchiveManually, "");
                        }

                        Text {
                            height: b.height;
                            vertical-alignment: center;
                            text: "Select in-path and out-path and run the conversion";
                        }
                    }
                }
            }

            if Platform.os == OperatingSystemType.macos && !UiState.config.mount-point.is-empty: Card {
                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Apple;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "macOS";
                        }
                    }

                    HorizontalLine { }

                    HorizontalLayout {
                        spacing: 10px;

                        IconButton {
                            icon: IconSet.Play;
                            width: self.height;
                            clicked => Dispatcher.dispatch(Message.RunDotClean, "");
                        }

                        Text {
                            height: b.height;
                            vertical-alignment: center;
                            text: "Run dot_clean (removes ._ files)";
                        }
                    }
                }
            }
        }
    }
}
