// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

export enum Page {
    GameGrid,
    Settings,
    About,
    Game,
}

@rust-attr(derive(serde::Serialize, serde::Deserialize))
@rust-attr(serde(default, rename_all = "snake_case"))
export struct ConfigContents {
    always-split: bool,
    mount-point: string,
    remove-sources-apps: bool,
    remove-sources-games: bool,
    scrub-update-partition: bool,
    sort-by: string,
    view-as: string,
    wii-ip: string,
    txt-codes-source: string,
    theme-preference: string,
    wii-output-format: string,
    gc-output-format: string,
    show-wii: bool,
    show-gc: bool,
    known-drives: [string],
}

export struct Config {
    path: string,
    contents: ConfigContents,
}

export enum IconButtonKind {
    Primary,
    Secondary,
    Warning,
    Danger,
}

export enum MessageKind {
    Info,
    Error,
    DeleteDir,
}

export struct Message {
    text: string,
    kind: MessageKind,
    data: string,
}

export struct Game {
    path: string,
    is-wii: bool,
    size-gib: float,
    title: string,
    id: string,
    cover: image,
}

export struct GameList {
    games: [Game],
    total-size: float,
    wii-count: int,
    wii-size: float,
    gc-count: int,
    gc-size: float,
}

export struct DiscInfo {
    // discheader
    id: string,
    title: string,
    is_wii: bool,
    is_gc: bool,
    disc_num: int,
    disc_version: int,

    // discmeta
    format: string,
    compression: string,
    block_size: string,
    decrypted: bool,
    needs_hash_recovery: bool,
    lossless: bool,
    disc_size: string,
    crc32: string,
    md5: string,
    sha1: string,
    xxh64: string,

    // misc
    is_worth_stripping: bool,
} 

export struct EmptyResult {
    err: string,
}

export struct DiscInfoResult {
    value: DiscInfo,
    err: string,
}
