// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

export enum Page {
    Games,
    Settings,
    About,
}

@rust-attr(derive(serde::Serialize, serde::Deserialize))
@rust-attr(serde(default, rename_all = "snake_case"))
export struct ConfigContents {
    always_split: bool,
    mount_point: string,
    remove_sources_apps: bool,
    remove_sources_games: bool,
    scrub_update_partition: bool,
    sort_by: string,
    view_as: string,
    wii_ip: string,
    txt_codes_source: string,
    theme_preference: string,
    wii_output_format: string,
    gc_output_format: string,
    known_drives: [string],
}

export struct Config {
    path: string,
    contents: ConfigContents,
}

export enum IconButtonKind {
    Primary,
    Secondary,
    Warning,
    Danger,
}

export struct Message {
    text: string,
    button: IconButtonKind,
}

export struct Game {
    path: string,
    is_wii: bool,
    size_gib: float,
    title: string,
    id: string,
    cover: image,
}

export struct GameList {
    games: [Game],
    filtered_games: [Game],
    total_size: float,
    wii_count: int,
    wii_size: float,
    gc_count: int,
    gc_size: float,
}
