// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

export enum Page {
    Games,
    HomebrewApps,
    Osc,
    Settings,
    About,
}

export struct DisplayedConfig {
    path: string,
    mount-point: string,
    always-split: bool,
    remove-sources-apps: bool,
    remove-sources-games: bool,
    scrub-update-partition: bool,
    sort-by: int,
    view-as: int,
    wii-ip: string,
    txt-codes-source: int,
    theme-preference: int,
    wii-output-format: int,
    gc-output-format: int,
    known-drives: [string],
    show-wii: bool,
    show-gc: bool,
}

export struct DisplayedDiscInfo {
    path: string,
    format: string,
    game-id: string,
    game-title: string,
    region: string,
    is-wii: bool,
    is-gc: bool,
    disc-number: int,
    disc-version: int,
    is-worth-scrubbing: bool,
    crc32: string,
}

export struct DisplayedGame {
    idx: int,
    path: string,
    is-wii: bool,
    size-gib: float,
    title: string,
    id: string,
    cover: image,
    search-term: string,
}

export struct DisplayedHomebrewApp {
    idx: int,
    path: string,
    slug: string,
    size-mib: float,
    name: string,
    coder: string,
    version: string,
    release-date: string,
    short-description: string,
    long-description: string,
    icon: image,
    search-term: string,
    osc-idx: int,
}

export enum ConversionKind {
    Standard,
    Archive,
    Scrub,
}

export struct QueuedConversion {
    kind: ConversionKind,
    path: string,
    game-idx: int,
}

export struct DisplayedDriveInfo {
    label: string,
    used-gib: float,
    games-gib: float,
    apps-mib: float,
    total-gib: float,
    fs-kind: string,
}

export struct DisplayedNotification {
    text: string,
    critical: bool,
}

export struct DisplayedOscApp {
    idx: int,
    slug: string,
    name: string,
    author: string,
    version: string,
    uncompressed-size-mib: float,
    release-date: string,
    short-description: string,
    long-description: string,
    search-term: string,
    release-date: string,
    icon: image,
}
