// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import {
    DisplayedConfig,
    DisplayedDriveInfo,
    DisplayedGame,
    DisplayedHomebrewApp,
    DisplayedOscApp,
    Notification,
    DisplayedDiscInfo,
    Page,
} from "types.slint";

export global UiState {
    in-out property <Page> current-page: Page.Games;
    in-out property <DisplayedGame> current-game;
    in-out property <DisplayedHomebrewApp> current-homebrew-app;
    in-out property <DisplayedOscApp> current-osc-app;
    in-out property <bool> scrubbing-current-game: false;
    in-out property <DisplayedGame> game-to-delete;
    in-out property <DisplayedHomebrewApp> homebrew-app-to-delete;
    in-out property <bool> scrubbing-all-games: false;
    in-out property <DisplayedOscApp> wiiloading-osc-app;

    in-out property <DisplayedConfig> config;
    in-out property <string> app-version;
    in-out property <string> data-dir;
    in-out property <DisplayedDriveInfo> drive-info;
    in-out property <[DisplayedGame]> games;
    in-out property <[DisplayedHomebrewApp]> homebrew-apps;
    in-out property <[DisplayedOscApp]> osc-apps;
    in-out property <[Notification]> notifications;
    in-out property <[string]> conversion-queue;
    in-out property <[string]> games-to-add;
    in-out property <string> status;
    in-out property <string> crc32-status;
    in-out property <int> osc-refreshed-x-hours-ago;
    in-out property <int> osc-refreshed-x-minutes-ago;
    in-out property <DisplayedDiscInfo> current-disc-info;
    in-out property <string> latest-version;
}
