name: Release

on:
  push:
    branches:
      - main
      - dev
      - slint
    tags:
      - "v*.*.*"
    paths:
      - "build.rs"
      - "src/**"
      - "ui/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "package/**"
      - "containers/**"
      - "cargo-config.toml"
      - ".github/workflows/release.yml"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

env:
  VERSION_NAME: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}

jobs:
  # ==================================================================================
  #  Build & Bundle Jobs
  # ==================================================================================
  build-linux:
    name: Build for Linux
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-22.04
            arch: x86_64
            target: x86_64-unknown-linux-gnu
          - runner: ubuntu-22.04-arm
            arch: aarch64
            target: aarch64-unknown-linux-gnu
          - runner: ubuntu-22.04
            arch: i686
            target: i686-unknown-linux-gnu
          - runner: ubuntu-22.04-arm
            arch: armhf
            target: armv7-unknown-linux-gnueabihf

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install LLVM and Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo ln -sf $(which clang-21) /usr/bin/cc
          sudo ln -sf $(which lld-21) /usr/bin/ld

      - name: Install i686 dependencies
        if: matrix.arch == 'i686'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc-i686-linux-gnu libc6-dev:i386 libfontconfig-dev:i386 pkg-config:i386

      - name: Install armhf dependencies
        if: matrix.arch == 'armhf'
        run: |
          sudo dpkg --add-architecture armhf
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf libc6-dev:armhf libfontconfig-dev:armhf pkg-config:armhf

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.94
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Download appimagetool
        run: |
          wget "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-${{ matrix.arch }}.AppImage" -O appimagetool
          chmod +x appimagetool

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }} --no-default-features --features "https-bundled"
          cp target/${{ matrix.target }}/release/TinyWiiBackupManager .
        env:
          CC: clang-21
          AR: llvm-ar-21
          CFLAGS_x86_64-unknown-linux-gnu: -O3 -flto
          CFLAGS_aarch64-unknown-linux-gnu: -O3 -flto
          PKG_CONFIG_i686-unknown-linux-gnu: /usr/bin/i686-pc-linux-gnu-pkg-config
          PKG_CONFIG_armv7-unknown-linux-gnueabihf: /usr/bin/arm-unknown-linux-gnueabihf-pkg-config
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS: -C linker-plugin-lto -C link-arg=-fuse-ld=lld
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUSTFLAGS: -C linker-plugin-lto -C link-arg=-fuse-ld=lld
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: clang-21
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: clang-21
          CARGO_TARGET_I686_UNKNOWN_LINUX_GNU_LINKER: i686-linux-gnu-gcc
          CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc

      - name: Package AppImage
        run: |
          cp -rP package/linux/AppDir TinyWiiBackupManager.AppDir
          install -Dm0755 TinyWiiBackupManager TinyWiiBackupManager.AppDir/usr/bin/TinyWiiBackupManager
          mkdir -p dist
          cd dist
          ../appimagetool \
            --comp zstd --mksquashfs-opt -Xcompression-level --mksquashfs-opt 19 \
            -u "gh-releases-zsync|mq1|TinyWiiBackupManager|latest|*${{ matrix.arch }}.AppImage.zsync" \
            ../TinyWiiBackupManager.AppDir \
            "TinyWiiBackupManager-${{ env.VERSION_NAME }}-linux-${{ matrix.arch }}.AppImage"
        env:
          VERSION: ${{ env.VERSION_NAME }}
          ARCH: ${{ matrix.arch }}

      - name: Upload Linux distributables
        uses: actions/upload-artifact@v7
        with:
          name: dist-linux-${{ matrix.arch }}
          path: dist/*

  build-windows:
    name: Build for Windows
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            target: aarch64-pc-windows-msvc
          - arch: x64
            target: x86_64-pc-windows-msvc
          - arch: x86
            target: i686-pc-windows-msvc

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.94
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Download VC-LTL5
        if: matrix.arch != 'arm64'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/Chuyu-Team/VC-LTL5/releases/latest/download/VC-LTL-Binary.7z" -OutFile "VC-LTL-Binary.7z"
          7z x VC-LTL-Binary.7z -oVC-LTL-Binary

      - name: Download YY-Thunks
        if: matrix.arch != 'arm64'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/Chuyu-Team/YY-Thunks/releases/latest/download/YY-Thunks-Objs.zip" -OutFile "YY-Thunks-Objs.zip"
          7z x YY-Thunks-Objs.zip -oYY-Thunks-Objs

      - name: Download UPX
        if: matrix.arch != 'arm64'
        shell: pwsh
        run: choco install upx

      - name: Build binary
        shell: pwsh
        run: |
          cargo build --release --target ${{ matrix.target }}
        env:
          CC: clang-cl
          AR_aarch64-pc-windows-msvc: llvm-lib
          CFLAGS_x86_64-pc-windows-msvc: /clang:-O3
          CFLAGS_i686-pc-windows-msvc: /clang:-O3
          CFLAGS_aarch64-pc-windows-msvc: /clang:-O3 /clang:-flto /clang:-fuse-ld=lld-link
          CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_RUSTFLAGS: -l dylib=ole32 -C link-arg=/SUBSYSTEM:WINDOWS,5.2 -L VC-LTL-Binary\TargetPlatform\5.2.3790.0\lib\x64 -C link-arg=YY-Thunks-Objs\objs\x64\YY_Thunks_for_WinXP.obj
          CARGO_TARGET_I686_PC_WINDOWS_MSVC_RUSTFLAGS: -l dylib=ole32 -C link-arg=/SUBSYSTEM:WINDOWS,5.1 -L VC-LTL-Binary\TargetPlatform\5.1.2600.0\lib\Win32 -C link-arg=YY-Thunks-Objs\objs\x86\YY_Thunks_for_WinXP.obj
          CARGO_TARGET_AARCH64_PC_WINDOWS_MSVC_RUSTFLAGS: -C linker-plugin-lto
          CARGO_TARGET_AARCH64_PC_WINDOWS_MSVC_LINKER: lld-link

      - name: Package binary (UPX)
        if: matrix.arch != 'arm64'
        shell: pwsh
        run: |
          New-Item -Path "dist" -ItemType Directory -Force
          upx --best --lzma -o "dist\TinyWiiBackupManager-${{ env.VERSION_NAME }}-windows-${{ matrix.arch }}.exe" "target\${{ matrix.target }}\release\TinyWiiBackupManager.exe"

      - name: Package binary (no UPX)
        if: matrix.arch == 'arm64'
        shell: pwsh
        run: |
          New-Item -Path "dist" -ItemType Directory -Force
          Copy-Item "target\${{ matrix.target }}\release\TinyWiiBackupManager.exe" "dist\TinyWiiBackupManager-${{ env.VERSION_NAME }}-windows-${{ matrix.arch }}.exe"

      - name: Upload Windows distributables
        uses: actions/upload-artifact@v7
        with:
          name: dist-windows-${{ matrix.arch }}
          path: dist/*

  build-macos:
    name: Build for macOS
    runs-on: macos-26
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            target: aarch64-apple-darwin
          - arch: x86_64
            target: x86_64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install LLVM and Clang
        run: brew install llvm@21

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.94
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }}
          cp target/${{ matrix.target }}/release/TinyWiiBackupManager .
        env:
          CC: /opt/homebrew/opt/llvm@21/bin/clang
          CFLAGS: -O3

      - name: Upload macOS binaries
        uses: actions/upload-artifact@v7
        with:
          name: build-macos-${{ matrix.arch }}
          path: target/${{ matrix.target }}/release/TinyWiiBackupManager

  build-macos-universal:
    name: Build for macOS (Universal)
    runs-on: macos-26
    needs: [build-macos]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Download macOS binaries
        uses: actions/download-artifact@v8
        with:
          pattern: "build-macos-*"

      - name: Create the .app bundle
        run: |
          cp -r package/macos/App TinyWiiBackupManager.app
          mkdir -p TinyWiiBackupManager.app/Contents/MacOS
          /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string ${VERSION_NAME#v}" TinyWiiBackupManager.app/Contents/Info.plist

      - name: Build the fat binary
        run: |
          lipo -create \
            -output TinyWiiBackupManager.app/Contents/MacOS/TinyWiiBackupManager \
            build-macos-arm64/TinyWiiBackupManager \
            build-macos-x86_64/TinyWiiBackupManager
          chmod 755 TinyWiiBackupManager.app/Contents/MacOS/TinyWiiBackupManager

      - name: Sign the .app bundle
        run: codesign --force --deep -s - TinyWiiBackupManager.app

      - name: Install appdmg
        run: npm i -g appdmg

      - name: Create Universal DMG
        run: |
          mkdir dist
          appdmg package/macos/appdmg.json "dist/TinyWiiBackupManager-${{ env.VERSION_NAME }}-macos-universal.dmg"

      - name: Upload macOS distributables
        uses: actions/upload-artifact@v7
        with:
          name: dist-macos-universal
          path: dist/*

  # ==================================================================================
  #  Release Job: Collects all artifacts and creates a single GitHub Release.
  # ==================================================================================
  release:
    name: Create GitHub Release
    if: github.ref_type == 'tag'
    runs-on: ubuntu-slim
    needs: [build-linux, build-windows, build-macos, build-macos-universal]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Download distributables
        uses: actions/download-artifact@v8
        with:
          path: dist
          pattern: "dist-*" # This pattern will match all final distributable artifacts
          merge-multiple: true # This places all matching artifacts into a single 'dist' directory

      - name: Create version.txt
        run: echo -n $(yq '.package.version' Cargo.toml) > version.txt # Write without line break

      - name: Extract release notes
        run: awk '/## \[${{ env.VERSION_NAME }}\]/{p=1; print; next} /^## \[/{p=0} p' CHANGELOG.md > BODY.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            version.txt
          body_path: BODY.md
          prerelease: ${{ contains(env.VERSION_NAME, 'alpha') || contains(env.VERSION_NAME, 'beta') || contains(env.VERSION_NAME, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
