name: Release

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*.*.*"
    paths:
      - "build.rs"
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "package/**"
      - "scripts/**"
      - ".github/workflows/release.yml"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

env:
  VERSION_NAME: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}

jobs:
  # ==================================================================================
  #  Build & Bundle Jobs: Run the platform-specific build scripts.
  # ==================================================================================
  build-linux:
    name: Build for Linux
    runs-on: ${{ matrix.runner }}
    container:
      image: ubuntu:20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            arch: x86_64-v3
            appimage-arch: x86_64
          - runner: ubuntu-24.04
            arch: x86_64-v2
            appimage-arch: x86_64
          - runner: ubuntu-24.04
            arch: x86_64
            appimage-arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: arm64
            appimage-arch: aarch64
          - runner: ubuntu-24.04
            arch: x86
            appimage-arch: i686
          - runner: ubuntu-24.04-arm
            arch: armhf
            appimage-arch: armhf

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.93
        with:
          components: rust-src

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y lsb-release wget software-properties-common gnupg

      - name: Install x86 dependencies
        if: matrix.arch == 'x86'
        run: apt-get install -y libc6-dev-i386

      - name: Install armhf dependencies
        if: matrix.arch == 'armhf'
        run: apt-get install -y gcc-arm-linux-gnueabihf

      - name: Install LLVM and Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          ./llvm.sh 21
          ln -sf $(which clang-21) /usr/bin/cc
          ln -sf $(which lld-21) /usr/bin/ld

      - name: Download appimagetool
        run: |
          wget "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-${{ matrix.appimage-arch }}.AppImage"
          chmod +x appimagetool-${{ matrix.appimage-arch }}.AppImage

      - name: Build binary
        run: scripts/build-linux-${{ matrix.arch }}.sh

      - name: Package AppImage
        run: scripts/package-linux-appimage.sh ${{ env.VERSION_NAME }} ${{ matrix.arch }} ./appimagetool-${{ matrix.appimage-arch }}.AppImage ${{ matrix.appimage-arch }}

      - name: Upload Linux distributables
        uses: actions/upload-artifact@v7
        with:
          name: dist-linux-${{ matrix.arch }}
          path: dist/*

  build-windows:
    name: Build for Windows
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: windows-2025
            platform: windows
            arch: x86_64-v3
          - runner: windows-2025
            platform: windows
            arch: x86_64-v2
          - runner: windows-2025
            platform: windows
            arch: x86_64
          - runner: windows-11-arm
            platform: windows
            arch: arm64
          - runner: windows-2025
            platform: windows
            arch: x86
          - runner: windows-2022
            platform: windows-legacy
            arch: x86_64
          - runner: windows-2022
            platform: windows-legacy
            arch: x86

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.93
        with:
          components: rust-src

      - name: Download VC-LTL5
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/Chuyu-Team/VC-LTL5/releases/latest/download/VC-LTL-Binary.7z" -OutFile "VC-LTL-Binary.7z"
          7z x VC-LTL-Binary.7z -oVC-LTL-Binary

      - name: Download YY-Thunks
        if: matrix.platform == 'windows-legacy'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/Chuyu-Team/YY-Thunks/releases/latest/download/YY-Thunks-Objs.zip" -OutFile "YY-Thunks-Objs.zip"
          7z x YY-Thunks-Objs.zip -oYY-Thunks-Objs

      - name: Build and package binary
        shell: pwsh
        run: |
          .\scripts\build-${{ matrix.platform }}-${{ matrix.arch }}.ps1
          .\scripts\package-windows.ps1 -VersionName ${{ env.VERSION_NAME }} -Platform ${{ matrix.platform }} -Arch ${{ matrix.arch }}

      - name: Upload Windows distributables
        uses: actions/upload-artifact@v7
        with:
          name: dist-${{ matrix.platform }}-${{ matrix.arch }}
          path: dist/*

  build-macos:
    name: Build for macOS
    runs-on: macos-26
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
          - arch: x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install LLVM and Clang
        run: brew install llvm@21

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.93
        with:
          components: rust-src

      - name: Build and package
        run: |
          scripts/build-macos-${{ matrix.arch }}.sh
          scripts/package-macos.sh ${{ env.VERSION_NAME }}
          scripts/zip-macos-app.sh ${{ env.VERSION_NAME }} ${{ matrix.arch }}

      - name: Upload macOS distributables
        uses: actions/upload-artifact@v7
        with:
          name: build-macos-${{ matrix.arch }}
          path: out/*

  package-macos:
    name: Package Universal2 macOS app and DMGs
    runs-on: macos-26
    needs: [build-macos]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Download macOS .app distributables
        uses: actions/download-artifact@v8
        with:
          pattern: "build-macos-*"

      - name: Extract the .zip distributables
        run: |
          ditto -x -k "build-macos-arm64/TinyWiiBackupManager-${{ env.VERSION_NAME }}-macos-arm64.zip" build-macos-arm64
          ditto -x -k "build-macos-x86_64/TinyWiiBackupManager-${{ env.VERSION_NAME }}-macos-x86_64.zip" build-macos-x86_64
          cp -r build-macos-arm64/TinyWiiBackupManager.app TinyWiiBackupManager.app

      - name: Create the Universal2 app
        run: |
          lipo -create \
            -output TinyWiiBackupManager.app/Contents/MacOS/TinyWiiBackupManager \
            build-macos-arm64/TinyWiiBackupManager.app/Contents/MacOS/TinyWiiBackupManager \
            build-macos-x86_64/TinyWiiBackupManager.app/Contents/MacOS/TinyWiiBackupManager
          codesign --force --deep -s - TinyWiiBackupManager.app

      - name: Install appdmg
        run: npm i -g appdmg

      - name: Create DMGs (assets from sindresorhus/create-dmg)
        run: |
          mkdir dist
          appdmg package/macos/appdmg-x86_64.json "dist/TinyWiiBackupManager-${{ env.VERSION_NAME }}-macos-x86_64.dmg"
          appdmg package/macos/appdmg-arm64.json "dist/TinyWiiBackupManager-${{ env.VERSION_NAME }}-macos-arm64.dmg"
          appdmg package/macos/appdmg-universal.json "dist/TinyWiiBackupManager-${{ env.VERSION_NAME }}-macos-universal.dmg"

      - name: Upload macOS distributables
        uses: actions/upload-artifact@v7
        with:
          name: dist-macos-universal
          path: dist/*

  # ==================================================================================
  #  Release Job: Collects all artifacts and creates a single GitHub Release.
  # ==================================================================================
  release:
    name: Create GitHub Release
    if: github.ref_type == 'tag'
    runs-on: ubuntu-slim
    needs: [build-linux, build-windows, package-macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Download distributables
        uses: actions/download-artifact@v8
        with:
          path: dist
          pattern: "dist-*" # This pattern will match all final distributable artifacts
          merge-multiple: true # This places all matching artifacts into a single 'dist' directory

      - name: Create version.txt
        run: echo -n $(yq '.package.version' Cargo.toml) > version.txt # Write without line break

      - name: Generate release notes
        run: scripts/print-changes.py $VERSION_NAME > BODY.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            version.txt
          body_path: BODY.md
          prerelease: ${{ contains(env.VERSION_NAME, 'alpha') || contains(env.VERSION_NAME, 'beta') || contains(env.VERSION_NAME, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
