name: Release

on:
  push:
    branches:
      - main
      - dev
      - slint
    tags:
      - "v*.*.*"
    paths:
      - "build.rs"
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "package/**"
      - "containers/**"
      - "cargo-config.toml"
      - ".github/workflows/release.yml"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

env:
  VERSION_NAME: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}

jobs:
  # ==================================================================================
  #  Build & Bundle Jobs
  # ==================================================================================
  build-linux:
    name: Build for Linux
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-22.04
            arch: x86_64
            target: x86_64-unknown-linux-gnu
          - runner: ubuntu-22.04-arm
            arch: aarch64
            target: aarch64-unknown-linux-gnu
          - runner: ubuntu-22.04
            arch: i686
            target: i686-unknown-linux-gnu
          - runner: ubuntu-22.04-arm
            arch: armhf
            target: armv7-unknown-linux-gnueabihf

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install LLVM and Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo ln -sf $(which clang-21) /usr/bin/cc
          sudo ln -sf $(which lld-21) /usr/bin/ld

      - name: Install i686 cross-linker
        if: matrix.arch == 'i686'
        run: sudo apt-get install -y gcc-i686-linux-gnu

      - name: Install armhf cross-linker
        if: matrix.arch == 'armhf'
        run: sudo apt-get install -y gcc-arm-linux-gnueabihf

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.94

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Download appimagetool
        run: |
          wget "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-${{ matrix.arch }}.AppImage" -O appimagetool
          chmod +x appimagetool

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }}
          cp target/${{ matrix.target }}/release/TinyWiiBackupManager .
        env:
          CC: clang-21
          AR: llvm-ar-21
          CFLAGS_x86_64-unknown-linux-gnu: -O3 -flto
          CFLAGS_aarch64-unknown-linux-gnu: -O3 -flto
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS: -C linker-plugin-lto -C link-arg=-fuse-ld=lld
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUSTFLAGS: -C linker-plugin-lto -C link-arg=-fuse-ld=lld
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: clang
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: clang
          CARGO_TARGET_I686_UNKNOWN_LINUX_GNU_LINKER: i686-linux-gnu-gcc
          CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc

      - name: Package AppImage
        run: |
          cp -rP package/linux/AppDir TinyWiiBackupManager.AppDir
          install -Dm0755 TinyWiiBackupManager TinyWiiBackupManager.AppDir/usr/bin/TinyWiiBackupManager
          mkdir -p dist
          cd dist
          ../appimagetool \
            --comp zstd --mksquashfs-opt -Xcompression-level --mksquashfs-opt 19 \
            -u "gh-releases-zsync|mq1|TinyWiiBackupManager|latest|*${{ matrix.arch }}.AppImage.zsync" \
            ../TinyWiiBackupManager.AppDir \
            "TinyWiiBackupManager-${{ env.VERSION_NAME }}-linux-${{ matrix.arch }}.AppImage"
        env:
          VERSION: ${{ env.VERSION_NAME }}
          ARCH: ${{ matrix.arch }}

      - name: Upload Linux distributables
        uses: actions/upload-artifact@v7
        with:
          name: dist-linux-${{ matrix.arch }}
          path: dist/*

  build-windows:
    name: Build for Windows
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: windows-11-arm
            arch: arm64
            os: win10
            target: aarch64-pc-windows-msvc
          - runner: windows-2022
            arch: x64
            os: xp
            target: x86_64-win7-windows-msvc
          - runner: windows-2022
            arch: x86
            os: xp
            target: i686-win7-windows-msvc

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.94

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Install thunk
        shell: pwsh
        run: cargo install thunk-cli

      - name: Download VC-LTL5
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/Chuyu-Team/VC-LTL5/releases/latest/download/VC-LTL-Binary.7z" -OutFile "VC-LTL-Binary.7z"
          7z x VC-LTL-Binary.7z -oVC-LTL-Binary

      - name: Download YY-Thunks
        if: matrix.arch != 'arm64'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/Chuyu-Team/YY-Thunks/releases/latest/download/YY-Thunks-Objs.zip" -OutFile "YY-Thunks-Objs.zip"
          7z x YY-Thunks-Objs.zip -oYY-Thunks-Objs

      - name: Download UPX
        if: matrix.arch != 'arm64'
        shell: pwsh
        run: choco install upx

      - name: Build binary
        shell: pwsh
        run: |
          thunk --os ${{ matrix.os }} --arch ${{ matrix.arch }} --subsystem windows -- --release
          Copy-Item "target\win${{ matrix.os }}_build\TinyWiiBackupManager.exe" .
        env:
          CC: clang-cl
          CFLAGS: /clang:-O3
          VC_LTL: .\VC-LTL-Binary
          YY_THUNKS: ${{ matrix.arch == 'arm64' && '' || '.\YY-Thunks-Objs' }}

      - name: Package binary (UPX)
        if: matrix.arch != 'arm64'
        shell: pwsh
        run: |
          New-Item -Path "dist" -ItemType Directory -Force
          upx --best --lzma -o "dist\TinyWiiBackupManager-${{ env.VERSION_NAME }}-windows-${{ matrix.arch }}.exe" "TinyWiiBackupManager.exe" .

      - name: Package binary (no UPX)
        if: matrix.arch == 'arm64'
        shell: pwsh
        run: |
          New-Item -Path "dist" -ItemType Directory -Force
          Copy-Item "TinyWiiBackupManager.exe" "dist\TinyWiiBackupManager-${{ env.VERSION_NAME }}-windows-${{ matrix.arch }}.exe"

      - name: Upload Windows distributables
        uses: actions/upload-artifact@v7
        with:
          name: dist-windows-${{ matrix.arch }}
          path: dist/*

  build-macos:
    name: Build for macOS
    runs-on: macos-26
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            target: aarch64-apple-darwin
          - arch: x86_64
            target: x86_64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install LLVM and Clang
        run: brew install llvm@21

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.94

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Install appdmg
        run: npm i -g appdmg

      - name: Build binary
        run: |
          cargo --release --target ${{ matrix.target }}
          cp target/${{ matrix.target }}/release/TinyWiiBackupManager .
        env:
          CC: /opt/homebrew/opt/llvm@21/bin/clang
          CFLAGS: -O3

      - name: Package DMG
        run: |
          VERSION_NAME="${{ env.VERSION_NAME }}"
          cp -r package/macos/App TinyWiiBackupManager.app
          mkdir -p TinyWiiBackupManager.app/Contents/MacOS
          cp TinyWiiBackupManager TinyWiiBackupManager.app/Contents/MacOS/TinyWiiBackupManager
          /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string ${VERSION_NAME#v}" TinyWiiBackupManager.app/Contents/Info.plist
          mkdir -p dist
          appdmg package/macos/appdmg-${{ matrix.arch }}.json "dist/TinyWiiBackupManager-${{ env.VERSION_NAME }}-macos-${{ matrix.arch }}.dmg"

      - name: Upload macOS distributables
        uses: actions/upload-artifact@v7
        with:
          name: dist-macos-${{ matrix.arch }}
          path: dist/*

  build-macos-universal:
    name: Build for macOS (Universal)
    runs-on: macos-26
    needs: [build-macos]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Download macOS distributables
        uses: actions/download-artifact@v8
        with:
          pattern: "dist-macos-*"
          merge-multiple: true

      - name: Create the Universal2 app
        run: |
          # Mount arm64 DMG and copy the app
          hdiutil mount TinyWiiBackupManager-${{ env.VERSION_NAME }}-macos-arm64.dmg
          cp -r /Volumes/TinyWiiBackupManager/TinyWiiBackupManager.app TinyWiiBackupManager.app
          hdiutil unmount /Volumes/TinyWiiBackupManager

          # Mount x86_64 DMG and extract the binary
          hdiutil mount TinyWiiBackupManager-${{ env.VERSION_NAME }}-macos-x86_64.dmg
          cp /Volumes/TinyWiiBackupManager/TinyWiiBackupManager.app/Contents/MacOS/TinyWiiBackupManager TinyWiiBackupManager-x86_64
          hdiutil unmount /Volumes/TinyWiiBackupManager

          # Create the Universal binary
          lipo -create \
            -output TinyWiiBackupManager.app/Contents/MacOS/TinyWiiBackupManager \
            TinyWiiBackupManager.app/Contents/MacOS/TinyWiiBackupManager \
            TinyWiiBackupManager-x86_64

          codesign --force --deep -s - TinyWiiBackupManager.app

      - name: Install appdmg
        run: npm i -g appdmg

      - name: Create Universal DMG
        run: |
          mkdir dist
          appdmg package/macos/appdmg-arm64.json "dist/TinyWiiBackupManager-${{ env.VERSION_NAME }}-macos-universal.dmg"

      - name: Upload macOS distributables
        uses: actions/upload-artifact@v7
        with:
          name: dist-macos-universal
          path: dist/*

  # ==================================================================================
  #  Release Job: Collects all artifacts and creates a single GitHub Release.
  # ==================================================================================
  release:
    name: Create GitHub Release
    if: github.ref_type == 'tag'
    runs-on: ubuntu-slim
    needs: [build-linux, build-windows, build-macos, build-macos-universal]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Download distributables
        uses: actions/download-artifact@v8
        with:
          path: dist
          pattern: "dist-*" # This pattern will match all final distributable artifacts
          merge-multiple: true # This places all matching artifacts into a single 'dist' directory

      - name: Create version.txt
        run: echo -n $(yq '.package.version' Cargo.toml) > version.txt # Write without line break

      - name: Generate release notes
        run: scripts/print-changes.py $VERSION_NAME > BODY.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            version.txt
          body_path: BODY.md
          prerelease: ${{ contains(env.VERSION_NAME, 'alpha') || contains(env.VERSION_NAME, 'beta') || contains(env.VERSION_NAME, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
